### ISSUE TITLE
Attempt to restore a modified Minecraft save on Switch resulted in error & reboot

### ISSUE THREAD

**Issue by TheProvider0** [FlagBrew/Checkpoint#114]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: paperclip jig to RCM mode   Hekate payload
* System version: 5.1.0
* Checkpoint version: 3.3.0
* Expected behaviour: restore a modified Minecraft save
* Encountered behavior: Does not restore the save, then Error 0000F601 Failed to commit to save device, and then an error screen asking me to reboot the console
* Result code (if available): 0000F601
* Steps to reproduce:
  * step 1 Modify save on computer after backing it up
  * step 2 Put files in the correct folder
  * step 3 Enter RCM mode and launch CFW using hekate
  * step 4 Launch Checkpoint
  * step 5 Attempt to Restore my modified Minecraft save
Extra info: I was able to restore a modified save that contained one texture pack with a specific directory system which was the one used for the Pocket Edition, but any other thing I do like adding skins or adding more texture packs (with different directory systems) would result in this error.
### Feature request details

* I would like this feature...:
* Because...:

**Comment by PuppyTails** [comment]
I've Noticed this happens when modifying (modify-ing?) a save on Mac, but the error didn't happen when I modify-ed the save on windows, I could be wrong.

**Comment by BernardoGiordano** [comment]
Are you using the modified hekate files for layeredfs?

**Comment by IntaroArt** [comment]
I got this error as well, some kind of issue with being in airplane mode.

1) disconnect from wifi via clear wifi settings
2) turn off airplane mode

**Comment by BernardoGiordano** [comment]
The solution is to use stable Hekate files.

**Comment by CarJem** [comment]
Like he said, the solution is to use stable Hekate files, with LayerFS.
Here's a link for everyone who is lost:
https://github.com/tumGER/SDFilesSwitch/releases/tag/v4

**Comment by BernardoGiordano** [comment]
I meant official Hekate Files without the shitty preliminar and unstable LayeredFS support.

**Comment by CarJem** [comment]
Sorry, where do I get those again, still relatively new to homebrew?

**Comment by CarJem** [comment]
I have no idea what is up with this issue, but I've heard plenty of people who have no issues with importing and restoring more than once, and I am unsure if this has something to do with the Firmware Version, CFW or LayerFS (Which I don't recommend personally recently), or Checkpoint itself. Whatever the case is this should be investigated and not ignored. I am having plenty of headaches with this problem, and often waste hours upon hours trying to restore with a modified save.

Some of the things I have experienced:
- Crashing after a second modification of LayerFS and CFW
- Crashing after the first restore on recent versions of LayerFS
- Random Crashing on restoring saves with LayerFS and CFW despite wiping the save a reloading it.
Some of the things I've heard about:
- No issues with backup and restore with modifications
- Plenty of issues related to mine

I am super confused on who's fault this issue may be caused by, whether it be LayerFS/CFW, the Firmware being used, or Checkpoint itself. I am also unable to find the "Official" files that have been mentioned by @BernardoGiordano , so some clarification there would be appreciated for those who are confused.

**Comment by 98otiss03** [comment]
I have this problem too. It happens when you try to restore/backup a save after modifying once.

**Comment by fennectech** [comment]
Ive solved this problem by deleting the minecraft savedata from horizon  (THEN OPENING THE GAME   THIS IS IMPORTANT) then restoring the save.

**Comment by fennectech** [comment]
When the issue crops up you cannot restore any save to bedrock    Not even vanilla untouched saves.

**Comment by fennectech** [comment]
Sometimes these problematic saves also cause nxshell to crash when interacting with them.

**Comment by Woody601** [comment]
@fennectech are you 100% sure that method you posted above works? I am iffy on deleting the savefile then trying to restore it and then fail like it does when restoring as I don't want to lose all of my hard work...

**Comment by fennectech** [comment]
Its the only way ive gotten it to work.  If you know your save is good thats thway i do it.

**Comment by BernardoGiordano** [comment]
Can you test with this build? https://www.dropbox.com/s/63cuarl6jou2eh9/Checkpoint.nro?dl=0

**Comment by IntaroArt** [comment]
tested it out. Was able to "restore" a modified save file once. Tried restoring to a non-modified state and a different modified game save and received error 0000F601 and the same crash error code( 2011-0301 ).

**Comment by fennectech** [comment]
Same thing for me on that buid.

**Comment by BernardoGiordano** [comment]
And with this one? https://www.dropbox.com/s/33c2gk32crfjap3/Checkpoint.nro?dl=0

**Comment by IntaroArt** [comment]
Tried it out again with the newer one you linked. Completely deleting my save game data and launching the game again so it would be a clean save file. Was able to restore once correctly. After checking and attempting again I same error. save error 0000F601 - Could not mount save state. But I couldn't see a crash code because the console froze and wouldn't show any crash error. After pressing the power button it would reboot without showing a crash error.

**Comment by BernardoGiordano** [comment]
Can you send me both original and modified Minecraft saves you're using?

**Comment by IntaroArt** [comment]
https://www.dropbox.com/s/5l19h3xvtoufjh8/MC-Checkpoint.zip?dl=0
These are the two save files used. Clean being the original save, the other adding one map.
I've been using Tumger's SD files and launching with CFW. I've tried with layeredFS and it has more issues (like you said but I was using it for a game mod). The same error occurs in EdiZon as well.

**Comment by 877cms** [comment]
Same issue here with BOTW, using RajNX CFW and lastest Checkpoint 3.4.1. 

Backs saves up ok on all other games.
On BOTW it backs up ok, but trying to restore gets me:
**Error 0000F601 Failed to commit save to device**

I have disabled fs_mitm.kip (by renaming it).

**Comment by IntaroArt** [comment]
@877cms I've had that issue as well (never used RajNX) I believe RajNX has LayeredFS enabled by default which caused that error instantly. I think it is just an issue with layeredFS and checkpoint because it should work mostly fine with CFW launched by hekate but like Bernardo said it will work best with the official hekate files.

**Comment by 877cms** [comment]
@IntaroArt yes worked fine with offical Hekate 3.2, but problems with rajnx and of course sxos didn't work either. Not sure how rajnx differs from original hekate but there is obviously something.

**Comment by BernardoGiordano** [comment]
Does this work? https://www.dropbox.com/s/wz9ca7pb27hc8l1/Checkpoint.nro?dl=0

**Comment by fennectech** [comment]
Failed to commit to device 0000F601 on hekate 4.0 with latest layeredfs and sdfiles.

**Comment by BernardoGiordano** [comment]
@fennectech can you test it without layeredfs?

**Comment by vigigure** [comment]
jksm on switch can backup and restor miencraft saves for me https://github.com/J-D-K/JKSV

**Comment by fennectech** [comment]
It also can for me. Though its far less optimised and i perfer this one.

**Comment by vigigure** [comment]
why is it not optimised? it doesn't slow for me

**Comment by fennectech** [comment]
Its not that its slow  The menu is rather ugly and interface feels clunky. _

**Comment by vigigure** [comment]
it is just a grid of icns with a box to confirm stuff and use the same colors as switch. i rather use something that actually works instead of delete save data over and over to make it work

**Comment by BernardoGiordano** [comment]
@vigigure we're debugging this to make it work fyi

**Comment by BernardoGiordano** [comment]
@vigigure @fennectech @877cms @Woody601 @TheProvider0 @PuppyTails @IntaroArt @CarJem @98otiss03 

Can you all test with this version? https://www.dropbox.com/s/wz9ca7pb27hc8l1/Checkpoint.nro?dl=0

Also, **if this dows work as intended**, please try to see if it works with other cfw that also enable modules like layeredfs and fs_mitm

**Comment by IntaroArt** [comment]
@BernardoGiordano 
Tested (same configuration as last time but with the "newer" test version. Was able to successfully restore twice without deleting data!
Tested with "Newest LayeredFS" via tomger's SD files: no issues, was able to restore the save files without any errors or crashes!

It seems like this version is working

**Comment by IntaroArt** [comment]
Update: no issues with the actual restore process and loading the game. The error now pops up when loading a world now. Error 2011-0301 on loading a custom world.

**Comment by fennectech** [comment]
Works for me.   Can you guys add a button on the keyboard input screen to accept the current text.  (Basically a button equivalent of pressing okay.   Like start or y or something like that.  So that we don’t have to go to “okay” to use the default filename

**Comment by fennectech** [comment]
@BernardoGiordano   Can you push this fix somewhere so i can compile a copy on my own?  (would like to add my keyboard change into it

**Comment by fennectech** [comment]
Also   after deleting a minecraft save they all vanish from the screen and the switch crashes

**Comment by fennectech** [comment]
![ac1cf90b-44ee-4588-a5e5-b38aa96744b5](https://user-images.githubusercontent.com/11953665/44970662-71e97000-af18-11e8-9640-568218d5890b.jpeg)
![88dbd8dd-b508-426a-91bd-9aaf1f31247f](https://user-images.githubusercontent.com/11953665/44970664-72820680-af18-11e8-8c4c-ec6b1d77ed0e.jpeg)
![24437c32-26db-4296-8819-f10a95ac4c39](https://user-images.githubusercontent.com/11953665/44970665-72820680-af18-11e8-8dff-fd5667bca7ba.jpeg)

**Comment by fennectech** [comment]
NEVERMIND   I GOOFED   Got confused by Checkpoint(1).nro Checkpoint(2).nro Checkpoint(27).nro etc  xD

**Comment by BernardoGiordano** [comment]
This is now considered fixed.
