### ISSUE TITLE
Fire Emblem Fates save incomplete restore

### ISSUE THREAD

**Issue by PsychoMan53** [FlagBrew/Checkpoint#118]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint:
* System version:
* Checkpoint version:
* Expected behaviour: All 5 save files would be present
* Encountered behavior: only the last 2 were restored
* Result code (if available):
* Steps to reproduce:
  * step 1 Backup save files to exdata
  * step 2 Load in edited save file
  * step 3 Overwrite with original Backup file
  
### Feature request details

* I would like this feature...:
* Because...:

**Comment by BernardoGiordano** [comment]
are you sure the missing ones are not in the standard save archive?

**Comment by PsychoMan53** [comment]
standard save archive? I don't follow. All I did was extract and then restore with what was on Checkpoint

**Comment by BernardoGiordano** [comment]
You backupp'd files to extdata. Backup in the normal option instead.

**Comment by BernardoGiordano** [comment]
anyupdate about this?
