### ISSUE TITLE
[Feature Request] Forwarder Functionality

### ISSUE THREAD

**Issue by ewormPL** [FlagBrew/Checkpoint#136]
Would it be possible for Checkpoint to read/backup saves from DS games played on a 3DS via [this](https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/) forwarder method? 

I know it's hardly a necessary thing, the saves are simple .sav files that can be accessed via any file manager, be it FBI, GodMode or whatever... But Checkpoint is very much more convenient and aesthetically pleasing. Would be very neat.

**Comment by fattard** [comment]
Hello, I just created a special version of the Checkpoint (based on the source code for version 3.6.0) that handles NDS ROMs save management.
It uses the default paths of the TWiLightMenu.

https://github.com/fattard/Checkpoint/releases/tag/v3.6.1-nds

It's a separated program that **exclusively** handles NDS ROMS save data.

To integrate with the original Checkpoint, it would needs a better media type management, and I will let @BernardoGiordano deals with that, if he's interested.
The additional code is already separated from the original functionality, so there's no conflict.

**Comment by GriffinG1** [comment]
Issue covered in a list that's part of #230, closing...
