### ISSUE TITLE
Paper Mario 3DS issues... still...

### ISSUE THREAD

**Issue by dragaron** [FlagBrew/Checkpoint#140]
I personally am still having issues with Paper Mario. I just backed up a save using Checkpoint 3.4.1, and then moved a few spaces (in the game) and then re-saved, quit the game, reloaded Checkpoint, restored said backed up save, and then had the typical "File is corrupted. Re-creating file." message followed by a cleared (deleted) save file when the game was loaded.

**Comment by BernardoGiordano** [comment]
This shouldn't be an issue anymore. Please test with 4.0.0 once it gets released and report back
