### ISSUE TITLE
Checkpoint 3.4.1 for Switch game titles issue

### ISSUE THREAD

**Issue by chinanoahli** [FlagBrew/Checkpoint#141]
### Error details

Checkpoint 3.4.1 for Switch show the game titles that I deleted and there was no Checkpoint back for those games. And there was no way to delete those titles!

![image](https://user-images.githubusercontent.com/10005128/44617498-4e7e4f80-a89e-11e8-8dde-991b0dcb797b.png)
![image](https://user-images.githubusercontent.com/10005128/44617523-d06e7880-a89e-11e8-9b93-43c70bdcfe7f.png)

**Comment by fennectech** [comment]
delete the titleIDs in your /switch/checkpoing/saves folder corrisponding to the games you dont want

**Comment by chinanoahli** [comment]
Thank you for you suggestion. After I posted this issue, I found that still save left inside the machine, I thought delete the game will automatic delete the save too. After I deleted the save in **Data Management > manage save date/screenshots and videos**, the game titles are gone now.
