### ISSUE TITLE
Feature Request: [3DS] Change Default Save Directory

### ISSUE THREAD

**Issue by ReignOfComputer** [FlagBrew/Checkpoint#148]
* [x] Feature request

### Feature request details

* Would be great to change the default save directory.
* Currently, saves are located at /3ds/Checkpoint/saves/<title>/<savefolder>. Custom paths could be allowed in configuration that allows users to change the default save location (even for specific titles only) to something like /Ultra Sun/<savefolder>, allowing users to reach save files faster.

**Comment by BernardoGiordano** [comment]
I don't quite see the benefit of this, closing for now
