### ISSUE TITLE
Feature Request: [3DS] One-click Backup/Restore

### ISSUE THREAD

**Issue by ReignOfComputer** [FlagBrew/Checkpoint#149]
* [x] Feature request

### Feature request details

* Would be nice to have a one-click backup or restore function.
* Current flow of the application is users have to select a game before pressing L/R to backup or restore, respectively. Would be nice to have the game highlighted (but not selected) and just pressing L to create a fast backup (removing the need to select, press L, filename screen), and/or fast restore (restoring latest possible save).

**Comment by BernardoGiordano** [comment]
#151 addresses a similar issue and is probably the best we can do while keeping the UI sane. Test it out, backup and restore can be done with a double A press

https://www.dropbox.com/s/txw0ovh5ovkaonp/Checkpoint.3dsx?dl=0
