### ISSUE TITLE
[Feature Request][Switch] - Press "A" while "New..." or a Backup is Highlighted Should Create or Load a Backup

### ISSUE THREAD

**Issue by IBNobody** [FlagBrew/Checkpoint#150]
## Issue template

* [x] Feature request
  
### Feature request details

* I would like this feature...: Press "A" while "New..." or a Backup is Highlighted Should Create or Load a Backup
* Because...: I spent quite a bit of time save-scumming Dead Cells and found that the current GUI has some non-intuitive elements.  Selecting "New..." or a backup and then having to push L or R feels clunky.

Current behavior: 
- After selecting a game by pressing **A**, the UI highlights the save dialog. 
- Pressing **A** while "New..." is highlighted does nothing. 
- Pressing **A** while a backup is highlighted does nothing.

Desired behavior: 
- After selecting a game by pressing **A**, the UI highlights the save dialog. 
- Pressing **A** while "New..." is highlighted should create a new backup. 
- Pressing **A** while a backup is highlighted should load that backup.
- Existing L/R functionality can still be preserved.

This change would make it possible to select a game, and then spam A to make a save.

**Comment by IBNobody** [comment]
@BernardoGiordano I took care of this issue by splitting the handling of the A button from the handling of the touchscreen. I can submit a pull request. Before I do, should I update the micro version, or should I leave that up to you? (And should I also update the 3DS micro version, even if I did not touch that code?)

**Comment by BernardoGiordano** [comment]
I'll take care of versioning

**Comment by IBNobody** [comment]
Done. I ended up editing a little more than just the A button. I also reworked the Y button. The end result is that the GUI should be more clear to the end user. I tried the fix out on both my 3DS and my Switch. Let me know if I need to change anything.
