### ISSUE TITLE
make the Game all of Yo-kai Watch USA/EU/JP support in the Checkpoint

### ISSUE THREAD

**Issue by Orionsilver** [FlagBrew/Checkpoint#153]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: CFW Luma 9.1
* System version: 11.8
* Checkpoint version:  3.4.2
* Expected behaviour: Backup issue
* Encountered behavior: Backup issue 
* Result code (if available): none

### Feature request details

* make the Game all of Yo-kai Watch USA/EU/JP support in the Checkpoint and i backup the save and then i go to my sd card it is backup and it shows blank save file on it

**Comment by BernardoGiordano** [comment]
They all should already be supported. Which entrypoint are you using? Please fill in all the relevant info

**Comment by Orionsilver** [comment]
i use CFW Luma 9.1

**Comment by Orionsilver** [comment]
@BernardoGiordano i fix the problem 
it did not backup and i reinstalled and it work as a charm 
sorry PLZ forgive me
