### ISSUE TITLE
Extract Save Data from User Partition Dump from Nand (hekate)

### ISSUE THREAD

**Issue by MatheusArleson** [FlagBrew/Checkpoint#154]
* [X] Feature request

### Feature request details

* I would like this feature...: 
Extract Save Data from User Nand Partition

* Because...: 
**Ban Safe** : Dump/Restore User partition using ONLY hekate without running any Custom Firmware will GREATLY reduce the risk of bans.

* Process...:

1. Run hekate.
2. Dump User Partition to SD.
3. Run CheckPoint. (?reading the dumped User partition file?)
4. Backup/Restore save files.
5. Run hekate.
6. Restore User Partition.

* Thoughts...
If the User partition is enough, we could run the checkpoint against the dumped USER.bin file.
If not, we could use hacDiskMount to mount it as a Windows Device.

* On the Code...
You initialize all the title available on   :
```
//title.cpp, loadTitles(), on line 227
Result res = fsOpenSaveDataIterator(&iterator, FsSaveDataSpaceId_NandUser);
```

Once you have all titles, the UI just trigger the backup method on IO.
Seems that you only need the title selected, and the filesystem...
```
//io.cpp, backup(), on lines 165 - 169
Title title;
getTitle(title, uid, index);

FsFileSystem fileSystem;
res = FileSystem::mount(&fileSystem, title.id(), title.userId());
```

Till line 235, You do some checking for the output path, and then on line 236
```
//this is where you copy the file from the memory to the sd card?
res = io::createDirectory(dstPath);
res = io::copyDirectory("save:/", dstPath + "/");
```

Maybe we are already half way there? 
Any thoughts?

**Comment by ThatNerdyPikachu** [comment]
h e t a k e

**Comment by MatheusArleson** [comment]
Edited the typos.
Hekate and hetake are very close...

**Comment by mariogamer2** [comment]
It would be really cool. But you'd need to provide biskeys too. After that, raw save aren't in the same format, so at the point where you extracted the save, I don't know how possible it would be to inject it afterward.

**Comment by yellows8** [comment]
This app only runs under Horizon, what you're describing is outside of Horizon.

**Comment by fennectech** [comment]
I beleve they are referring to a nand dump on the SD card.

**Comment by MatheusArleson** [comment]
What we got so far:
Hekate - All nand partitions, including USER, where save files are.

Biskeydump - All console keys.

HacDiskMount - Check the partitions content, mount them as windows devices. 
If you provide the keys, operations in the mounted device have transparent cryptography.

Checkpoint - Extract save files.

The idea is to create a new version that could interact with the raw full nand binary, OR/AND User partition binary, OR/AND the mounted windows device.

To restore, user will just restore from the nand partition using hekate.

**Comment by BernardoGiordano** [comment]
Yeah but Checkpoint is not designed to work outside the OS.

**Comment by MatheusArleson** [comment]
Indeed. 
But can you clarify the dependencies between the application and the OS?
Is it something that would be impossible or just hard to do?

BTW, i want to contribute, not just wait.

**Comment by fennectech** [comment]
you will have to 'port' checkpoint to the PC for this.   Checkpoint runs on the switch  not the PC
