### ISSUE TITLE
Create A Copy of Save File Before Backup or Restore

### ISSUE THREAD

**Issue by crunchycheese** [FlagBrew/Checkpoint#156]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [ ] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [x] Feature request

### Feature request details

Is it possible for Checkpoint to create a copy of a save file before a backup overwrites an existing backup or is restored? A main.bak could be created in the root path/folder before the backup/restore function is performed to prevent accidental loss of a save.

**Comment by BernardoGiordano** [comment]
The whole issue can just be avoided by performing a pre-backup of your backup.
