### ISSUE TITLE
Shantae and the Pirates Curse - Corrupted Save

### ISSUE THREAD

**Issue by peteyWheatstraw** [FlagBrew/Checkpoint#157]
Heya,

While trying to transfer save files of Shantae and the Pirates Curse, from an o3dsxl to a n3dsxl, i keep getting a 'corrupted save file detected' on the n3dsxl.

Both systems are running the latest luma and checkpoint.  

I've tried multiple different Shantae and the pirates curse cias ( checked their md5 sums) and none of them worked.  

I also tried using someone elses saved files, and still same result ( corrupted save file )

Does checkpoint work with Shantae  and the Pirates Curse? 

note: saves made from the installed shantae can be restored correctly. it appears the error only happens when trying to restore a game made on another system.
  
(all other games worked flawlessly btw, so a huge thank you)

**Comment by BernardoGiordano** [comment]
Please fill out the issue with details

**Comment by BernardoGiordano** [comment]
This got old without useful answers, closing.
