### ISSUE TITLE
Backup names are not using correct timestamp

### ISSUE THREAD

**Issue by garoxas** [FlagBrew/Checkpoint#158]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: SX OS 1.9
* System version: 4.1.0
* Checkpoint version: 3.4.2
* Expected behaviour: Placeholder for backup names using correct timestamp
* Encountered behavior: The auto-generated backup names always using **19691231-235959 username**
* Steps to reproduce:
  * open Checkpoint, select any games, tap L (backup)
  * the backup name dialog displays **19691231-235959 username** as placeholder name instead of **current date-current time username**
  
Thanks

**Comment by yellows8** [comment]
Was this system ever online / ever did a network time-sync?

**Comment by garoxas** [comment]
Nope. Never go online or even setup wifi connection since I bought it

**Comment by garoxas** [comment]
can it be "fixed" or is it the limitation on the whatever library used by checkpoint?
thanks

**Comment by garoxas** [comment]
awesome. thank you

**Comment by tmc9031** [comment]
@james-d-elliott thanks your comment, hope Checkpoint can update as soon as possible

**Comment by drdrjojo** [comment]
libnx v1.5.0 is out (switchbrew/libnx@480174753a7a05b2b6c41b27c0f57ac58ab62816) and include the time service fixes.
I have already tested it and the backup names are correct.
Hope we get an official release with libnx v1.5.0!

**Comment by garoxas** [comment]
tested the 3.5.0 build and it works great. thanks
