### ISSUE TITLE
Files not detecting on checkpoint. Help!

### ISSUE THREAD

**Issue by evanliang82** [FlagBrew/Checkpoint#160]
* [] Issue with Checkpoint for 3DS
* [x ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* System version: 6.0.0 using SX OS
* Checkpoint version: latest 10/6/18

So I just tried Checkpoint today and saved my Zelda BOTW game and it saved successfully onto my SD card. I copied that file onto my (MAC) computer and tried using the Zelda gamesaver editor and changed the files on my SD Card. I was not able to get that to work, so I deleted the modified file on my SD card and replaced it with my copied original save data from my mac. When I went back into checkpoint, my files for backup are not detected and do not show up. When I look at the SD card on my computer, it says its there, but when I look at the files on my switch, they don't show up...

Please help me, I was just trying to back up my BOTW game... I have the saved file, but I just can get it to detect on checkpoint and transfer the data again.

Thanks

**Comment by BernardoGiordano** [comment]
Please provide pictures of your SD card structure.

**Comment by evanliang82** [comment]
<img width="633" alt="screen shot 2018-10-14 at 10 26 40 am" src="https://user-images.githubusercontent.com/43920826/46919939-c6621f80-cf9b-11e8-903a-1c5c2668d5ec.png">
<img width="634" alt="screen shot 2018-10-14 at 10 26 47 am" src="https://user-images.githubusercontent.com/43920826/46919940-c8c47980-cf9b-11e8-9d81-c0f5bcae67ce.png">
<img width="636" alt="screen shot 2018-10-14 at 10 26 55 am" src="https://user-images.githubusercontent.com/43920826/46919941-ca8e3d00-cf9b-11e8-9bfe-8cd93adf6e41.png">
<img width="638" alt="screen shot 2018-10-14 at 10 27 07 am" src="https://user-images.githubusercontent.com/43920826/46919942-d0841e00-cf9b-11e8-9bb1-e55f837adbc1.png">
<img width="633" alt="screen shot 2018-10-14 at 10 27 15 am" src="https://user-images.githubusercontent.com/43920826/46919944-d37f0e80-cf9b-11e8-9a85-e1f8e0cd234e.png">
<img width="635" alt="screen shot 2018-10-14 at 10 27 22 am" src="https://user-images.githubusercontent.com/43920826/46919945-d5e16880-cf9b-11e8-98df-e5349f582e86.png">
