### ISSUE TITLE
An error has occured for Switch 6.0 with SX OS 2.0

### ISSUE THREAD

**Issue by sanglongbest** [FlagBrew/Checkpoint#163]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [] Issue with Checkpoint for 3DS
* [x ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Enter the app
* System version: 6.0.1 and SX 2.0.1
* Checkpoint version: 3.4.0 and 3.4.2
* Expected behaviour: Enter the app
* Encountered behavior: An error has occured and restart the switch.
* Result code (if available):
* Steps to reproduce:
  * step 1
  * step 2
  * ...
  
### Feature request details

Could I ask whether it is supported for swith 6.0 with and SX OS 2.0, please?

**Comment by BernardoGiordano** [comment]
Please reach me out in FlagBrew's discord server.
