### ISSUE TITLE
Issues with firmware 1.0.0

### ISSUE THREAD

**Issue by fire3element** [FlagBrew/Checkpoint#164]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Atmosphere 0.7.1
* System version: 1.0.0
* Checkpoint version: 3.4.2
* Expected behaviour: Backup BOTW (ver. 1.0) save
* Encountered behavior: Crashes directly after clicking "Yes" to backup. Crash happens before filename entry field appears.
* Result code (if available): None. Black screen. No error code, no console response.
* Steps to reproduce:
  * Boot Atmo 0.7.1
  * Launch Homebrew Launcher
  * Run Checkpoint
  * Select game (Breath of the Wild)
  * Click L to start backup
  * Click on "Yes (A)" 
  * ~Crash~  No filename input field. Black screen, system unresponsive.

  
### Extra details

Now before, Checkpoint would crash EVERY time, the first time.
However, I tried doing a multi-title backup with BOTW included. That backup worked fine. (verified multiple times doing the multi-title method)
Backup made with multi-select was restorable without issue.

Since then, if I try to backup BOTW immediately after a fresh boot into Atmosphere -> Checkpoint, I can get to the filename input screen.
If you back out (do not proceed with backup), then attempt to start a backup again, the system crashes immediately after clicking "Yes (A)".

I did notice that sometimes you can see the filename input screen for a brief second before it goes black.

To be clear, this issue is only with BOTW. Other titles backup fine/have never shown problems.

**Comment by BernardoGiordano** [comment]
Can you attempt with this build? https://www.dropbox.com/s/l2cwkl81aqqkjpm/Checkpoint.7z?dl=0

**Comment by fire3element** [comment]
Good news. 
Checkpoint 3.5.0 works on SDFilesSwitch v10 after updating Switch FW to 5.1.0
BOTW backs up and restores fine.

Unfortunately, I was not able to test it on FW 1.0.0
Could not get either 3.4.1 or 3.5.0 to run again. Both would load to a blank screen. No files listed.

Likely a permissions issue on 1.0.0
Also tried booting with fullsvcperm=1 and debugmode=1 in the hekate_ipl boot config, 
but that did not resolve the loading issue.

**Comment by BernardoGiordano** [comment]
Test with 3.6.0

**Comment by BernardoGiordano** [comment]
Closing this at this point.
