### ISSUE TITLE
Newer games don't display their game name, just the titleid

### ISSUE THREAD

**Issue by MattKimura** [FlagBrew/Checkpoint#165]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [ ] Issue with Checkpoint for 3DS
* [x ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint:sxos 2.1
* System version:6.0.1
* SD Card Filesystem:FAT32
* Checkpoint version: 3.4.2
* Expected behaviour: Game titles on folders in switch/checkpoint/
* Encountered behavior: No game titles on folders in switch/checkpoint/. Just titleid's are displayed for newer titles such as Dark Souls for example.
* Result code (if available):
* Steps to reproduce:
  * step 1
  * step 2
  * ...
  
### Feature request details

* I would like this feature...:
* Because...:

**Comment by fennectech** [comment]
This is because some of your games have charicters that arent 0-9 or a-z.  These charicters cannot be put in filenames on fat32    We dont support it currently on ether.

**Comment by garoxas** [comment]
is it possible just to replace those characters with normal characters?
I see there's similar implementation here https://github.com/FlagBrew/Checkpoint/blob/master/switch/source/util.cpp#L95, just need to add more characters in the list (®, ™)

**Comment by fennectech** [comment]
We could just have blank charicters for charicters that dont have simple alternatives

**Comment by garoxas** [comment]
that works too

**Comment by fennectech** [comment]
@BernardoGiordano  If i were to add the charicters that dont have alternatives as spaces in a PR would you merge it?   It would likely break compatibility with existing unsupported directory names as they would have to be renamed manually

**Comment by BernardoGiordano** [comment]
I would rather prefer converting symbols to spaces and special letters to normal ones, if you really want to take care of this

**Comment by fennectech** [comment]
I’m referring specifically to charicters like TM and (R) that dont have easy alternatives in the FAT filesystem

**Comment by fennectech** [comment]
Is the following code used?  I cannot get pokemon quests accented E to be recognised and turned into an e. 

`// https://stackoverflow.com/questions/14094621/change-all-accented-letters-to-normal-letters-in-c
std::string StringUtils::removeAccents(std::string str)
{
    std::u16string src = UTF8toUTF16(str.c_str());
    const std::u16string illegal = UTF8toUTF16("ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöō÷øùúûüýþÿ&®™");
    const std::u16string fixed   = UTF8toUTF16("AAAAAAECEEEEIIIIDNOOOOOx0UUUUYPsaaaaaaeceeeeiiiiOnoooooo/0uuuuypy____");
    `

**Comment by gajewsk2** [comment]
I'm only playing japanese games, so this is definitely an issue for me as well. I was wondering why my games weren't showing up.

**Comment by BernardoGiordano** [comment]
Can't really do much about this at this point in time
