### ISSUE TITLE
BUG: can NOT show game icon when switch user do NOT exist save data and Checkpoint exist backuped save data

### ISSUE THREAD

**Issue by tmc9031** [FlagBrew/Checkpoint#166]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

**NOTICE**: The issue tracker is meant for bug reports and not for troubleshooting. Please reach us out on our [Discord server](https://discord.gg/bGKEyfY) to receive help. By sending this issue report to us, you're aware that your submission may be closed without notice if invalid.

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: sxos 2.0.1
* System version: 6.0.1
* SD Card Filesystem: exfat
* Checkpoint version: 3.4.2
* Expected behaviour: can show game icon when switch user do NOT exist save data and Checkpoint exist backuped save data !!! then i can restore backuped save data to switch user
* Encountered behavior: 
* Result code (if available):
* Steps to reproduce:

**Comment by BernardoGiordano** [comment]
This is the intended behaviour. You need to create a save beforehand by entering the game, then you can use checkpoint.

**Comment by tmc9031** [comment]
@BernardoGiordano why is the intended behaviour ??? or can NOT implement ???
for example setp
1. create a save beforehand by entering the game
2. use checkpoint. backup save
3. delete save by switch save manager (maybe just a mistake)
4. want to use checkpoint. restore backuped save (but have NOT game icon...)

if must game save must exist, please use "overwrite" NOT "restore" , thanks
