### ISSUE TITLE
Feature Request: [3DS] Option for those who need to backup with damaged touchscreens

### ISSUE THREAD

**Issue by PhobosIndustries** [FlagBrew/Checkpoint#167]
* [ ] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [x] Feature request
  
### Feature request details

* When creating a new save slot during the backup process, I would like the option to accept the default name by 'A' button or 'Start' button, rather than just pressing 'OK' on the touchscreen.

* I am trying to extract save games from a N3DS with a broken touchscreen, and I can't progress past the on screen keyboard. The touchscreen of this N3DS cannot just be replaced as the damage is to the both connector on the mainboard and the touchscreen cable. Your application is so close to solving this problem I (and perhaps others?) have.

**Comment by BernardoGiordano** [comment]
While it's not possible to exit the on screen keyboard without touching the screen, you can select one title using Y and then backup using the button L. That will let you backup a single title without prompting you for a backup name.
