### ISSUE TITLE
Feature Request (swap titleid and title name in directory). 

### ISSUE THREAD

**Issue by fennectech** [FlagBrew/Checkpoint#168]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

**NOTICE**: The issue tracker is meant for bug reports and not for troubleshooting. Please reach us out on our [Discord server](https://discord.gg/bGKEyfY) to receive help. By sending this issue report to us, you're aware that your submission may be closed without notice if invalid.

* [ ] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [x] Feature request

### Feature request details

* I would like this feature...:Swap the titleid and title name 
* Because...:It would make searching for your title by directory name so much easier.  It would also make sorting possible.   

If you hit “m” in your windows explorer it will take you to the Ms in your folder.

**Comment by BernardoGiordano** [comment]
Unfeasible nowadays, and actually looks messier than you think.
