### ISSUE TITLE
Titles with black backgrounds no longer display properly (e.g. undertale, skyrim, octopath traveler)

### ISSUE THREAD

**Issue by theedward1** [FlagBrew/Checkpoint#170]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: sdfiles 10.1
* System version: 6.0.1
* SD Card Filesystem: exfat
* Checkpoint version: 3.5.0
* Expected behaviour: a proper icon with the black background showing correctly
* Encountered behavior: only the overlay graphic shows up, the black background is not there, and shows a gray instead 
* Steps to reproduce:
  * check any title with a black background like undertale, skyrim, or octopath traveler

**Comment by BernardoGiordano** [comment]
Can you submit a screenshot?

**Comment by theedward1** [comment]
![2018103021154000-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/22187024/47764150-f09d2800-dc91-11e8-8085-767eb6047aec.jpg)
![2018103021154200-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/22187024/47764151-f09d2800-dc91-11e8-80a3-88637e0a11a9.jpg)
![2018103021155200-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/22187024/47764152-f135be80-dc91-11e8-8f29-8e9d9cddba5a.jpg)

**Comment by theedward1** [comment]
any ideas what could be going wrong?

**Comment by fennectech** [comment]
PNG alpha layer?  I see this as well.

**Comment by fennectech** [comment]
Here is some evidence of backgrounds partaly displaying but not completely    lending credance that alpha layer may have been used on these images 

![](ftp://fennectech@10.0.0.24:5000/Nintendo/Album/2018/11/12/2018111217091000-B934DC54584BF9D4445EFCBF14A74585.jpg)

![](ftp://fennectech@10.0.0.24:5000/Nintendo/Album/2018/11/12/2018111217085100-B934DC54584BF9D4445EFCBF14A74585.jpg)

**Comment by yellows8** [comment]
"PNG" It's JPEG...

**Comment by theedward1** [comment]
Good to see others have the issue and my switch isn't just screwed up, hope it's an easy fix.
