### ISSUE TITLE
[Feature Request] 3ds Card1 raw save file support

### ISSUE THREAD

**Issue by CordY5** [FlagBrew/Checkpoint#172]
I was wondering about a potential feature, would it be possible to add support for card1 raw save files? (encrypted bin files of a size of ~512kb/1024kb)

**Comment by Mike007899** [comment]
If you are asking about support for flashcards, you are outta luck because its a form of piracy and Bernardo and team dont wanna encourage it.

**Comment by cheatfreak47** [comment]
I think this is talking about exact 1:1 encrypted rips of saved data from physical cartridges, I guess this is the sort of thing that you'd get with like, a powersaves dongle or one of the cheap chinese clones that do the same thing.

I don't see much point in supporting this but I mean, I guess it's a feature that wouldn't hurt. ¯\_(ツ)_/¯

**Comment by CordY5** [comment]
I am not talking about flashcards stuff, I don't even have one.

Exactly what @cheatfreak47 said.
I'd like to look into the encryption, but I don't have a powersave or anything else. (nothing that is free can do it atm)

**Comment by BernardoGiordano** [comment]
Out of scope
