### ISSUE TITLE
Pokémon Rumble World slow save dump

### ISSUE THREAD

**Issue by wrathsoffire76** [FlagBrew/Checkpoint#174]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

**NOTICE**: The issue tracker is meant for bug reports and not for troubleshooting. Please reach us out on our [Discord server](https://discord.gg/bGKEyfY) to receive help. By sending this issue report to us, you're aware that your submission may be closed without notice if invalid.

* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: CFW
* System version: 11.8.0-41E
* Checkpoint version: 3.5.0
* Expected behaviour: Save dumps
* Encountered behavior: Save dumps but takes quite a while to do, especially when the saves are a few kb large

**Comment by BernardoGiordano** [comment]
It's a trade off, speeding up transfer of small files would slow down transfer of big files
