### ISSUE TITLE
Issue with SX OS

### ISSUE THREAD

**Issue by lisai9093** [FlagBrew/Checkpoint#175]
Not working on SX OS 2.0.1 with switch version 6.1.0 to cause 2345-0031 error

**Comment by fennectech** [comment]
SXOS is unsupported as it is closed source  we cannot correct issues with their software.  They also dont steal the updates fast enough to be anywhere near up to date.

**Comment by BernardoGiordano** [comment]
@lisai9093 please fill out the full issue form and submit your issue again.
