### ISSUE TITLE
Menu messed up

### ISSUE THREAD

**Issue by fennectech** [FlagBrew/Checkpoint#184]
Instaid of a discription and how to reproduce i will link a video on how i managed to reproduce it.

https://cdn.discordapp.com/attachments/377425394866847744/533075804062613515/2019011018115700-DA63280140B1530CD17755515D814CFE.mp4

**Comment by fennectech** [comment]
any news on this?

**Comment by piepie62** [comment]
This is just a mismatch of your expectations with the implementation. Instead of paging upward and downward, it's paging from left to right.

**Comment by fennectech** [comment]
so  this is intensional?

**Comment by piepie62** [comment]
Even if it isn't, it is a perfectly valid paging system. PKSM uses a left-to-right system for the most part, as well

**Comment by fennectech** [comment]
well   the reason I ask is that it used to page vertically
