### ISSUE TITLE
2002-0001 when trying to restore edited save for Smash Ultimate xci

### ISSUE THREAD

**Issue by tommy1292** [FlagBrew/Checkpoint#185]
Okay, I already had the edited save working with no errors. I deleted it because I wanted another save file that didn't have any completion (new game) in Super Smash Ultimate xci. I am using SX OS 2.5.2 emuNAND 6.2.0 with exFat support. I am working on a mac
When I finally had both the new save game and the edited save folders in checkpoint and restored the edited save I consistently get a 2002-0001 when I am loading Smash Ultimate. I have tried many combinations: deleting both files and starting from scratch, deleting the new save game file, deleting the saves through data management. Deleted the .nsp v1.2 update for Smash Ultimate. Deleted the Checkpoint.nro and folder it belonged in. Installed the xci using sx os installer. re-installing the v.1.2 .nsp update. I cannot get the edited file to load anymore. The only thing I did not try was to delete the smash ultimate.xci file completely from the sd card and copy it back to the root of the sd. I don't know if that will do it but unsure why it is not loading the edited save file. Any info will help. Thank you!

**Comment by BernardoGiordano** [comment]
I won't care about issues with SX OS
