### ISSUE TITLE
[Feature Request] Cloud Support

### ISSUE THREAD

**Issue by amaredeus** [FlagBrew/Checkpoint#190]
**Is your feature request related to a problem? Please describe.**
If my switch SD card is erased, or switch is bricked, or even switch gets lost so will my saves.

**Describe the solution you'd like**
Support for at least one popular cloud service like Google Drive, Dropbox, or Mega. Game saves can be automatically backed up to a default folder in the cloud.

**Describe alternatives you've considered**
Manually copying the game save to another device...

**Additional context**
UI would be nice but I think most would be happy if game saves were saved automatically in default cloud paths.

**Comment by johnlescault** [comment]
Came here to request the same except for the 3DS version. I have multiple 3DS I play and this would be nice to sync them even if it's a little slow to upload.

**Comment by ulucs** [comment]
Came here to propose this just to see it was already proposed. I'd love to contribute this feature to the project if the dev team doesn't object to it.

**Comment by fennectech** [comment]
Keeping a local database of what’s been synced and when would be smart to keep from having to reupload all the data every time.

**Comment by piepie62** [comment]
Does... anyone think about how difficult this would be? It's not as simple as just sending the data up to the server, we'd have to implement and/or port an entire login API.

**Comment by BernardoGiordano** [comment]
Considering authentication/authorization issues, it's not trivial. And we prefer providing safe tools rather than unsafe hacks that 'work'

**Comment by ulucs** [comment]
Of course I don't think it will be trivial. Honestly, I think the first step sould be ftp sync with address and credentials read from a configuration file rather than full-fledged cloud sync.

**Comment by fennectech** [comment]
Oh yes.  This would be a royal pain in the ass.  But you dont require implementing login.  You can use oauth which mean you punch in a code on a browser and log in there to authorize it.

**Comment by FM1337** [comment]
the main issues are

1. Ensuring the security of the saves
2. Implementing a login system for users
3. Ensuring the security of said login system
4. Legality issues, this would be competing with Nintendo's cloud save feature for the Nintendo Switch which could open FlagBrew up to a C&D

**Comment by liamwarfield** [comment]
how about make it general and add ftp support? This way it's not tied to specific cloud service provider, and users can host there own server.

**Comment by BernardoGiordano** [comment]
Closing since FTP support got provided in the latest commits. Work for the 3DS version will be done in the future if feasible enough

**Comment by SegFault42** [comment]
@amaredeus you can try my tool : https://gbatemp.net/threads/backupnx.543111/
