### ISSUE TITLE
multiple error 2345-0031 switch 

### ISSUE THREAD

**Issue by alextazy0** [FlagBrew/Checkpoint#195]
Hello! I've got error 2345-0031 while trying to launch checkpoint with the sx ox under my two switches, one with fw 7.0.1 and one with fw 8.0.0sx os 2.7.1.
I've tried on both with sd card both formated with fat32 or exfat, with both sx os 2.6.1 or 2.7.1 … 
Now I've tried all the possible combination above, I don't really know what to try

Thank you in advance for your answer!

**Comment by Gudf** [comment]
Try using Atmosphere instead of SX OS.

**Comment by BernardoGiordano** [comment]
Closing as the form hasn't been filled properly. Also, we don't troubleshoot SX OS issues.

**Comment by alextazy0** [comment]
Same error with different screen!
![IMG_0366 resized-q70](https://user-images.githubusercontent.com/50498319/57554764-aa2c3280-7372-11e9-99cf-73d54e89ed2d.jpg)

**Comment by BernardoGiordano** [comment]
Fill out the issue form properly. Locking
