### ISSUE TITLE
Can not start Checkpoint, system crashed at error: 2345 - 0031

### ISSUE THREAD

**Issue by konan767** [FlagBrew/Checkpoint#197]
**Describe the bug**
Everytime I started Checkpoint, Its comes system crashed at error: 2345 - 0031

**Switch:**
- Entrypoint: SXOS
- System version: 8.0.1  (Emunand)
- Checkpoint version: 3.6.0
- SD Card Filesystem: ExFAT
- Result code (if available): 2345 - 0031

**Comment by fennectech** [comment]
Exfat is verry unstable on the switch and sxos is known to have issues. Please use fat32 and try with atmosphere or kosmos.

**Comment by BernardoGiordano** [comment]
#192 duplicate
