### ISSUE TITLE
I have a bootleg heartgold cart

### ISSUE THREAD

**Issue by 0rangesjustice** [FlagBrew/Checkpoint#198]
I backed up my data on pokemon heartgold using checkpoint on the 3ds. However, i cant open the save on pkhex or pokegen. Somebody told me that i have a bootleg heartgold cart which is why the save file isnt in the right place. They suggested that i send Benardo (Checkpoint Dev) my cart information from JEDECheck, but i dont know how to send it to him. Ill post it here instead.
![20190513_215547](https://user-images.githubusercontent.com/50605883/57668591-d693b900-75d5-11e9-9ea3-229b75af4f56.jpg)

**Comment by BernardoGiordano** [comment]
Not much can be done
