### ISSUE TITLE
Cannot restore Saves after Nand restore

### ISSUE THREAD

**Issue by cleggorz** [FlagBrew/Checkpoint#199]
I backed up all my saves and updated to 8.0.1 ofw to play fortnite with a friend. After getting bored very quickly I restored my 7.0.1 Clean Nand backup (backup contained no user data or saves) However I now cannot restore my saves as checkpoint doesnt see the saves on my sdcard (I have tried previous backups too and nothing)

 Im not even sure if its a user profile issue as I created two user profiles and backed up a fresh save from one and the other profile could restore it. No matter what I try the checkpoint cannot see my old backups before I updated and restored my nand.

**Comment by BernardoGiordano** [comment]
You need to initialize your saves first by launching the games. This is the intended behaviour

**Comment by ph03nxd0wn** [comment]
I launched the game to initialize my saves as you wrote. Checkpoint still does not see my save. :/ Any other tip?
