### ISSUE TITLE
i got my wii u save and converted it to switch,but when I try to load that save, it starts from the start of the game(BotW)

### ISSUE THREAD

**Issue by sciscor** [FlagBrew/Checkpoint#201]

**Comment by sciscor** [comment]
when i try to restore my save,checkpoint does it,but botw doesnt use the save,instead it starts from the beginning

1.restore
2.restart
3.go to botw
4.doesnt load save

switch:
8.0.1
sd:
Fat32
no result code

**Comment by piepie62** [comment]
It seems quite likely to me that you didn't convert the save correctly

**Comment by sciscor** [comment]
i've tried multiple converters but nothing works

**Comment by sciscor** [comment]
i have a question.what should be the name of the actual file(00050000-101C9400 is what i call it)

**Comment by sciscor** [comment]
but i did convert it successfully this time but it still not working

**Comment by BernardoGiordano** [comment]
You didnt put the converted save file in the proper location

**Comment by sciscor** [comment]
where should i put it
