### ISSUE TITLE
Tittles Missing, and only one page.

### ISSUE THREAD

**Issue by hexthat** [FlagBrew/Checkpoint#202]
**Describe the bug**
Tittles Missing, no other pages

**To Reproduce**
1. Go to 'checkpoint'
2. Click on 'and hold B'

**Expected behavior**
When I hold B and it refreshes I can see the tittle I want but then after it finishes updating the list rearranges and the tittle disappears. Only 29 tittles show up, no way to switch pages.

**3DS:**
- Entrypoint: Rosalina
- System version: 11.10-43U
- Checkpoint version: 3.6.0
- Result code (if available):

**Additional context**
Same issue happens in sharkive, no pages and missing tittles, games that are missing have game saves

**Comment by hexthat** [comment]
I installed more tittles and its working correctly now. I'm going to close this now... perhaps it was something I did wrong?

**Comment by BernardoGiordano** [comment]
Will keep this open for a double check on my end
