### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by notkryptic** [FlagBrew/Checkpoint#203]
**Describe the bug**
Crashes on startup, i haven't had this problem before. It started after backup/restore on my copy of Pokemon Moon. ive tryed to re download it and changing the "checkpoint" file name but still to no pro vale.
 
**To Reproduce**
1.  literally just open checkpoint and close it, open it again and it crashes.  

**Expected behavior**
not this, its worked great for so long i dont know what broke it.

**Screenshots**
![image0](https://user-images.githubusercontent.com/51891982/59570540-9190f580-905f-11e9-90c1-7f20d68411b6.jpg)

**3DS:**
- Entrypoint: gm9
- System version: 11.10
- Checkpoint version: 3.6.9
- Result code (if available):

**Switch:**
- Entrypoint:
- System version:
- Checkpoint version:
- SD Card Filesystem:
- Result code (if available):

**Additional context**

**Comment by notkryptic** [comment]
i have a crash dump if needed.

**Comment by GriffinG1** [comment]
Upload it sooner rather than later

**Comment by notkryptic** [comment]
[crash_dump_00000022.zip](https://github.com/FlagBrew/Checkpoint/files/3294770/crash_dump_00000022.zip)

**Comment by BernardoGiordano** [comment]
Upload also the cache files you have in 3ds/Checkpoint. After that, remove them and it should load again. You exited forcefully before it could finish creating its files, that's the issue

**Comment by BernardoGiordano** [comment]
Any news about this issue?

**Comment by BernardoGiordano** [comment]
Closing
