### ISSUE TITLE
Crash on startup (Switch version)

### ISSUE THREAD

**Issue by SegFault42** [FlagBrew/Checkpoint#204]
**Describe the bug**
Crash on startup

**To Reproduce**
Launch Checkpoint with missing field in json file or with empty file

**Expected behavior**
No crash

**Switch:**
- Entrypoint: Atmosphere
- System version: 7.0.1
- Checkpoint version: 3.6.0
- SD Card Filesystem:fat32
- Result code (if available):

**Additional context**
I don't have time to fix this issue but the problem is located in parsing : https://github.com/FlagBrew/Checkpoint/blob/6bef27ce7629117a288518d1cfd9327d980abf06/switch/source/configuration.cpp#L196

Maybe just check if all field are present in the config file.

**Comment by piepie62** [comment]
Misconfiguration is not a code problem, it's a user problem

**Comment by BernardoGiordano** [comment]
I agree that it should gracefully replace the wrong json with the stock one if something's bad with it, rather than crashing

**Comment by BernardoGiordano** [comment]
Please test it again. 3DS version will be updated in the next future

**Comment by SegFault42** [comment]
Still crashing ...

And i have issue with the Makefile since this commit https://github.com/FlagBrew/Checkpoint/commit/cb773c8dfbd4e58fc161e067e6440c0c79a31d2a

When i build with : ``` `aarch64-none-elf-pkg-config SDL2_ttf SDL2_image --libs```
the .nro file is only 158K
```-rw-r--r-- 1 segfault42 segfault42 158K  6 juil. 10:13 Checkpoint.nro```

I have to replace ```LIBS:=``` with this ``` -lbz2 -lSDL2_ttf -lSDL2_image -lpng -ljpeg `sdl2-config --libs` `freetype-config --libs` -lnx -lwebp```

and add lwebp to compile with latest SDL2_image

Like this i have a correct .nro 
```-rw-r--r-- 1 segfault42 segfault42 8,6M  6 juil. 13:19 Checkpoint.nro```

I'm build on linux

**Comment by BernardoGiordano** [comment]
Please send your config.json file

**Comment by SegFault42** [comment]
I tried just with empty file

**Comment by WinterMute** [comment]
Make sure you have your host pkg-config installed.

**Comment by SegFault42** [comment]
@WinterMute Compilation fixed thx
