### ISSUE TITLE
Title Not Showing

### ISSUE THREAD

**Issue by PlantBeatdown** [FlagBrew/Checkpoint#205]
I have roughly 25 games on my SD cartridge, 9 of which have save data. When booting up Checkpoint, only 8 of the 9 titles with save data show up. The title with save data that I _want_ to appear, Monster Hunter Stories, isn't shown at all. When using JKSM, it shows up just fine, however I need it to show up on Checkpoint, since JKSM can't do anything with the save data on my version of  CFW. This hasn't happened to me before, at least to my knowledge. I'm running the CIA version of Checkpoint with Steelhax CFW on an 11.10 old 3ds XL.

**Comment by BernardoGiordano** [comment]
What happens if you hold `B` to refresh your title list?

**Comment by PlantBeatdown** [comment]
It shows the same titles as before, still no Monster Hunter Stories. I've also tried reinstalling Checkpoint, but still no change.  (Sorry for the late reply)

**Comment by SpiredMoth** [comment]
What if you press `X` to view the extdata list? I think I remember MHStories keeping its save data in extdata instead.

**Comment by PlantBeatdown** [comment]
That did the trick! Thank you!
