### ISSUE TITLE
Switch: Not restoring at all

### ISSUE THREAD

**Issue by koboltzz** [FlagBrew/Checkpoint#207]
**Describe the bug**
I created a new profile and wanted to restore my savegames with the latest checkpoint version. The tool starts, the games are displayed (previously started with the new account) but pressing the R button to restore does nothing. No error, no confirmation, as if the key is broken (it is not).

**To Reproduce**
Start tool, press R, nothing happens.

**Expected behavior**
A confirmation or something like that.

**Switch:**
- Entrypoint:  
- System version: 8.0
- Checkpoint version: 3.6
- SD Card Filesystem: fat32

**Comment by BernardoGiordano** [comment]
You're using the program in the wrong way.

You must press `A` to enable working with the selected title. **Then**, move to the save backup you want to restore, and **then** you can press the restore button.

You were using the tool in a way that was not specifying at all which one between the save backups you wanted to restore.

**Comment by koboltzz** [comment]
Well you could have implemented a notification after pressing R

**Comment by BernardoGiordano** [comment]
There is a notification after pressing R.

**Comment by koboltzz** [comment]
I don't get any notification

**Comment by BernardoGiordano** [comment]
You need to press the restore button while hovering on a save backup **and** while you entered the save backup scroll by pressing `A`. You notice you have the save backup scroll enabled by seeing the save backup list going blue, and the buttons getting darker.

**Comment by koboltzz** [comment]
Got it now. My backup process was as follows: Hold Y down and then press L.
So I thought the restore process was the same. Of course it didn't work. Then I pressed R like wild without pressing the equivalent to Y, namely A ;)

**Comment by BernardoGiordano** [comment]
You should have been more clear from the beginning. Mass restore is not supported, since Checkpoint can't automatically decide which one of your backups you want to restore. You must do one by one

**Comment by koboltzz** [comment]
Since I had only one backup and one profile, I wonder what the tool couldn't have decided automatically? I think I was clear ;)

**Comment by BernardoGiordano** [comment]
Feel free to submit a solution that would properly work for both cases via PR :)
