### ISSUE TITLE
Game crashes at startup after emunand reinstall

### ISSUE THREAD

**Issue by itsme2417** [FlagBrew/Checkpoint#209]
**Describe the bug**
Made a backup of a save on the game My friend pedro bullets blood bananas and Deleted my sx emunand afterwards i created a new one and after injecting the new save the game crashes when loading
**To Reproduce**
1. Create a backup of a savegame of the game my friend pedro bullets blood bananas
2. Reinstall sx os emunand
3. Install the game and launch it, exit after the cutscene ends and inject the save
4. Game stays on blackscreen and doesnt load after entering the game

**Expected behavior**
The game starts normally 

**Switch:**
- Entrypoint: SX OS 
- System version: 8.0.1
- Checkpoint version: 3.6.0
- SD Card Filesystem: Fat32
- Result code (if available):

**Additional context**

**Comment by piepie62** [comment]
We don't support SX OS
