### ISSUE TITLE
Favorites not displayed first

### ISSUE THREAD

**Issue by fennectech** [FlagBrew/Checkpoint#211]
**Is your feature request related to a problem? Please describe.**
No way to order how titles display in checkpoint.
**Describe the solution you'd like**
Display favorited filters first.

**Describe alternatives you've considered**
A file that defines the order?

**Additional context**
Not really

**Comment by GriffinG1** [comment]
In one sentence:

A sorting option for titles? So instead of the default alphabetical, you can do them by titleid.

**Comment by fennectech** [comment]
Mainly I’d like favorites to be displayed first in the list of titles.

**Comment by fennectech** [comment]
so turns out its intended to work that way however it does not   
![image](https://user-images.githubusercontent.com/11953665/60858707-1beaf600-a1d5-11e9-9f5e-27124e646841.png)
This is on 3.6.0

**Comment by BernardoGiordano** [comment]
This should have been fixed

**Comment by fennectech** [comment]
This issue was still in master as of 8 days ago.

**Comment by BernardoGiordano** [comment]
Been fixed in `last-fixes` branch
