### ISSUE TITLE
Checkpoint Crashing when loading games

### ISSUE THREAD

**Issue by ScrapDragon2** [FlagBrew/Checkpoint#212]
While trying to make use a Checkpoint, the app crashes with a data abort for some reason. Only started today, seems like a random thing to have happen. When trying to look into Checkpoint's folders on the computer, Windows gives an error, saying that the saves folder is not accessible due to corruption. Unable to delete the folder.

Just opening Checkpoint causes the crash. I had only been playing Pokemon Ultra Sun beforehand.

**3DS:**
- Entrypoint: Luma? Not sure on the Entrypoint.
- System version: 11.10.0-43U
- Checkpoint version: 3.6.0

**Comment by piepie62** [comment]
That's not Checkpoint that did that, that's your SD card getting corrupted

**Comment by ScrapDragon2** [comment]
I wonder how that happened... Assuming that the corruption is deep-seated, that means I'm going to lose all my data, no?

**Comment by ScrapDragon2** [comment]
I honestly hope that this corruption is fixable without needing to lose any data.

**Comment by piepie62** [comment]
I wish you best of luck retrieving your data, but closing this as it's not a Checkpoint issue
