### ISSUE TITLE
Bug Report - Crash after running Player Selection applet during three consecutive reboots of Checkpoint

### ISSUE THREAD

**Issue by BernardoGiordano** [FlagBrew/Checkpoint#220]
**Describe the bug**
Checkpoint crashes after 3 consecutive reboots if the user selection applet has been launched.

**To Reproduce**
1. Boot Checkpoint
    * 1.1. Open the account selection applet
    * 1.2. Choose an user
    * 1.3. Close Checkpoint
2. Boot Checkpoint
    * 2.1. Open the account selection applet
    * 2.2. Choose an user
    * 2.3. Close Checkpoint
3. Boot Checkpoint
    * 3.1. Open the account selection applet
    * **Crash**

**Switch:**
- Entrypoint: nx-hbmenu, from title
- System version: 8.1.0
- Checkpoint version: 4.0.0 (alpha) - commit 420513d
- SD Card Filesystem: FAT32

**Comment by XorTroll** [comment]
From my homebrew tests, on a test in which I didn't close sm session properly it crashes with result 2144-0001 after opening and closing it 3 times, like in your case. Apparently other times I got that result thrown by qlaunch are also related to not closing sessions properly.

Pretty sure it's all fo sessions
