### ISSUE TITLE
Copy checkpoint data from another sdcard - saves are not listed with new SD

### ISSUE THREAD

**Issue by YannickBiet** [FlagBrew/Checkpoint#222]
**Describe the bug**
I am changing from microSD 128GB to 256GB
so i copied pasted all files from old SD to new SD (including the checkpoint.NRO and switch/checkpoint FS)
I am using MAC OS X Mojave latest update.
I moved all files from old SD to a folder on desktop and with the new SD i Drag/Drop the files inside the new SD

Unfortunately, running SXOS and then Checkpoint from the new SD, i can't see any saves to restore to the new emunand image i created on the new SD card.

What should i do to restore my saves ?

**Expected behavior**
When launching checkpoitn from new SD, i was supposed to be able to see for each game a ligne under "new" prroving me the save on SD was read and able to restore.

**Switch:**
- System version: 8.0.1
- Checkpoint version: 3.6
- SD Card Filesystem: ExFat 256GB
- Result code (if available): no code at all

**Comment by YannickBiet** [comment]
Switching back to SXOS using the old SD 128GB -- checkpoint list the files....
what is wrong with copying the Filesystem structure to another SD (different brand, different size)

**Comment by YannickBiet** [comment]
Update : 
Trying to create a new save from a game doesn't list any error (message of success displayed) but the list of save is not refreshing.

So i removed the SD, delete the Switch folder, run SXOS / checkpoint again, created a new save to force the system to create the filesystem on SD instead of MacOS

Now the new save is created and listed in Checkpoint

I removed the SD, drop another folder in one of the switch/checkpoint/saves/gameid folders

When back to Checkpoint under sxos, on the game ID selected i can see the backup created with the same SD but my second folder is still ignored/not listed.

**Comment by YannickBiet** [comment]
using a terminal i can see that owner:group of the folders/files are the same...
i really don't understand how i can let checkpoint "see" my previous folders.

any advice ?

**Comment by GriffinG1** [comment]
SXOS is not guaranteed support, switch to a better CFW.

**Comment by BernardoGiordano** [comment]
Use FAT32 as filesystem, exfat is not guaranteed to work with homebrew.

**Comment by YannickBiet** [comment]
@BernardoGiordano --> 32GB is the maximum partition size limit using the FAT or FAT32 file system

with SD card of 128 or 256GB, what is the FS supported ?

**Comment by BernardoGiordano** [comment]
It is not. Just extend the block size and you can format higher capacity sd cards with FAT32 as well

**Comment by YannickBiet** [comment]
According to some French sites and tutorials, there's a big warning to don't use a MAC but a Windows computer to copy/paste back the files to the new SD card. I will have to find a Windows OS to test this and will update the thread. could it be interesting to know there's might be a problem @BernardoGiordano  ?

**Comment by BernardoGiordano** [comment]
I've never heard of such an issue, but it will be interesting to know about the outcome when you manager to format your sd card with a Windows PC. I think you're safe to format your card with a linux system as well. GParted is a nice tool to use in this cases.

**Comment by YannickBiet** [comment]
I'll keep you updated.
what is strange is that first SD (128GB) has been formatted with exFat, and checkpoint was working fine (i succesfully backuped and restored some saves from the SD), so i wonder what is the stopper to move the first SD save files to another SD of different capacity formatted the same way than the first one.

Anyway, I'll grab my windows PC tomorrow from work and will update the case

**Comment by YannickBiet** [comment]
Hello @BernardoGiordano 
as promised i used my professionnal laptop under windows10 this morning....
copy pasting the saves folder actually worked from **windows**, the saves are listed inside Checkpoint now and can be restored !!!

So there's an issue using Mac's Finder instead of a windows computer.

Do you want to reopen the issue or should i open a new one ?

**Comment by GriffinG1** [comment]
Do neither. It’s officially a macOS issue, not a pksm issue

**Comment by YannickBiet** [comment]
Dear @GriffinG1, 
there's might be a workaround that can be found or at least a warning added in the readme or known issue in Checkpoint.

It will maybe also help a lot of user that will not loose a full saturday trying to get the software work.

It was not an SxOS problem, nor the filesystem used.

Anyway i am awaiting any official feedback from Bernardo that is the owner of the Repo and will decide if he wants to trace this kind of issues (or not)

Thus said, I wish you to have a good day.

**Comment by fennectech** [comment]
I know macOS loves to fuck with the archive bit wich really eases with it. Can you run the fix archive bits tool in hekate.?

**Comment by YannickBiet** [comment]
Hi @fennectech thanks for sharing the info, i will try during the day and keep you updated.
As i a not a hekate user (sorry!) i will try the OS manipulation to see if this helps to target better the issue.

**Comment by fennectech** [comment]
I recomend installing hekate if even temporarily as it has a tool to fix this

**Comment by YannickBiet** [comment]
Congrats to @fennectech for th workaround, in deed after copying from the mac, i went on windows and check the archive flag, siply unchecked it and recursively apply --> files are appearing in checkpoint now.

**Comment by YannickBiet** [comment]
Seems from a mac we can fix that from command line :
https://gbatemp.net/threads/how-to-fix-sd-reading-problems-for-macos-users.510856/

**Comment by fennectech** [comment]
This fix will fuck up any games you have installed.    You’ll have to redownload shit.
