### ISSUE TITLE
BETA  Checkpoint hangs when backing up multiple games.

### ISSUE THREAD

**Issue by fennectech** [FlagBrew/Checkpoint#225]
**Describe the bug**
The application hangs   the console does not.   You can still exit with home button

**To Reproduce**
1. select multiple titles
2. press L to backup

**Expected behavior**
It should start backing up saves

**Switch:**
- Entrypoint: Atmosphere
- System version:8.1.0
- Checkpoint version:4.0,0  Commit 420513d
- SD Card Filesystem:fat32
- Result code (if available):NA

**Comment by BernardoGiordano** [comment]
Unable to reproduce

**Comment by fennectech** [comment]
i see.  Its the UI locking up while backing up with no indication its working.   It takes over a minute to backup a minecraft save with alot of purchessed content
