### ISSUE TITLE
Not extracting Layton 2 Spanish version save

### ISSUE THREAD

**Issue by patataofcourse** [FlagBrew/Checkpoint#226]
**Describe the bug**
Checkpoint will give the error "C8804478 - Couldn't retrieve the directory list for LAYTON2" when opened and the same error code with the message "Failed to create destination directory" when attempting to backup a save from the DS game _El profesor Layton y la caja de Pandora_ (Professor Layton and the Diabolical Box (US) / Pandora's Box (PAL), Spanish version with ID YLTS).

**To Reproduce**
1. Open the Checkpoint app, see first error message
2. Select the title and try to back it up, the name doesn't matter, see second error message

**Expected behavior** - obvious, would like the save to be properly extracted

**Screenshots**
Right after opening the app
![Opening the app](https://user-images.githubusercontent.com/29714419/64054651-5d21d580-cb88-11e9-8046-44d847709659.png)
When trying to backup the save
![Backup attempt result](https://user-images.githubusercontent.com/29714419/64054653-5d21d580-cb88-11e9-96ec-38edadfdc716.png)

**3DS information:**
- Entrypoint: Luma 3DS v10.0.1 / Homebrew Launcher
- System version: 11.11.0-43E
- Checkpoint version: v3.6.0
- Result code (if available): C8804478

**Additional context**
- Surprisingly, the problem solves itself after refreshing by holding B while the cartridge is still inserted, and the error won't happen even after restarting the app. It returns to its previous state after deleting the game's folder though.
- Curiously, this only applies to La caja de Pandora, despite all other Layton games before Mystery Journey having language-specific carts (excluding the crossover with Ace Attorney).

**Comment by GriffinG1** [comment]
Hi, can you update to v3.8.0 and let me know if this issue persists? Thanks.

**Comment by patataofcourse** [comment]
My 3DS broke a while ago, so I can't test anything, sadly

**Comment by GriffinG1** [comment]
Understood. I'm going to close this for now then.

**Comment by impeeza** [comment]
I can Confirm Checkpoint 3.8.0 can save without a problem: Professor Layton "Y la máscara de los prodigios" (Professor Layton and the Miracle Mask) & Professor Layton "y el legado de los ashalanti" (Professor Layton and the Azran Legacy) the two titles for 3ds on spanish.  Professor layton "2" is Professor Layton and the Diabolical Box/Pandora's Box which is for DS not 3ds so can use Checkpoint to manage his savegames.

**Comment by GriffinG1** [comment]
> which is for DS not 3ds so can use Checkpoint to manage his savegames.

can you be more clear about this @impeeza? Cause I'm reading it as can being a typo for "can't", which doesn't make sense to me as checkpoint can manage DS cartridges.

**Comment by impeeza** [comment]
OH, yeah, my bad,  I don't own the DS cartidges so can't test it but the 3ds version of game can be backed up just fine.

**Comment by GriffinG1** [comment]
Ok. This issue was specifically regarding a DS cartridge, with them pointing out in their original issue that it doesn't occur with any other Layton game.

**Comment by impeeza** [comment]
ok, sorry.
