### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Primeey** [FlagBrew/Checkpoint#227]
**Describe the bug**
Checkpoint simply doesn't launch from hbmenu. I get a black screen when I select it in hbmenu then my Switch goes back to hbmenu

**To Reproduce**
1. Launch hbmenu 3.0.1 via the album applet method
2. Select Checkpoint

**Expected behavior**
Checkpoint to launch

**Switch:**
- Entrypoint: ReiNX
- System version: 8.1.0
- Checkpoint version: 3.7.0
- SD Card Filesystem: FAT32
- Result code (if available):

**Additional context**

**Comment by piepie62** [comment]
Don't launch from applet mode

**Comment by Primeey** [comment]
The changelog for 3.7.0 LITERALLY SAYS

Fixed: Checkpoint doesn't run anymore if nx-hbmenu is launched over a system applet (like Album).

But ok...

**Comment by BernardoGiordano** [comment]
That's totally right. Launching hbmenu from a system applet is wrong
