### ISSUE TITLE
Checkpoint only works for the game in the cartridge

### ISSUE THREAD

**Issue by 3ds4Days** [FlagBrew/Checkpoint#228]
N3ds, Checkpoint 3.7.0

As the title says, Checkpoint seems to work but only for the game currently in the cartridge slot.   

From stock images, it is my interpretation that the top screen of the menu should show multiple images for the game save files currently handled by Checkpoint.  However, the only icon that shows up is for the game currently in the cartridge.        

I can make save backups for other cartridge games and save folders do appear under the "Saves" folder for Checkpoint.  But, on the menu, I can only see saves for the game currently in the cartridge slot.  

A DS rom's save file on the SD does not appear.  

I have tried looking under Extdata and have also tried pressing select and B multiple times.  Recently updated to version 3.7 from the previous version.  Previous version also had the problem.

**Comment by piepie62** [comment]
Checkpoint works for any INSTALLED games and the current cartridge. DS ROMs are not supported

**Comment by piepie62** [comment]
You cannot see titles that are not either installed or inserted

**Comment by 3ds4Days** [comment]
So, to be clear:
If I were to buy a game off the eShop and it got downloaded to my SD card, Checkpoint would work.
If I were to dump a cart onto the SD and removed the cart from the console, Checkpoint should work?
And, no roms are supported.

**Comment by piepie62** [comment]
Um, I can tell you for a fact that DS ROMs are unsupported. DS *cartridges* are. Checkpoint stores all of the backups of cartridges that you use on the SD card, but can only show titles that are present in the system.

**Comment by 3ds4Days** [comment]
Ah, I think I understand now.  Thank you for answering.
