### ISSUE TITLE
Checkpoints FTP-Server switches other FTP servers off.

### ISSUE THREAD

**Issue by Conan179** [FlagBrew/Checkpoint#231]
When I start the latest checkpoint version, the built-in FTP server of Athmoshere and SX-OS is switched off (can no longer connect). Also, if the FTP server is NOT active in the checkpoint.
(Switch 8.1.0, Atmosphere 0.9.3, SX OS V2.8)

**Comment by BernardoGiordano** [comment]
Atmosphere doesn't have a built-in server. Can you please tell me which server it is and to which port it connects?

**Comment by Conan179** [comment]
https://github.com/jakibaki/sys-ftpd
this with auto start
