### ISSUE TITLE
Crash on Startup SX OS 2.8beta

### ISSUE THREAD

**Issue by Ninjistix** [FlagBrew/Checkpoint#233]
**Describe the bug**
Any attempts to Launch Checkpoint returns you to the Launcher used to open Checkpoint, SX Homebrew Launcher, HBL, Mercury etc.

**To Reproduce**
1. Go to any HBL while on SX OS
2. Click on Checkpoint
3. See error

**Expected behavior**

**Screenshots**

**Switch:**
- Entrypoint: SX HBL, Mercury, HBL
- System version: 8.1.0
- Checkpoint version: 3.7.0
- SD Card Filesystem: FAT32
- Result code (if available):

**Additional context**
Error Log Shows
> [2019-09-09 18:59:23] [ INFO] Starting Checkpoint loading...
> [2019-09-09 18:59:23] [ERROR] Please run Checkpoint under Atmosphére title takeover. AppletType is 2.
> [2019-09-09 18:59:33] [ INFO] Starting Checkpoint loading...
> [2019-09-09 18:59:33] [ERROR] Please run Checkpoint under Atmosphére title takeover. AppletType is 2.

Checkpoint 3.6.0 still works on SX OS had to downgrade back until the issue gets resolved.

**Comment by GriffinG1** [comment]
That error log tells you exactly what to do. SXOS, and any other non-atmo cfw, is not supported by FlagBrew.

**Comment by Conan179** [comment]
@Ninjistix 
"Fixed: Checkpoint doesn't run anymore if nx-hbmenu is launched over a system applet (like Album)."

**Comment by Ninjistix** [comment]
@Conan179 thanks I missed that part, also i'm not sure @GriffinG1  knows what he's talking about

**Comment by GriffinG1** [comment]
I know exactly what I'm talking about. SXOS is a shit cfw, and Bernardo has stated before that no support will be added for it. In addition, those error logs you got specify to use Atmo's title takeover.

**Comment by Ninjistix** [comment]
putting @GriffinG1 aside, Checkpoint 3.7.0 only seems to be launched from HBL.nsp any other launcher seems to crash instantly

**Comment by FM1337** [comment]
SX OS isn't supported, you may try to run it, but there is no guarantee that will work.
