### ISSUE TITLE
Bug Report: It keeps crashing after the splash screen

### ISSUE THREAD

**Issue by Kontiki-** [FlagBrew/Checkpoint#235]
Checkpoint 3.7.0 installed through cia on 11.10. I tried deleting cache files and configuration. That didn't work so I tried a fresh install which also didn't work. For some reason it has no problem launching from .3dsx through hblauncher. 

Processor: ARM11 (core 0)
Exception type: data abort
Fault status: Translation - Page
Current Process: Checkpoi (000400000BCFFF00)

[Checkpoint exception.zip](https://github.com/FlagBrew/Checkpoint/files/3597034/Checkpoint.exception.zip)

**Comment by EtianAM** [comment]
I try to reinstall and it momentary works, but I turn off and turn on the console and it stops of work again.

**Comment by BernardoGiordano** [comment]
Can you try removing `3ds/checkpoint/*cache` and `3ds/checkpoint/config.json` ?

**Comment by Kontiki-** [comment]
I just tried and it still crashed, but this time with no stack dump.

**Comment by BernardoGiordano** [comment]
Check out this as well https://www.reddit.com/r/3dshacks/comments/d1hkgu/checkpoint_370_released_featuring_cheat/ezsv19p

**Comment by AlbertoDiazC** [comment]
Same for me... until I inserted a physical cartridge in the slot.
It seems to crash when there isn't any game installed or inserted.
