### ISSUE TITLE
Cheats not working on Switch

### ISSUE THREAD

**Issue by melsbacksfriend** [FlagBrew/Checkpoint#236]
Describe the bug A clear and concise description of what the bug is.
My cheat codes won't enable.  The game behaves like normal.  
To Reproduce Steps to reproduce the behavior:

Try to turn on cheats for a game.  
Go into game.  
Expected behavior A clear and concise description of what you expected to happen.
Cheats to be applied
Screenshots If applicable, add screenshots to help explain your problem.

Entrypoint: Atmosphère
System version: 8.1.0
Checkpoint version: 3.7.0
SD Card Filesystem: FAT32
Result code (if available):
Additional context Add any other context about the problem here.
The game I tried to use cheats with was Pokémon Let's Go Eevee.

**Comment by BernardoGiordano** [comment]
LGPE cheats are broken, that's not an issue with the cheat engine but with the cheat codes itself. Also, please report broken codes on [Sharkive's repository](https://github.com/FlagBrew/Sharkive).

**Comment by melsbacksfriend** [comment]
Thank's for letting me know.
