### ISSUE TITLE
Checkpoint on Switch SXOS 

### ISSUE THREAD

**Issue by wolfbitez23** [FlagBrew/Checkpoint#237]
Tried updating it using SX Installer, Tried to send via FTP on SXOS, Tried copying it manually on the memory card it just keeps crashing back to the Homebrew Menu.

For now back to 3.6.0

**Comment by Conan179** [comment]
you muss youse nsp injekt. google it

**Comment by BernardoGiordano** [comment]
It doesn't crash. It gracefully exits. Also, NSP inject is not suggested. Please use a CFW that is able to run homebrew over regular titles.
