### ISSUE TITLE
Checkpoint will freeze when pressing the - button when the switch is in aireplane mode

### ISSUE THREAD

**Issue by Cubuss** [FlagBrew/Checkpoint#238]
**Describe the bug**
Checkpoint will freeze when pressing the `-` button on the left joycon to open the instruction menu when in aireplane mode

**To Reproduce**
1. Put the switch in aireplane mode
2. Open checkpoint
3. Press - on the left joycon
4. Checkpoint will freeze and doesnt open the instruction menu, you can unfreeze by pressing home button and resuming checkpoint

**Expected behavior**
Displaying the instruction menu

**Screenshots**

**Switch:**
- Entrypoint:
- System version: 8.1
- Checkpoint version: 3.7
- SD Card Filesystem: exfat
- Result code (if available):

**Additional context**
Haven't tested if this issue only occures when using aireplanemode,
My gues is that if the switch wifi is enabled but not connected to wifi that it will do the same thing

**Comment by BernardoGiordano** [comment]
I can't reproduce this. Airplane mode, pressing `-` brings up the instruction menu just fine

**Comment by BernardoGiordano** [comment]
WIll reopen this again if it is still an issue with the next version
