### ISSUE TITLE
How is this app ran on Atmosphere 0.9.4?

### ISSUE THREAD

**Issue by dothackjhe** [FlagBrew/Checkpoint#240]
I'm getting an error where the app is prompted not to run in "Applet Mode." Problem is, I do not even know how to do just that. 

Can anyone tell me how I'd make this app work on Atmosphere 0.9.4, firmware 8.1.0?

**Comment by fennectech** [comment]
You are intended to use title take over.

**Comment by dothackjhe** [comment]
How do I go about doing that?

**Comment by BernardoGiordano** [comment]
Hold R while starting a title.
