### ISSUE TITLE
Feature Request [Cheat code 3DS)

### ISSUE THREAD

**Issue by davibonacorso** [FlagBrew/Checkpoint#241]
Good Morning!  I would like cheats added for the game Metal Gear Solid Snake Eater (usa)

**Comment by GriffinG1** [comment]
Nobody on the FlagBrew team knows, or wants to learn, how to make cheats. You're free to search online for any though, and make a PR to the database [here](https://github.com/FlagBrew/Sharkive). And for further note, any issues specifically concerning the database should go there.

**Comment by JourneyOver** [comment]
Closing as this is not the right place to make issues for the cheat database.
