### ISSUE TITLE
red screen

### ISSUE THREAD

**Issue by enigma14** [FlagBrew/Checkpoint#242]
Hello,
on my switch with fw 8.1.0 I launched the checkpoint.nro files v3.7.2 and 3.7.0 from homebrew's os sx cfw, I get red screen with the phrase "please do not run checkpoint in applet mode". What is the problem ? how can I fix that? thanks
![IMG-20190917-WA0001](https://user-images.githubusercontent.com/16175320/65035561-c4da6d80-d949-11e9-8b35-5684b5eb1764.jpeg)

**Comment by GriffinG1** [comment]
switch to atmosphere and use title takeover

**Comment by enigma14** [comment]
> 
> 
> switch to atmosphere and use title takeover

Hello,
isn't sx os compatible ? I have seen a lot of tutorials on the web

**Comment by GriffinG1** [comment]
If it has a way of title takeover, sure, but only atmosphere is explicitly supported and sxos is stolen trash

**Comment by enigma14** [comment]
I have seen videos with people working with it but they were older version... I would like to understand what is the problem in my specific case at least to better understand and curiosity

**Comment by GriffinG1** [comment]
Applet mode is shit. Per 3.7.1 changelog:

> Added: Checkpoint can now run again under applet mode, but:
it will be very annoying.
functionalities may not work properly and memory corruption may happen. Occasionally, the application could hang when trying to access one of the system applets.
Please do not run Checkpoint in applet mode.

Again, use title takeover.

**Comment by BernardoGiordano** [comment]
There's nothing to fix there
