### ISSUE TITLE
Cheats crash on normal mode.

### ISSUE THREAD

**Issue by toxic9** [FlagBrew/Checkpoint#243]
Hi!
The cheats menu crash Checkpoint.
On applet mode it seems to work, but we have a red filter on the screen.
Idont know the problem of running it on applet mode. It always worked that way.
We should be promped to bypass the use on applet mode instead of that annoying filter.
Thanks

**Comment by GriffinG1** [comment]
;clap: read ;clap: the ;clap: changelogs ;clap: 

> Added: Checkpoint can now run again under applet mode, but:
it will be very annoying.
functionalities may not work properly and memory corruption may happen. Occasionally, the application could hang when trying to access one of the system applets. Watch this video for an example.
Please do not run Checkpoint in applet mode.

**Comment by BernardoGiordano** [comment]
@toxic9 can you explain what 'cheats menu crash Checkpoint' means?

Can you give more details about system version, cfw and attach a video reproducing the issue? Please open a new issue while doing so and follow the template.

**Comment by toxic9** [comment]
Hi!
Running Checkpoint on normal mode, I click on cheats and Checkpoint shows some error message and it goes to homebrew menu again. I need to re-enter Checkpoint.
After several tries, the error message seems to have changed. I can't remember what it says right now.
I'm using 9.0.0 on Atmos 0.94. Everything updated.
I can send you some pictures (or video) later.

**Comment by GriffinG1** [comment]
> Can you give more details about system version, cfw and attach a video reproducing the issue? Please open a new issue while doing so and follow the template.
