### ISSUE TITLE
Cheats menu not working on normal mode

### ISSUE THREAD

**Issue by toxic9** [FlagBrew/Checkpoint#244]
When I enter cheats menu in normal mode (holding R and clicking a game):

![IMG_20190918_132650](https://user-images.githubusercontent.com/34398680/65153293-684a8180-da21-11e9-804a-61e221692451.jpg)

video:
https://streamable.com/1bv3o

When I enter cheats menu in Applet mode, it works but we have the annoying Red filter and it's difficult to see what we are doing.

OFW: 9.0.0
CFW: Atmos 0.9.4
Checkpoint: 3.7.2

**Comment by BernardoGiordano** [comment]
what game is it?

**Comment by toxic9** [comment]
Yoshi Wooly World

**Comment by toxic9** [comment]
Have you been able to reproduce the issue?
Thanks

**Comment by BernardoGiordano** [comment]
does this fix the issue? https://www.dropbox.com/s/yzxslwvo2z678p1/Checkpoint.7z?dl=0

**Comment by toxic9** [comment]
Hi!

There are a few times thet it still shows an error when clicking R  
stick to open  the cheats menu...
Bu it's much better now!
THank you very much for your work.
 

Citando Bernardo Giordano <notifications@github.com>:

> does this fix the issue?  
> https://www.dropbox.com/s/yzxslwvo2z678p1/Checkpoint.7z?dl=0
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].

 

Ligações:
---------
[1]  
https://github.com/FlagBrew/Checkpoint/issues/244?email_source=notifications&email_token=AIGODWDVJ5H7BFHEMFIE4MDQMW53FA5CNFSM4IX64DI2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAHUWTY#issuecomment-537873231
[2]

**Comment by MonfGeiger** [comment]
running atmo 0.19.3 using the SciresM fork of checkpoint since the 3.7.4 version crashes with atmo 0.19.3 and in the homebrew menu in R button normal mode

I didnt realized I had this fork in my switch until I bothered checking the crc of the app on my switch with a fresh copy downloaded to my desktop. So I boot it up, click the right thumbstick to use the cheats function for bayonetta 2, and the app crashes just as the starter post above

**Comment by GriffinG1** [comment]
This should've been fixed in v3.8.0. If it isn't, feel free to let me know and I'll reopen this.

Edit: I'll be merging all related issues into #294, so let me know there please.
