### ISSUE TITLE
[Feature Request] PC version

### ISSUE THREAD

**Issue by massijay** [FlagBrew/Checkpoint#246]
It would be nice to have a PC version of Checkpoint, so we could backup/restore our saves backups without using any homebrew (on Horizon OS) but accessing them through memloader and HacDiskMount

**Comment by fennectech** [comment]
This has been asked before and is out of scope for checkpoint.

**Comment by ThatNerdyPikachu** [comment]
Might end up writing a tool for this using LibHac -- it already has the functionality to do this.
