### ISSUE TITLE
Error- Checkpoint can't run again under applet mode - version 3.7.2

### ISSUE THREAD

**Issue by Emeraldu** [FlagBrew/Checkpoint#247]
Using a Nintendo Switch with SX OX 2.8 beta and system version 8.1
microSD card is formated in FAT32, all other homebrew apps are working (ChoiDujour, goldleaf and Checkpoint 3.6.0 woring great).

I get a redish screen when I run Checkpoint with the error: Checkpoint can't run again under applet mode
I can't load or backup saves from any game.

I've tested version 3.7.1 and 3.7.2 , both give me the same error.
I had to go back to version 3.60 that works great.

**Comment by piepie62** [comment]
Run Checkpoint through Atmosphère's title takeover. SX OS isn't supported

**Comment by BrianGilbert** [comment]
@Emeraldu although not supported 3.7.2 does still work on SXOS

**Comment by piepie62** [comment]
Please don't post on closed, nearly month-old issues
