### ISSUE TITLE
[Feature Request] Rework Cheats Path

### ISSUE THREAD

**Issue by sora10pls** [FlagBrew/Checkpoint#249]
Tested using v3.7.2.

Currently, Checkpoint generates a `cheats` directory both on the root of the SD Card as well as in the following path: `sd:/3ds/Checkpoint/`. The former is used to store cheat textfiles, while the latter goes completely unused.

To avoid clutter on a user's SD Card, it'd be preferred if textfiles would be stored in `sd:/3ds/Checkpoint/` (where a directory is already created but unused) rather than in a `cheats` directory on the root of the SD Card.

**Comment by piepie62** [comment]
That's not possible. Luma, which is what actually applies the cheats, does not read from Checkpoint's directories. The `cheats` folder in Checkpoint is the way that users would provide cheat databases built from Sharkive before the next Checkpoint release

**Comment by sora10pls** [comment]
Is it at least possible to not generate a `cheats` folder every time Checkpoint is launched? Even when I don't do anything in the app, the folder re-generates itself.
