### ISSUE TITLE
Bug Report wrong code

### ISSUE THREAD

**Issue by Garmin969** [FlagBrew/Checkpoint#250]
When I start CheckPoint 3.7.2, the screen appears the wrong code:0XD88007FA
ROSOLINA NOT FOUND ON THIS STSTEM, AN UPDATED CFM IS REQUIRED TO LAUNCH CHECKPOINT.
How can I solve this problem?

**Comment by GriffinG1** [comment]
update your cfw, it's outdated.

**Comment by Garmin969** [comment]
> update your cfw, it's outdated.

Where can I update it?(Actually I even don't know what the cfw is QAQ)

**Comment by GriffinG1** [comment]
Turn your 3ds on while holding start. If it goes directly to the home menu, follow [this guide](https://3ds.hacks.guide). If it brings up a different menu, post the version number here.
