### ISSUE TITLE
Doesn't load in 9.0.1 firmware

### ISSUE THREAD

**Issue by taunnt** [FlagBrew/Checkpoint#255]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**3DS:**
- Entrypoint:
- System version:
- Checkpoint version:
- Result code (if available):

**Switch:**
- Entrypoint:
- System version:
- Checkpoint version:
- SD Card Filesystem:
- Result code (if available):

**Additional context**

**Comment by GriffinG1** [comment]
Please fill out the template properly.

**Comment by piepie62** [comment]
What Griffin said
