### ISSUE TITLE
Crash, 2144-0001 / 0100000000001000, no theme

### ISSUE THREAD

**Issue by Stuntaneous** [FlagBrew/Checkpoint#259]
**Describe the bug**

Crash upon launch of Checkpoint from homebrew menu. Black screen. Hitting home button caused the screen to turn white (presumably related to my theme being the default white). Shortly after, Atmosphere crashed with error code 2144-0001 (0x290), title 0100000000001000.

**Switch:**
Checkpoint 3.7.2, firmware 9.0.1, Atmosphere 0.9.4, FAT32 128 GB U3 card. No themes installed or sitting on the SD card.

**Additional context**
I'm trying to solve random crashing on this particular Switch ([GBAtemp thread](https://gbatemp.net/threads/switch-freezing-randomly-only-in-cfw.550785/)) and this occurred after my latest, very minimal setup to test stability. I've ruled out the SD card being the issue and somewhat ruled out the SD reader but not entirely.

I've previously attempted to use Kefir to add a linked account to this console but have since wiped the SD card entirely. Is it possible user accounts were changed elsewhere in some part of the internal storage? I don't particularly understand the Switch's layout of partitions, e.g. SYSTEM, USER, SAFE, etc.

**Comment by Stuntaneous** [comment]
**Update:** downgraded from 9.0.1 to 9.0.0 and Checkpoint still crashes in the same scenario but with a different error, 2168-0002 (0x4a8), title 010000000000100D.

**Comment by BernardoGiordano** [comment]
Are you sure you have latest hb_loader and nx-hbmenu?

**Comment by Stuntaneous** [comment]
Yes.

**Comment by Stuntaneous** [comment]
I believe I've fixed it. No issues.. yet. Using Hekate's "migrate emuMMC" option to repair it seems to have fixed everything. I highly suspect the root of the issue was quick formatting the SD and programs going to memory addresses with old data.
