### ISSUE TITLE
Can't see saves of Ring Fit Adventure to restore

### ISSUE THREAD

**Issue by Stuntaneous** [FlagBrew/Checkpoint#262]
**Describe the bug**
Ring Fit Adventure can have its saves backed up, and can be seen as backed up by that account as normal. But, a different account can't see the saves to restore them.

**To Reproduce**
- Create new emuMMC
- Backup saves
- factory reset emuMMC
- Restore saves --- all but Ring Fit Adv. available

**Switch:**
- System version: 9.0.1
- CFW version: 0.9.4
- Checkpoint version: 3.7.2
- SD Card Filesystem: FAT32
- Game version: launch and with its first, only update

**Additional context**
All other saves backup and restore normally.

**Comment by BernardoGiordano** [comment]
Can you shoot a video of this issue?

**Comment by Stuntaneous** [comment]
Not of the backing up, as I'm not keen to redo the emuMMC all over. As for the restoring, I'm not sure what there'd be to see. It's quite simply just as you'd expect, all the games and their saves happily appearing and restoring, except Ring Fit Adventure doesn't even feature in the tiled display of games.

**Comment by Stuntaneous** [comment]
I should mention as well, I think I noticed while other games will prompt for a user selection, Ring Fit Adv. did not. I thought that was odd. I believe that happened with one account available to choose from, but possibly when there was two - I forget. This is with user selection enabled in the settings, of course.

**Comment by BernardoGiordano** [comment]
I just need a video of the restore to see what's going on

**Comment by Stuntaneous** [comment]
I'm not sure what I'd film, I'd be filming the lack of anything.

**Comment by Stuntaneous** [comment]
Any idea what might be causing this, or how it may be fixed?
