### ISSUE TITLE
Freeze when change user

### ISSUE THREAD

**Issue by ratwix** [FlagBrew/Checkpoint#263]
When I try to change user with ZL or ZR, application freeze

**Comment by BernardoGiordano** [comment]
Are you running homebrew in applet mode?

**Comment by ratwix** [comment]
I don't know (and I don't think so). Application is run throw SX OS 2.9.2,
throw the Homebrew menu

**Comment by BernardoGiordano** [comment]
That is clearly an issue with SX OS. Please use Atmosphere.
