### ISSUE TITLE
Application non respond if i want to change the user (ZL / ZR)

### ISSUE THREAD

**Issue by Pryape** [FlagBrew/Checkpoint#264]
**Describe the bug**
Hello, if i want to change the user (ZL or ZR) the application freeze. And i cant do nothing. I have to press home button

**To Reproduce**
1. Launch Checkpoint in homebrew section of sx os 2.9.2 stable
2. Click on 'ZR'
3. Freeze

**Switch:**
- Entrypoint: SX OS Stable 2.9.2
- System version: 9.0.1
- Checkpoint version: 3.7.3
- SD Card Filesystem: SYSNAND
- Result code (if available):

**Additional context**

**Comment by BernardoGiordano** [comment]
Issue is related to you using SX OS rather than another CFW that doesn't suck, closing.

SX OS is unable to run homebrew in extended memory mode, which causes issues while opening system applets like the account selection or the keyboard. Please refrain from using SX OS.

**Comment by amendgit** [comment]
Having the same problem.  When I want to switch user with ZL and ZR, the application doesn't respond. 

Switch:
* Entrypoint: atmosphere 0.9.4
* System version: 8.1.0
* Checkpoin version: 6.7.3
* SD Card Filesystem: exFAT

Thanks ~~

**Comment by amendgit** [comment]
Having the same problem. When I want to switch user with ZL and ZR, the application doesn't respond.

Switch:

Entrypoint: atmosphere 0.9.4
System version: 8.1.0
Checkpoint version: 3.7.3
SD Card Filesystem: exFAT

Thanks ~~

**Comment by Mike007899** [comment]
I believe, and this is just a hunch, your problem is exFAT. You should be running FAT32 even though the switch can handle exFAT. (Dont crucify me if im wrong, I am more knowledgeable with the 3DS.)

**Comment by BernardoGiordano** [comment]
You're probably running homebrew using applet mode. Please use title takeover instead.

**Comment by madvillain91** [comment]
problem persit on sx os applet mode or not. And ExtFAT ou FAT32. Impossible to switch user to do all backup :(

**Comment by GriffinG1** [comment]
Please do not comment on closed issues.
