### ISSUE TITLE
User not Detected in EmuNand

### ISSUE THREAD

**Issue by elidoe89** [FlagBrew/Checkpoint#265]
Hi,

I am tying to backup --> edit --> and restore a gamesave (pokemon).

I use atmosphere 0.8.4 with EmuNand on raw partition as copy of my sysnand.

When I open Checkpoint it detects only 1 profile (the one copied from the sysnand) but it doesnt detect the new profile created on EmuNand.

Could you please verify and if necessary implement the option to swap to new profiles?
Thanks

**Comment by BernardoGiordano** [comment]
Checkpoint has nothing to do with user detection, as it is a system applet feature.
