### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Th3Alic3** [FlagBrew/Checkpoint#267]
Checkpoint version: Nintendo Switch
Feature: Cheat System

Issue: Cheats system lists cheats for other versions of the game.

Example: Pokemon Let's Go Eevee and Pikachu both have received two game updates (v1.0.1 and v1.0.2). There are cheats available intended for v1.0.0 and v1.0.1 but none for v1.0.2 HOWEVER regardless of which version of the game is on the Switch all cheats appear. I have the v1.0.2 of the game but even though there are no cheats for that version - Checkpoint still shows all of the v1.0.0 and v1.0.1 cheats.

Would it be possible in future versions to revise the cheats list to show their software version compatibility or better yet don't show one's not compatible with the version of the game you are using?

(This may belong under new feature requests but I was unsure so I will apologize if it belonged in there.)

[Side note: is anyone going to update the cheats for these two games for the v1.0.2?]

**Comment by GriffinG1** [comment]
At this moment, it is intended behavior as checkpoint can’t check update number

**Comment by Th3Alic3** [comment]
Would it be possible in the future to amend the cheats database to include a qualifier/tag along with the cheats so the user can manually set version # in Checkpoint. Thus allowing Checkpoint the ability do show only cheats that will work.

**Comment by GriffinG1** [comment]
it would require luma and atmosphere to update their code processing to allow it, as version number needs to not screw up loading the cheat

**Comment by Th3Alic3** [comment]
In terms of the database, who over sees that? Is there a community that I can reach out to? _(As I mentioned, they still have not provided updated codes for v1.0.2 and I would love to appeal to them to revise the code names if unable to convince anyone to update the code system to support versions.)_

In the meantime, are the cheats stored in local text files (similar to EdiZon which doesn't work if you have Tinfoil on your Switch) on a folder so I can manually edit titles to include version #'s on my own Switch?

**Comment by GriffinG1** [comment]
The database is managed by flagbrew in [Sharkive](https://github.com/FlagBrew/Sharkive). Nobody on FlagBrew knows how to make codes, or wants to learn. Also, there's no way of knowing for sure what versions a code will work on without testing it, which would be horrendous to do for all the games in the database.

Cheats are stored in Checkpoint's binary. You can clone Sharkive, edit the db, build the db, and put it into Checkpoint, but that's the best you can do. Build instructions are in Sharkive's readme.
