### ISSUE TITLE
Trouble Report

### ISSUE THREAD

**Issue by thelichkingecu** [FlagBrew/Checkpoint#268]
Hi, i have this trouble when i use the app on switch, when i want to back up a save in any game i dont know if i am the only one with this trouble (the cheats works perfectly) 
![Trouble](https://user-images.githubusercontent.com/57513296/68445406-d7ce2900-01a7-11ea-9335-b10af4cc330e.jpg)
please help

**Comment by BernardoGiordano** [comment]
Make sure to run Checkpoint using title takeover, not applet mode. That's most likely the issue here.
