### ISSUE TITLE
Bug Report - 3.7.3 does not support back up VC save

### ISSUE THREAD

**Issue by Johngew** [FlagBrew/Checkpoint#269]
Bug Report - 3.7.3 does not support back up VC save

but on 3ds 3.7.0 does support VC game save.

**Comment by BernardoGiordano** [comment]
This issue doesn't make much sense since nothing has changed from 3.7.0 to 3.7.3 that affected this. If you want to reopen the issue, please fill out the template properly.

**Comment by Johngew** [comment]
thank for reply.
by the way is ok . I will keep seek new version and if does not able run
back up VC save then I will drop back 3.7.

thank for update and notice about the changes.

Bernardo Giordano <notifications@github.com> 于2019年11月9日周六 上午2:55写道：
