### ISSUE TITLE
Bug Report VC could found in 3.7.3 [the way show up VC save if reinstall game]

### ISSUE THREAD

**Issue by Johngew** [FlagBrew/Checkpoint#270]
Bug Report VC could found in 3.7.3 [the way show up VC save if reinstall game]

I have open in 3.7.3 but cant find out VC save in past .
before that I was back to 3.7. 

but some pages show PRESS B [hold B refresh page].
then 3.7.3 Checkpoint will show up the save. [VC have to run a time created save and no need new game and save. Because I delete the game and keep save in checkpoint backup]

thank for update

**Comment by GriffinG1** [comment]
Closing due to age. If you are still having an issue with v3.8.0, please open a new issue.
