### ISSUE TITLE
Option to 'de-register' a title from Checkpoint

### ISSUE THREAD

**Issue by Stuntaneous** [FlagBrew/Checkpoint#271]
**Is your feature request related to a problem? Please describe.**
For example: 
I install a game from one region, run it to register it in Checkpoint, realise my savegame is for another region, uninstall the game and reinstall the other region, I now have two confusing listings for the same game in Checkpoint

**Describe the solution you'd like**
The ability to de-register a title

**Comment by piepie62** [comment]
Delete the relevant save archive through an application like FBI. Checkpoint specifically does not allow deleting archives like that because it has no way to create them with the correct parameters.

**Comment by BernardoGiordano** [comment]
Use filters in configuration when possible, otherwise, delete the unused archive.
