### ISSUE TITLE
Bug Report - Crash when changing user profile

### ISSUE THREAD

**Issue by undefeatabl3** [FlagBrew/Checkpoint#272]
**Describe the bug**
When switching user profiles in 3.7.3 on Switch, Checkpoint will hang/crash.

**To Reproduce**
1. Open Checkpoint
2. Press ZL or ZR
3. Crash

**Expected behavior**
User profile would change and other saves would appear

**Screenshots**

**Switch:**
- Entrypoint:
- System version: 9.0.1
- Checkpoint version: 3.7.3
- SD Card Filesystem: EXFAT

**Comment by GriffinG1** [comment]
Use title takeover, not applet mode.
