### ISSUE TITLE
Pokémon HeartGold/SoulSilver Freezing

### ISSUE THREAD

**Issue by domesticwarlord86** [FlagBrew/Checkpoint#273]
When trying to restore a sav game file using checkpoint to Pokémon HG/SS it freezes the entire 3DS. The only way I can get it to respond is to hold the power button. I get an error message about ARM11 crash. 
Processor: ARM11 (core 1)
Exception type: preface abort (Kernel panic)
Fault status: Debug event
Current process: pxi 
I’ve tried this on two separate 3DS.
For testing purposes I backed up the save file for my copy of Pokémon Black and restored that using Checkpoint and worked without any issues.
For testing purposes I created a new game on HeartGold, played to first Pokémon, saved, went to checkpoint and backed the save up successfully. Loaded the game up, played about five minutes and saved again. Loaded checkpoint back up and attempted to restore the save made earlier by checkpoint and got the same freezing behavior. 

My N3DS runs sys with Luma3DS v9.1. 
I’m using the latest version of Checkpoint installed via cia from the website.

**To Reproduce**
1. Go to Checkpoint. 
2. Create backup of HeartGold/SoulSilver
3. Attempt to restore created backup, system locks up. 
4. Press power button to get system to respond, see error. 

**Expected behavior**
I expect to be able to restore backups to Pokémon SoulSilver/HeartGold without any errors. 

**Screenshots**
![F99F71EC-1BBC-4F22-8C95-3265E60F1ECE](https://user-images.githubusercontent.com/57776315/68903063-8b32a280-06ff-11ea-8697-d80d8ed77dd0.jpeg)

**3DS:**
- Entrypoint: Luma3DS v9.1
- System version: 11.12.0-44U
- Checkpoint version: 3.7.3
- Result code (if available):

**Comment by aureola-watches** [comment]
Same issue with me.

**Comment by piepie62** [comment]
Could either of you send your save? HGSS clones that we've had to deal with in PKSM can be strange, and I want to see if this perhaps is the same problem

**Comment by domesticwarlord86** [comment]
> Could either of you send your save? HGSS clones that we've had to deal with in PKSM can be strange, and I want to see if this perhaps is the same problem

Turns out mine was due to a fake cartridge. After realizing it was fake I got a legit copy and the save restored just fine.

**Comment by piepie62** [comment]
Since this was a fake cartridge problem, there's no good way to fix it. As such, I'm closing this
