### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by FamilyGuy0395** [FlagBrew/Checkpoint#274]
Checkpoint is unable to display the save files that I have on my SD card.  Also, I'm unable to backup new save files, even when it says that it successfully did so.  I'm not sure what the issue is here, but obviously the inability to backup saves, restore saves, or even view my saves is very problematic, and I'd REALLY appreciate any and all assistance to resolve this issue as soon as possible so I can go back to backing up my saves!  Thank you so much!

Atmosphere/Kosmos v0.9.4/v14.2
Checkpoint v3.7.3
hekate v5.0.2
TegraRcmGUI v2.6
Switch firmware v9.0.1

**Comment by BernardoGiordano** [comment]
Couod you explain better what the issue is and how to replicate it? A video would also be appreciated

**Comment by FamilyGuy0395** [comment]
Is there anyway I can record my Switch's screen w/o the need for a capture card so I could show you what I mean?

**Comment by BernardoGiordano** [comment]
Your smartphone should be good enough

**Comment by FamilyGuy0395** [comment]
Okay, when I get a chance, I will do that.  Can I upload a video file here?

**Comment by BernardoGiordano** [comment]
Not directly. You can upload the video on a video streaming service like YouTube

**Comment by FamilyGuy0395** [comment]
To be honest, for privacy's sake, I'm really not comfortable with taking a video and uploading it publicly to YouTube.  Is there any other way I can explain this?

My saves are located under [root] --> switch --> Checkpoint --> saves.

When I open up Checkpoint on the Switch, the saves aren't displayed.  Under every single game it just says "New..." where I can backup a save.

If I try to backup a save, it says that it was backed up successfully, but nothing was actually written to the microSD card, nor is the save listed under the respective game.

**Comment by BernardoGiordano** [comment]
Are you using a FAT32 formatted SD Card or exFAT?

> My saves are located under [root] --> switch --> Checkpoint --> saves.

Can you at least send a screenshot of the folder's content? Sadly, without you providing additional info, I can not diagnose the root of the issue properly

**Comment by FamilyGuy0395** [comment]
exFAT

Not sure why a screenshot would help?  Under switch --> Checkpoint --> saves just contains all of the individual game folders, and within those folders, the save files themselves.

**Comment by BernardoGiordano** [comment]
Problem must be caused by exFAT. Please format your SD Card to FAT32 and open another issue if the problem persists

**Comment by FamilyGuy0395** [comment]
When I copied everything off my microSD card, formatted it to FAT32, copied everything back on, re-set up RCM, I'm getting an error after injecting the payload: "Sleep Mode library is missing!".  What am I supposed to do now?  Am I screwed?

**Comment by deadair3210** [comment]
No, you must have failed to copy or missed some files. Download hekate and cfw again

**Comment by GriffinG1** [comment]
This isn't the place for non checkpoint issues. Go to either the FlagBrew server, linked in the project description, or to the Nintendo Homebrew server, found [here](https://discord.gg/C29hYvh).
