### ISSUE TITLE
Bug Report change user it's impossible .

### ISSUE THREAD

**Issue by will5517** [FlagBrew/Checkpoint#275]
Hello, it is impossible to change the user with the ZL and ZR keys because as soon as I touch these keys, checkpoint frieze and I have to return to the main menu of the switch. Do you have a solution ?
thank you in advance

**Switch:**
- Entrypoint:
- System version: 9.0.1
- Checkpoint version: 3.7.3
- SD Card Filesystem: exFat
- Result code (if available):
- SX OS 2.9.2

**Comment by BernardoGiordano** [comment]
SX OS is unable to let homebrew run under title takeover, resulting in not enough memory for Checkpoint to launch system applets.

Please use title takeover and avoid using SX OS.

**Comment by LVNeptune** [comment]
Works fine under SXOS on 3.6. Issue started after 3.6.

**Comment by BernardoGiordano** [comment]
That's because Checkpoint started using system applets to change users and to show the system keyboard, as stated [in the changelogs](https://github.com/FlagBrew/Checkpoint/releases/tag/v3.7.0).

Atmosphere is able to run in said mode fine. Please don't justify your CFW's lack of features and complain to developers behind it instead.

**Comment by LVNeptune** [comment]
No justification here was trying to understand why it was working then stopped. Makes sense. Would suggest putting something along the lines of incompatible with SXOS in the changelog, however so this doesn't keep popping up randomly.

**Comment by will5517** [comment]
thank you for your answers even if I did not all understand ... but I saved my backup version 3.6. Is it possible now to install these backups with version 3.7.3 ??? thank you again and sorry for my bad english ...

**Comment by BernardoGiordano** [comment]
It is always possible to backup and restore saves with different versions of Checkpoint.

**Comment by will5517** [comment]
thanks again  Bernardo for your work and sharing

respect
