### ISSUE TITLE
Pokemon Sword and Shield Problems

### ISSUE THREAD

**Issue by johndu132** [FlagBrew/Checkpoint#276]
Hi there.  Just wanted to mention that Checkpoint is not properly backing up Pokemon Sword and Shield saves.  All that appears is a folder with the name you designate when backing up, but nothing appears inside of it.

**Comment by deadair3210** [comment]
Works fine for me, both the main file and the backup file are correctly generated

**Comment by johndu132** [comment]
Really?  That's strange.  I've been trying for a while but can't seem to get it to work.  I would just delete Checkpoint from the root of my SD card and copy the new folder from here to the root to reinstall it right?

**Comment by deadair3210** [comment]
Make sure save redirection is off in atmospheres settings if you are using it

**Comment by johndu132** [comment]
Save redirect?  I don't believe I've heard of that.  When you say Atmosphere's settings, where would I find that?  I looked in the payload menu for hekate and also in Kosmos Toolbox but I don't see anything related to it.

**Comment by Haydut86** [comment]
Hi there,

Do we need to hack the Nintendo switch for transferring save files? I'm new here.

**Comment by deadair3210** [comment]
you need custom firmware to run Homebrew at all

**Comment by johndu132** [comment]
Well, that's somewhat true.  If you want to transfer save files without custom firmware, the Switch has an option of transferring to another system, but all saves from the source system are deleted.

**Comment by deadair3210** [comment]
Figured they were talking about Homebrew since the issue was here. If save redir is off and you don't have a emunand I have no idea. Filesystem corruption maybe?

**Comment by johndu132** [comment]
I have an emuNAND, and there doesn't seem to be any file corruption.  I do appreciate the thoughts though, and it seems this issue might actually be tied with Atmosphere itself.

**Comment by deadair3210** [comment]
Correct me if I'm wrong, as I don't use emunand, but doesn't that explain why your saves are only different if you are in cfw vs stock? the saves are stored on the band, so if you boot into a different nand image the saves would be different, no?

**Comment by johndu132** [comment]
This is true, but I'm ot using emuNAND either.  However, I'll tinker with an idea I just got and I'll get back to posting here.

**Comment by johndu132** [comment]
I found out that this is eactly what it is.  I had to reboot into hekate, then boot into sysNAND with CFW enabled.  Then I found all my game saves that are supposed to be there.  Thank you for helping me figure that out.

**Comment by Haydut86** [comment]
> Well, that's somewhat true. If you want to transfer save files without custom firmware, the Switch has an option of transferring to another system, but all saves from the source system are deleted.
> https://www.nintendo.com.au/help/switch-storage-and-data-management/how-to-transfer-your-save-data-to-a-nearby-nintendo-switch
> 
> However, you shouldn't be asking that question here. This is a specific issue I opened, but I do appreciate your efforts.
> 
> Edit: Found out how to configure the save redirect, and mine is not redirecting at all.

I am very sorry for my rudeness. Thank you very much for your kindness
