### ISSUE TITLE
Switch User Swap Not Working

### ISSUE THREAD

**Issue by AlinMGupta** [FlagBrew/Checkpoint#277]
When I Use ZL/ZR to switch users on my nintendo switch, the system crashes.

**To Reproduce**
1. Boot Using Hekate & fusee
2. Launch Homebrew
3. Click on Checkpoint
4. Press ZL/ZR

**Expected behavior**
I Wanted it to cycle between my three users on the switch

**Comment by GriffinG1** [comment]
use title takeover.

**Comment by piepie62** [comment]
Also, please feel free to both use issue templates and search closed issues before you open a new one next time

**Comment by AlinMGupta** [comment]
Can you explain what title takeover is?
Sorry, new to this sort of stuff.
