### ISSUE TITLE
Backups Not Showing On MicroSD Card

### ISSUE THREAD

**Issue by lagolfer09** [FlagBrew/Checkpoint#279]
**Describe the bug**
After installing Kosmos Defaults including Checkpoint 3.7.3 on my Switch. Whilst holding down R and selecting a game, I can access Checkpoint and see all off my games. When I select backup, it states Successfully Transferred to Card but when I turn-off and place the Micro SD card in my PC, I have no saves folder showing in my Checkpoint Folder.

If I retrace my steps and do the same thing again, the backup I made also isn't showing on the switch, as though it never saved.

**To Reproduce**
Described above

**Expected behavior**
The backup to show when the SD card is placed into a PC under the Checkpoint - Saves folder

**Screenshots**

**Switch:**
- Entrypoint: 
- System version: Atmosphere (Kosmos) (v0.9.4/v14.2)
Hekate  v5.0.2
- Checkpoint version: 3.7.3
- SD Card Filesystem: FAT32
- Result code (if available):

**Comment by chrisnieves4075** [comment]
In having the samw issue no save files and my switch has atmosphere but checkpoint creates the folder but no save file.

**Comment by jd00bz** [comment]
If you have any valid backups on your sd card, back them up on your pc. Then delete every directory in the “saves” folder as well as checkpoint.log and config.json. Open checkpoint again and it will create a new log and json. back up a save. If the backup appears below “new” after you created it, proceed as I shall mention below. If not, you may be experiencing a different issue. 

If the new save is appearing, create a new backup in checkpoint for every backup file you want to have. Copying your old backup folders to the directory will not work for this. Instead, checkpoint has to make the folder, and then you will need to manually overwrite the savedata.bin file with your old backup. Once the old backup file is in the new folder that checkpoint created, it can be restored in checkpoint.

**Comment by GriffinG1** [comment]
Closing issue due to age and use of Kosmos, please open a new issue if you are still having issues using v3.8.0 and the latest Atmosphere release.
