### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Giraffes-are-bae** [FlagBrew/Checkpoint#280]
whenever i try to switch accounts on checkpoint, it crashes

**To Reproduce**
1. go on checkpoint
2. use zr/zl
3. crash

**Expected behavior**
expected to change accounts

- Entrypoint: homebrew, using atmosphere
- System version: 9.0.1
- Checkpoint version: 3.7.3

**Additional context**

**Comment by BernardoGiordano** [comment]
Launch homebrew with title takeover, by holding B while launching a game.

This is not an issue. Please look at the already existing issues before submitting new ones.

**Comment by Giraffes-are-bae** [comment]
im not clear on what title takeover is and how it works, i hold b when opening a game but it just loads the game as normal, and when i do it on the actual checkpoint app in my switch homebrew menu, it does nothing,

i am genuinely confused on what you mean by this

**Comment by GriffinG1** [comment]
Hold R while launching a game, not B.
