### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by SnakeDeath** [FlagBrew/Checkpoint#281]
**Describe the bug**
Freezing when clicking on the profile picture in Checkpoint

**To Reproduce**
1. Running checkpoint 
2. Click on profile picture
3. freezing

**Expected behavior**
Freezing

**Screenshots**
i guess there is no need for screenshots 

**Switch:**
- Entrypoint:
- System version: 9.0.1 atmosphere 0.9.4
- Checkpoint version: 3.7.3
- SD Card Filesystem: exFat

**Comment by BernardoGiordano** [comment]
Please run homebrew using title takeover (Holding R while launching a game). Also, **please** look at already closed issues before opening new ones.

**Comment by SnakeDeath** [comment]
my bad thank you , just saw them
