### ISSUE TITLE
Add support for multiple user accounts (switch)

### ISSUE THREAD

**Issue by hitsuji** [FlagBrew/Checkpoint#282]
Currently, Checkpoint only seems to pick up the user account initially created on the switch.

There appears to be no way to select another account making it impossible to restore or backup saves for any other user.

**Comment by BernardoGiordano** [comment]
Not true. You can switch between users by clicking ZL/ZR or touching the account icon on the screen. Please use title takeover (holding R while launching a game) to do so safely, due to memory constraints occurring when launching a game using applet mode.
