### ISSUE TITLE
sx os checkpoint 0x0 aborted by user

### ISSUE THREAD

**Issue by Chaos192** [FlagBrew/Checkpoint#283]
I just bought sx pro and got it set up to emunand and checkpoint is giving the 0x0 aborted by user error whenever I try to backup any of my saves. It worked flawlessly when I was previously using atmosphere so it has to be something related to either emunand itself or sx os. I tried installing it via FTP and also through SX OS itself and no matter what I do using sx os I get this error. Not sure why it's doing this but my guess is the emunand is somehow confusing checkpoint or denying access possibly? I followed youtube tutorials etc afterwards to see if maybe I did something wrong and that isn't the case. I am on the newest firmware 9.0.1 and like I said previously it worked for atmosphere. I was using newest checkpoint version.

**Comment by BernardoGiordano** [comment]
Please read #282, #281, #280, #277, #275, #272, #268, #264, ...

**Comment by Chaos192** [comment]
I looked at all of those and It's not about changing user. I only have one user on my device and that's never changed and when I load the app it shows the correct user at the bottom. So it's just sx os not being supported properly which either it gets fixed or it doesn't. I just know now I wasted $50 on sx os and switched back to atmosphere to fix the issue.

**Comment by BernardoGiordano** [comment]
It's not about user change, but the reason it's the same. SX OS is a bad copy of atmosphere, in the terms of having left behind the most important feature needed to run homebrew properly nowadays. Get a refund

**Comment by Chaos192** [comment]
Yeah I am going to just try to send it back and get a refund. I hope it happens cause was a huge waste of money honestly. Atmosphere everything worked properly without issues.

**Comment by ELY3M** [comment]
I warned everyone about getting sxos.   sxos is very very worst cfw to waste money on.   I hope you did chargeback on your credit card.

**Comment by GriffinG1** [comment]
@ELY3M please stop replying to closed issues.
