### ISSUE TITLE
can't change user profiles

### ISSUE THREAD

**Issue by shawnhosg** [FlagBrew/Checkpoint#284]
Describe the bug
After Entering Checkpoint Homebrew App, attempts with ZL/ZR to switch user profile causes app to hang.

There are 3 user profiles as shown in the screenshots, however any attempts to switch user profiles causes app to hang.

To Reproduce

As described above

Expected behavior
Bottom right user profile icon to switch between different user profiles

Screenshots
https://1drv.ms/u/s!AqN6vgNsS2bZvnUz4UZdIUW_yzpi?e=S5JgA8

Switch:

    Entrypoint:
    System version: SX OS 2.9.2
    Checkpoint version: 3.7.3
    SD Card Filesystem: exFAT
    Result code (if available):

**Comment by BernardoGiordano** [comment]
Please read  #283, #282, #281, #280, #277, #275, #272, #268, #264, ...
