### ISSUE TITLE
Animal Crossing New Leaf 1.5 cheat database

### ISSUE THREAD

**Issue by tr0jance** [FlagBrew/Checkpoint#285]
I'm not sure if its an issue or if you really don't have the cheats for the said game, but there's no cheats available for Animal Crossing New Leaf 1.5. Is it possible to add it on the database?

**Comment by GriffinG1** [comment]
Nobody on FlagBrew is interested in learning how to make codes. If you find any working ones, you’re free to open a pr to [Sharkive](https://github.com/FlagBrew/Sharkive), where the db is stored.

**Comment by BernardoGiordano** [comment]
Please open this issue on Sharkive's repository.

**Comment by bluesky37** [comment]
hi, would it be possible to create cheat codes for this game in version 1.5 please ( welcome amiibo )
