### ISSUE TITLE
Crash 3.7.3 in Firm 9.0.1

### ISSUE THREAD

**Issue by neotic82** [FlagBrew/Checkpoint#286]
**Describe the bug**
The rest of homebrew in SD Card work correctly, but when I open checkpoint from hbmenu, I get this error

**Screenshots**
![13992a9e-1fd4-40cb-abff-b1af3d161606](https://user-images.githubusercontent.com/7745739/70029556-ab8ba980-15a7-11ea-96b3-a31472e4cfaf.jpg)

**Switch:**
- Entrypoint: Kosmos (14.2) -> Atmosphere
- System version: 9.0.1
- Checkpoint version: 3.7.3
- SD Card Filesystem: exFat
- Result code (if available): 2168-002

**Comment by GriffinG1** [comment]
Use fat32. The switch has a terrible exFat driver

**Comment by neotic82** [comment]
> Use fat32. The switch has a terrible exFat driver

And how do I do later to copy the games that occupy more than 4 GB?

**Comment by BernardoGiordano** [comment]
Are you sure you're running version 3.7.3?

**Comment by neotic82** [comment]
> Are you sure you're running version 3.7.3?

Sure :) 

https://github.com/FlagBrew/Checkpoint/releases/download/v3.7.3/Checkpoint.nro

**Comment by BernardoGiordano** [comment]
Can you send `sdmc:/switch/Checkpoint/checkpoint.log` here?

**Comment by neotic82** [comment]
> Can you send `sdmc:/switch/Checkpoint/checkpoint.log` here?

Tonight I look at the content of the file

**Comment by neotic82** [comment]
> Can you send `sdmc:/switch/Checkpoint/checkpoint.log` here?

Do not create any files checkpoint.log. 
Only config.json and saves folder

and the content of config.josn is:

{
  "additional_save_folders": {},
  "favorites": [],
  "filter": [],
  "ftp-enabled": false,
  "pksm-bridge": false,
  "version": 4
}

**Comment by neotic82** [comment]
When I return home I will see why I believe that the hbmenu is running in applet mode and I have seen that there are errors.

I have fewer and fewer options :(

**Comment by neotic82** [comment]
SOLVED!!!!

The problem came from the fact that I had not installed any games in the emmunand ¬ ¬
