### ISSUE TITLE
Issue with cheats

### ISSUE THREAD

**Issue by gitlevia** [FlagBrew/Checkpoint#287]
works fine but the only issue for me are the cheats i cant seem to get it to work or to registet i can click it shows x icon beside asks me if i want to save clicked yes go back to cheats nothing happened im on sxos btw thank you

**Comment by muxi1** [comment]
The same problem exists for me under ATM v0.10.0

**Comment by BernardoGiordano** [comment]
A small update needs to be released to restore compatibility with ams 0.10.0
