### ISSUE TITLE
Error trying to backup saves

### ISSUE THREAD

**Issue by weirdmario** [FlagBrew/Checkpoint#288]
using the latest version, i attempted to backup some saves and they instantly gave me the following error: Error: 0x0 Operation aborted by the user. 
I did not abort anything.

**To Reproduce**
1. Go to the Homebrew menu under Albums
2. Click on Checkpoint
3. Scroll down to any game you want to backup the save and try to back it up

**Expected behavior**
I expect it to work properly and backup whatever game i want.

**Switch:**
- Entrypoint: Album, then Homebrew 
- System version: 9.0.1
- Checkpoint version: 3.7.3
- SD Card Filesystem: Fat32
- Result code (if available): 0x0, maybe

**Additional context**
PS: I also selected cheats, by pressing down on the right control stick and that gave me an error that i had to restart my Switch.

**Comment by piepie62** [comment]
See #286, #282, #281, #280, #277, #275, #272, #268, #264, ...
