### ISSUE TITLE
There's no sprites.h

### ISSUE THREAD

**Issue by KironDevCoder** [FlagBrew/Checkpoint#289]
**Describe the bug**
The header file gui.hpp requires a sprites.h header file which I couldn't find in the repository

**To Reproduce**
1. Download a clone (https://github.com/FlagBrew/Checkpoint/archive/master.zip)
2. Try to build it
3. Get an error for it not finding a sprites. h

**Expected behavior**
The repository to have a sprites.h header file.

**Screenshots**
Don't have any :/

**Additional context**
It also gives me so many more errors....

**Comment by piepie62** [comment]
That should be created as part of the build process. What are you using to try to build Checkpoint?

**Comment by KironDevCoder** [comment]
VSCode, but that shouldn't be big of a deal since it just runs the make command

**Comment by BernardoGiordano** [comment]
Not the reply I was waiting for, but it seems you're missing tex3ds. Please make sure your development environment is properly setup, since sprites.h is generated at compile time

**Comment by KironDevCoder** [comment]
I installed tex3ds, now I get this error
```
sprites.t3s
sprites.t3x
Multiple inputs only supported with atlas mode
```

**Comment by BernardoGiordano** [comment]
Delete that .t3x file you generated
