### ISSUE TITLE
[Feature Request] Create and restore zipped save files

### ISSUE THREAD

**Issue by silvershadowkat** [FlagBrew/Checkpoint#293]
**Is your feature request related to a problem? Please describe.**
It would save some time if i can create zipped save files as well as restore zipped save files.

**Describe the solution you'd like**
Would be nice if i can press a button or choose an option to backup a save and compress it (but not create an additional folder inside the zip)
Good: save.zip/save file contents
Bad: size.zip/**save**/save file contents

Would be also nice if i can restore those same zips that i create directly on the system, without needing to uncompress them first with a computer.

**Describe alternatives you've considered**
Right now, i always have to zip them on a computer, and then unzip them when im ready to use them.

**Additional context**
1 zip file with the save contents i feel is much better to manage than a folder with lots of files inside.

**Comment by GriffinG1** [comment]
This seems like it would only be useful to a small number of users.

**Comment by BernardoGiordano** [comment]
#147 duplicate
