### ISSUE TITLE
crash when starting cheats on the switch

### ISSUE THREAD

**Issue by kenjiro22** [FlagBrew/Checkpoint#294]
![IMG_20191216_161130](https://user-images.githubusercontent.com/58914138/70918163-f503dc00-201e-11ea-966f-746e04ca431b.jpg)

**Describe the bug**
I enter hbmenu (applet mode) start checkpoint I click on any game I open the cheats window and crashed, but go press r+game in checkpoint have a crash game 
**To Reproduce**
1. Go to 'checkpoint'
2. Click on 'press r3 for open cheat window any games' (applet mode)
3. Crash

**Switch:**
- Entrypoint:( hekate - CTCaer 5.1.1 + Atmosphere 0.10.1
- System version: fw 9,0.1(emummc 9.0.1)
- Checkpoint version: 3.7.4
- SD Card Filesystem: Fat32
- Result code (if available):

**Comment by quartypies** [comment]
I also get the same issue.

**Comment by Falld0wn18** [comment]
I have the same problem when using cheat on new 2ds.

**Comment by whitetigerx8** [comment]
Similar issue on the switch, but it just says "The software was closed because an error occurred" and sends me back to the home screen. I have the same setup as kenjiro22.

**Comment by Ninjistix** [comment]
applet mode crashes both 

Atmosphere
- Entrypoint: hekate
- System version: 9.1.0 (Atmosphere 10.2)
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32
- Result code (if available): 2168-0001 (0x2a8)

SX OS
- Entrypoint: sxloader
- System version: 9.1.0 (sxos 2.9.3 beta)
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32
- Result code (if available): 2168-0001


Title override mode just says "The software was closed because an error occurred"

**Comment by Philipp-94** [comment]
I second this. Hopefully someone can point out to what we are doing wrong as it seems to work for many other.

**Comment by kacciocciacciara** [comment]
Same for me.
System 9.0.0
Atmosphere 10.0.2
Checkpoint 3.7.4

**Comment by elephantdino** [comment]
it worked initially for me. then It crashed one day trying to enable cheats. ever since, it keeps crashing after presssing r3. tried deleting everything is sd except emmu and nintendo folder. still happening..

**Comment by greensad** [comment]
Entrypoint: hekate
    System version: 9.1.0 (Atmosphere 10.2)
    Checkpoint version: 3.7.4
    SD Card Filesystem: FAT32
    Result code (if available): Applet- 2168-001(0x2a8) Title Override - none/"The software was closed because an error occurred"

**Comment by gonzolitzgerald** [comment]
I’m having the same issue, it has worked before but today just started crashing every time I press r3, everything is the same as above except for that I’m using Exfat.

Applet mode: 2168-0001 (0x2a8)
Override mode says the software was closed because of error.

**Comment by GriffinG1** [comment]
@gonzolitzgerald switch to fat32 and try again, the switch’s exfat implementation is terrible.

**Comment by gonzolitzgerald** [comment]
I’m hoping the only solution isn’t to switch to fat32, I waited a month to have my touch screen fixed so I could use Choidujornx to install exfat update. Plus I have 200gb of games. Checkpoint isn’t worth it.

**Comment by deadair3210** [comment]
It's not just checkpoint though, it's any Homebrew, and even some games. Ninty's exfat implementation is borderline dangerous to your data,as it can corrupt extremely easily

**Comment by gonzolitzgerald** [comment]
I only have a Mac so it’s been a pain to keep getting free trials of virtual machines and windows 10, and they don’t run well on my Mac. I would use fat32 if I just had an easy way of putting large nsp’s on my sd card with a program for Mac.

**Comment by deadair3210** [comment]
Multiple apps come up just by searching split nsp Mac, and even more if you feel like dealing with python

**Comment by aisync** [comment]
Any updates with this? I have the same issue. But I'm able to run it perfectly fine if I use fusee-primary as the payload.

**Comment by gonzolitzgerald** [comment]
I formatted to fat32 and am still having the same issue.

**Comment by BernardoGiordano** [comment]
> I formatted to fat32 and am still having the same issue.

can you send a zip of your `atmosphere` folder?

**Comment by neurodo** [comment]
im formatted in fat32 but same issue as well i can make backups and restore but if i open cheat menu in applet or full ram it crashes, one like seen above or in full ram it says unexpected error, i tried deleting content folder with all the cheats since in my case the cheats were automatically being applied to ffx and cuphead

**Comment by BernardoGiordano** [comment]
@gonzolitzgerald @neurodo can you send a zip of your `atmosphere` folder?

**Comment by RahilSagarwala** [comment]
I just encountered this issue on Atmosphere 0.10.5. Upon toggling the cheat menu for any game, Checkpoint would crash and say that the software closed due to an error. I found a fix for this bug. Create a save backup for any game. Now the cheat menu should work. This did not seem to happen on previous versions of Atmosphere.

**Comment by neurodo** [comment]
> @gonzolitzgerald @neurodo can you send a zip of your `atmosphere` folder?

I was able to fix my issue don’t know how I just did a random restore of lets go Eevee and I was able to open cheat menu without crashing or hitting unknown error

**Comment by gonzolitzgerald** [comment]
[atmosphere.zip](https://github.com/FlagBrew/Checkpoint/files/4397010/atmosphere.zip)

**Comment by gonzolitzgerald** [comment]
[atmosphere.zip](https://github.com/FlagBrew/Checkpoint/files/4397067/atmosphere.zip)

**Comment by rubensk8er** [comment]
Im having this error too with some homebrees like awoo withouth entering on applet mode or gold leaf picking om the menu updates, it happened after i paste salty nx and some cheats dont knlw what happened is there an answer same error

**Comment by GriffinG1** [comment]
This should've been fixed in v3.8.0. If it isn't, feel free to let me know and I'll reopen this.
