### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by LazyEnot** [FlagBrew/Checkpoint#296]
**Describe the bug**
Cannot exit from Checkpoint

**To Reproduce**
1. Open HBL in title mode 
2. Open Checkpoint
3. (Do anything)
4. Exit checkpoint

**Expected behavior**
Checkpoint closes, HBL opens

**Real behavior**
Checkpoint doesn't close

**Switch:**
- System version: 9.0.1 (Atmosphere 0.10.0)
- Checkpoint version: 3.7.3
- SD Card Filesystem: exFAT

**Comment by BernardoGiordano** [comment]
Unable to reproduce. Will reopen this if it still happens under 3.7.4+

**Comment by LazyEnot** [comment]
@BernardoGiordano there are no Exit button in Checkpoint for go back to homebrew menu. Please, add it.
I cant exit from app, only close it and run hb menu again.

**Comment by BernardoGiordano** [comment]
Press the cross button to quit Checkpoint.

**Comment by LazyEnot** [comment]
That worked (for +, not x). Then, I think, you should add that information to help (which shows when pressing -)
