### ISSUE TITLE
Keyboard can't be found by Checkpoint 3.7.4

### ISSUE THREAD

**Issue by druidasse** [FlagBrew/Checkpoint#298]
I use sx os 2.9.3 with FW 9.1. 

I have installed checkpoint 3.7.4 and backed up some games. It didn't ask where i wanted to save because it could not access to the keyboard, so it saved it at the root of the sd card, in the default folder "checkpoint". 

Now i want to restore these, as I have reinit the sd card, but i can't because it still can't access the keyboard...

**Comment by GriffinG1** [comment]
You don't need the keyboard to restore...

Also, SXOS isn't supported. Use Atmosphere's title takeover.

**Comment by BernardoGiordano** [comment]
The issue you're describing is incorrect, since there is none. No backups are saved in a default folder "checkpoint". In order to be able to use the keyboard, please use a CFW that allows you to use the title takeover feature.

Also, restoring save backups has nothing to do with the keyboard.

**Comment by druidasse** [comment]
I have installed checkpoint myself and performed these operations myself. Also, before i posted this i could see in the release notes that you changed the management of the keyboard to use the system keyboard and I believe this could be linked.

Tell me where i can upload a video for you and you'll see by yourself. Or tell me how to send logs maybe???

**Comment by GriffinG1** [comment]
Switch to Atmosphere and use it’s title takeover feature. That will let you use the keyboard.

You do not need the keyboard to select a save.

Bernardo wrote Checkpoint, I think he knows a bit better on how Checkpoint saves when it can’t use the keyboard. Your problem is nonexistent.

**Comment by druidasse** [comment]
Ok, fine. I am using sx os because i was unsuccessful at configure atmosphere on it. I'll check with the sx os team then. Thanks for your support.

**Comment by druidasse** [comment]
Ok, so i found out how to use the title takeover feature on sx os. Thanks for the hint. 

So where are the games checkpoints saved on the sd card then?

**Comment by GriffinG1** [comment]
[Hmm if only that information was documented somewhere on this repo...](https://github.com/FlagBrew/Checkpoint/blob/master/README.md#working-path)

**Comment by druidasse** [comment]
Sorry, I had missed that. Thanks for your help.
