### ISSUE TITLE
Bug Report  Can't show save after I delete serial number

### ISSUE THREAD

**Issue by Meiliaodasi** [FlagBrew/Checkpoint#300]
**Describe the bug**
My virtual system is SX OS 2.9.3 and checkpoint is useful.I delete my virtual system serial number, other save data can't show,and previous data can't modify.Then I new an account,and find that is also not working.

**Switch:**
- Entrypoint:
- System version:SX OS 2.9.3 
- Checkpoint version:3.7.4
- SD Card Filesystem: FAT32
- Result code (if available):

**Comment by GriffinG1** [comment]
Support is not guaranteed for SXOS. Switch to Atmosphere and see if you can reproduce.

**Comment by BernardoGiordano** [comment]
You need to start games at least once if you formatted your system. If the issue is still there, this will be reopened.

**Comment by Meiliaodasi** [comment]
> You need to start games at least once if you formatted your system. If the issue is still there, this will be reopened.

I have started several games,the issue is still exist
