### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SekiTimewalker** [FlagBrew/Checkpoint#301]
**Describe the bug**
Pokémon Crystal is not showing up on Checkpoint. It is a legit copy bought from the e-shop. 

**Expected behavior**
Expected behavior is to include Crystal to be able to backup.

**3DS:**
- Entrypoint: Luma
- System version: 11.13.0-45u
- Checkpoint version: 3.7.3
- Result code (if available): None

**Comment by BernardoGiordano** [comment]
Unable to reproduce. Please refresh your title list holding B.
