### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by rock20xx** [FlagBrew/Checkpoint#302]
I only use my switch for one thing and that's to edit pokemon. 

 When beginning the process to edit through pkhex  I tried to backup my save file, before I take the SD card out and place it Into the comp. For use work pkhex.

 When I go into to checkpoint  It shows that I currently have 57 minutes of gameplay.  I have an hour and 7 minutes of gameplay that is not being backed up. 
 I hit L to backup it says that it saves it but nothing happens when I take the memory card out and put it into the computer to use PK hex that's a file is nowhere to be found

 I have re hacked my switch 3 times following  The exact same instructions to the t.

It all began with the new update for pkmn sword and sheild
(Expansion pk)

I am using the all most updated stuff.. programs etc.

**Comment by BernardoGiordano** [comment]
Please open another issue where you follow the template and perfectly describe what's going on. This should be a matter of user error and not fault of Checkpoint.
