### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by TrahsPanda** [FlagBrew/Checkpoint#306]
100% Shiny Cheat for Pokemon X not working.

**To Reproduce**
1. Activate the cheat via Rosalina Menu.
2. Select + L to enable it.
3. Get into a wild battle.
4. Crashes.
5. Sometimes it crashes before wild battle too.

**Expected behavior**
It is supposed to make all wild Pokemon Encounters shiny.

**3DS:**
- Entrypoint: B9S 1.3 Luma 10.0.1
- System version: 11.13.0-45U
- Checkpoint version: 3.7.4
- Result code (if available): In Attached File.
[crash_dump_00000003.zip](https://github.com/FlagBrew/Checkpoint/files/4081946/crash_dump_00000003.zip)

**Comment by BernardoGiordano** [comment]
Please report the cheat as broken on [Sharkive's repo](https://github.com/FlagBrew/Sharkive)
