### ISSUE TITLE
Arm 11 crash Checkpoint 3.7.4

### ISSUE THREAD

**Issue by gunnarwish** [FlagBrew/Checkpoint#310]
**Describe the bug**

**To Reproduce**
1. Go to 'Open checkpoint'
2 'When i try to close it. The program won't respond immediately. 
3.Then when i get the option to close the program and close it.
4. ARM11 crash

**Expected behavior**
 Close without crash

**Screenshots**
(https://github.com/FlagBrew/Checkpoint/files/4094611/crash_dump_00000003.zip)

**3DS:**
- Entrypoint: B9S 1.3 Luma 10.0.1
 -System version: 11.13.0-45E
- Checkpoint version:3.7.4
- Result code (if [available):

Additional context
I tried to reinstall Checkpoint with a completely new Checkpoint map but the error still happens.

**Comment by BernardoGiordano** [comment]
#299 duplicate.
