### ISSUE TITLE
Cheats.txt only contains "404: Not Found"

### ISSUE THREAD

**Issue by JonArbuckle48** [FlagBrew/Checkpoint#311]
**Describe the bug**
When activating cheats for any game, installed to sd or from a physical cart, the cheats.txt only says "404: Not Found"

**To Reproduce**
1. Open Checkpoint
2. Activate cheats for a game
3. Go to the game and press the luma menu button combo
4. Select "cheats" and see the message "no cheats for title xxxxxxxxx"

**Expected behavior**
For cheats.txt to contain what is in the database

**3DS:**
- Entrypoint: Not sure what this means, I'm using the latest Luma release and I used the Steelhax method for softmodding
- System version: 11.13.0-45U
- Checkpoint version: 3.7.4
- Result code (if available):

**Switch:**
- Entrypoint:
- System version:
- Checkpoint version:
- SD Card Filesystem:
- Result code (if available):

**Additional context**
It works if I go to the database and copy/paste the cheats into the txt file

**Comment by BernardoGiordano** [comment]
Can you send the contents of your `/luma` and your `/cheats` folder?

**Comment by JonArbuckle48** [comment]
Checkpoint crashed when I opened it soon after posting, and now it's working correctly, maybe because  I renamed my "cheats" folder to "notcheats" to troubleshoot, but I can't be sure 
The crash dump is in here too
[LumaAndCheats.zip](https://github.com/FlagBrew/Checkpoint/files/4096661/LumaAndCheats.zip)

**Comment by BernardoGiordano** [comment]
I see you have lots of folders under the title folder that are from Luma as the main source of cheats. You should just delete them and let Luma only search into the secondary folder, which is the one checkpoint works, with, namely `cheats`.
