### ISSUE TITLE
Checkpoint hangs when trying to switch users

### ISSUE THREAD

**Issue by antib0t** [FlagBrew/Checkpoint#312]
**Describe the bug**
Checkpoint hangs when trying to switch users. Using SXOS 2.9.3 Emunand

**To Reproduce**
1. Navigate to Pictures
2. Navigate to homebrews
3. Open Checkpoint 3.7.4
4. Switch user by clicking LZ

**Expected behavior**
User switched after 3-5 min.

**Actual result**
App hangs with possibility to exit by HOME button

**Switch:**
- Entrypoint: from homebrews checkpoint folder
- System version: SX OS 2.9.3 Emunand
- Checkpoint version: 3.7.4
- SD Card Filesystem: exFAT
- Result code (if available):

**Additional context**

**Comment by GriffinG1** [comment]
SXOS is trash and not supported. Use Atmosphere with title takeover.

**Comment by antib0t** [comment]
solved by running app not in applet mode
