### ISSUE TITLE
Bug Report, It doesn't work no matter what

### ISSUE THREAD

**Issue by Whynotboi** [FlagBrew/Checkpoint#315]
**Describe the bug**

**To Reproduce**
1. Go to 'Mario & Luigi Bowser's Inside Story + Bowser Jr's Journey'
2. Press 'Luma3ds Menu Combo'
3. Scroll down to 'Cheats'
4. Select 'any cheat'
5. Exit Luma Menu

**Expected behavior**
The game crashes, causing this exact info to be said:
**An Exception has Occured**
_Arm11 (core 0)
Data abort
Translation-Section
Remillio (00040000001d1400)
After all the code it also says:
Access type: Read_

**Screenshots**
I would give you a screenshot, but I don't have a sd with a micro SD slot currently...

**2DS XL:**

**Additional context**
I seriously don't understand, it is not working and I need some help
I tried cheats on Sonic Generations and it worked, I backed up save data and redownloaded the title, I tried seeing if I renamed the stored cheat file to the update ticket for it and it still didn't work... I searched everywhere for an answer for this but no one seems to have this same problem...

**Comment by GriffinG1** [comment]
Please do not create multiple issues on multiple repos. You had the correct location the first time, at [Sharkive/199](https://github.com/FlagBrew/Sharkive/issues/199). Please close this issue, and reopen that one.
