### ISSUE TITLE
Changing title of a file

### ISSUE THREAD

**Issue by mokkamenn** [FlagBrew/Checkpoint#316]
When i changed the name of the folder with all my pokemon shield saves, i couldn't acess the saves anymore.

**Comment by GriffinG1** [comment]
Ok? This isn't a bug. Checkpoint relies on the game folder to be what it names it, not what you name it. Change it back (you can regenerate it by making a new backup).

**Comment by mokkamenn** [comment]
I found out of the name of the folder, i was just plain stupid right there. Of course cant checkpoint reconginse the folder. well thanks for help
