### ISSUE TITLE
Cannot use cheats after updating other apps

### ISSUE THREAD

**Issue by HolyRabbid** [FlagBrew/Checkpoint#321]
After updating KOSMOS on my Switch, I tried using cheats twice through Checkpoint and the system crashed. No big deal, third time was the charm, I just passed it off as a bug. I then saw that version 3.7.4 was released and decided to update the app through the Homebrew store. Now, every time I try to access cheats for any game, Checkpoint crashes and either Atmosphere for the Switch gives me a crash screen, forcing me to quit out of Checkpoint and go back to the main menu (Switch crash screen) or reset the console to RCM and reinject the payload (Atmosphere crash screen.) 

1. With Checkpoint installed at rev 3.7.3 or lower, go to the Homebrew Store
2. Update Checkpoint through the store, then open it up. 
3. Select any game and press R3 to access cheats
4. The system will crash with one of two error messages depending on which catches it, Atmosphere or the Switch itself. 

I knew from this page that files were now looked at from the contents folder and not titles, but pressing R3 shouldn't make it crash every time. 

**Switch:**
- Entrypoint: Opening the Homebrew Menu via R1 while loading Super Mario Maker 2
- System version: 9.1.0
- Checkpoint version: 3.7.4 (3.7.3 prev)
- SD Card Filesystem: FAT32

It was my understanding that, since I only updated KOSMOS and never used it, that it would not affect anything else on the console. The problems did not start outright until after KOSMOS was updated. However, the cheats didn't fail completely until after downloading and updating Checkpoint through the homebrew store app.

**Comment by GriffinG1** [comment]
This should've been fixed in v3.8.0. If it isn't, feel free to let me know and I'll reopen this.
