### ISSUE TITLE
Certain Applications Not Appearing (2DS)

### ISSUE THREAD

**Issue by ShadowNMSS** [FlagBrew/Checkpoint#322]
When I use Checkpoint on my New 2DS some apps won't appear.

I dumped my copies of Pokemon Y, Alpha Sapphire and Ultra Moon and once reinstalled digitally, only Pokemon Y appears in Checkpoint. I have save files in Ultra Moon and Alpha Sapphire but they won't show up. Pokemon Y works flawlessly but was installed the exact same way as the others.

I'm on the latest versions of Checkpoint and 3DS software (Europe).

**Comment by Originalimoc** [comment]
Same, some games not showing up.

**Comment by LeonardoLimaMH** [comment]
Same here, but using Old 3DS XL

**Comment by GriffinG1** [comment]
Checkpoint doesn't rescan on successive launches, to save boot time. Try holding `B`.

**Comment by Originalimoc** [comment]
> Checkpoint doesn't rescan on successive launches, to save boot time. Try holding `B`.

This should be included in "select” command hints.

**Comment by Originalimoc** [comment]
> Checkpoint doesn't rescan on successive launches, to save boot time. Try holding `B`.

And no, this doesn’t solve the issue.

**Comment by GriffinG1** [comment]
![image](https://user-images.githubusercontent.com/28538707/77027865-f1a12900-695c-11ea-8d8e-8af023782bf0.png)



> > Checkpoint doesn't rescan on successive launches, to save boot time. Try holding `B`.
> 
> This should be included in "select” command hints.

This has been requested numerous times, and will probably be added when the next update is ready.

**Comment by Originalimoc** [comment]
> ![image](https://user-images.githubusercontent.com/28538707/77027865-f1a12900-695c-11ea-8d8e-8af023782bf0.png)
> 
> > > Checkpoint doesn't rescan on successive launches, to save boot time. Try holding `B`.
> > 
> > 
> > This should be included in "select” command hints.
> 
> This has been requested numerous times, and will probably be added when the next update is ready.

There is an ongoing save. Not in ExtData either.

PS. One of the missing title(s) is Professor Layton and the Miracle Mask.

**Comment by marfi01** [comment]
I also had the same problem.
First you need to create a save inside the game, without this step Checkpoint may not detect the game.
After that, if it still cannot detect it, you must hold down B.
The game should now be seen. I hope I have been clear!

**Comment by GriffinG1** [comment]
@marfi01 both of those points are already covered in my message.

**Comment by marfi01** [comment]
ok sorry, i didn't understand :,)
