### ISSUE TITLE
SX OS Unsupported warning on README

### ISSUE THREAD

**Issue by jmhg92** [FlagBrew/Checkpoint#323]
**Is your feature request related to a problem? Please describe.**
I ran into a problem about the keyboard not showing up and when I found the closed issue about it I read the following:

> Also, SXOS isn't supported. Use Atmosphere's title takeover

I went on to look at other issues with SX OS and the same thing was being said about not supporting it:

#264 #275 #298 #300 #312 

I have read through the README and there is no mention about not using SX OS or any reason as to why it isn't supported.

**Describe the solution you'd like**
Put a warning on the README that states that SX OS is not supported and to use alternative CFWs instead (like Atmosphere). This way users of SX OS are clear that this application could possibly not work as expected and maybe think about not filing an issue when the answer will be that it "isn't supported".

EDIT
----

Another way to look at this could also be to put a **Supported/Tested Nintendo Switch CFWs** instead to let users know which CFWs this tool has been tested on.

**Comment by GriffinG1** [comment]
I get the feeling that the people opening those kinds of issues will not be reading the readme, either.

**Comment by jmhg92** [comment]
Doesn't hurt to try

**Comment by ELY3M** [comment]
This need to be done.  I encourage people to switch to atmosphere if they are having issues on sxos.  I have got about 10 to 15 people to switch to atmosphere.

**Comment by GriffinG1** [comment]
> EDIT
> Another way to look at this could also be to put a Supported/Tested Nintendo Switch CFWs instead to let users know which CFWs this tool has been tested on.

Just wanted to reply to this quickly; no CFW except Atmosphere is officially supported. None. Also, in regards to this:
> or any reason as to why it isn't supported.

There’s a few reasons. First and foremost, SXOS has stolen code from Atmosphere in it, violating Atmosphere’s copyleft license. In addition, they have some of _Nintendo’s_ code in it, violating their copyright. The other “big” reason SXOS isn't supported is, it’s primarily a piracy tool.

**Comment by ELY3M** [comment]
worst day I have is that someone paid other person to do cfw install.  the installer did sxos install on his switch.  the switch owner only wanted to do pkhex stuff.  this anger me so much.   this person also have trouble with checkpoint.

**Comment by rsn8887** [comment]
If the keyboard doesn’t show up for your friend, I suspect it is not a SX OS problem. It probably just means they started the app wrong. Always hold R over a GAME to start the app, never use ALBUM to start any homebrew app. This is true for both Atmosphere and SX OS and happens with all apps that use the on screen keyboard AFAIK.

**Comment by piepie62** [comment]
This issue is getting off topic, so I'm going to lock it. That said, last time I checked SX OS removed normal title takeover, always starting homebrew in applet mode.
