### ISSUE TITLE
Animal Crossing New Horizon not displayed

### ISSUE THREAD

**Issue by iaxx** [FlagBrew/Checkpoint#326]
**Describe the bug**
Animal Crossing New Horizon is not on the list of games in Checkpoint despite being installed on the SD Card. 

**To Reproduce**
1. Install AC
2. Play the game until it allows you to save
3. Quit the game and check Checkpoint

**Expected behavior**
The game should be displaying on there.

**Screenshots**
Not necessary.

**Switch:**
- Entrypoint: I'm too dumb to know what this is referring to
- System version: 9.2.0 with AMS on 0.10.4
- Checkpoint version: 3.7.4 
- SD Card Filesystem: FAT32

**Comment by BernardoGiordano** [comment]
#324 duplicate.
