### ISSUE TITLE
Bug Report | Unable to use buttons on Switch NRO

### ISSUE THREAD

**Issue by Alexowo** [FlagBrew/Checkpoint#327]
**Describe the bug**
I've noticed this with other Switch homebrew as well, notably goldleaf (v0.5), and nxmtp. It just suddenly started happening (before this, they worked fine) but some homebrew nros don't accept button presses at all. I don't know why this is, but it's very important with Checkpoint, judging how at the moment I can't scroll down to the next page of titles to dump the save I want (Animal Crossing: New Horizons).

**To Reproduce**
I literally know nothing about what caused this to happen so I can't really record the steps to reproduce. It does affect other homebrew apps as I said and sometimes affects functionality of them.
**Expected behavior**
Checkpoint should've worked normally, allowing me to use the buttons on the joycons to navigate through the menu and choose the title for the save I want to dump.

**Switch:**
- Entrypoint:
- System version: 9.1.0 (I think)
- Checkpoint version: 3.6.0
- SD Card Filesystem: FAT32
- Result code (if available):

I will test to see if the problem persists on a newer version, and if it does, I'll update the issue with more information. Thanks.

**Comment by GriffinG1** [comment]
You won't be able to use Animal Crossing yet anyways (see #324). In addition, please do not report a bug unless you are using the latest version of Checkpoint. Finally, please do not leave the entrypoint space empty, as that is important for debugging as well.

**Comment by BernardoGiordano** [comment]
You just need to update Checkpoint to get buttons working again. You're running an old build that is not fully compatible with your system version.
