### ISSUE TITLE
Bug Report Cant back up animal crossing new horizon

### ISSUE THREAD

**Issue by CommicKick69ing** [FlagBrew/Checkpoint#328]
**Describe the bug**
The game does not appear on the menu even though my other games do

**To Reproduce**
1. Go to 'checkpoint'
2. Scroll around 'dont see the game'

**Expected behavior**
you see the game, you select the title, you backup your save

**Switch:**
- Entrypoint: dont know
- System version: 9.1.0
- Checkpoint version: 3.7.4
- SD Card Filesystem: 128 gb
- Result code (if available): none

**Comment by GriffinG1** [comment]
#324 duplicate
