### ISSUE TITLE
Bug Report - Back up save file size is very small for the game.

### ISSUE THREAD

**Issue by hotducksoup** [FlagBrew/Checkpoint#329]
**Describe the bug**
Game: Stardew Valley
Game Version 1.4
File size seems to be 106kb? when I use checkpoint to back up the game save. I checked an older backup and it would hover around 2.5MB. But ever since stardew valley updated to 1.4 I only seem to get backup save files of 106KB.

**To Reproduce**
1) Boot SX Pro 
2) Homebrew Apps
3) Open Checkpoint (v3.7.4)
4) Select Stardew Valley
5) Backup Save File
6) Look at backup save file using FTP (transferred to desktop)

**Expected behavior**
The backup save file should be around 2MB however I only see 106KB. When I try to inject this save file to another switch (same OS version, same Checkpoint version, and same game version. The game reboots into the title screen.) This does not occur if I use an older save and only occurs using backup saves after game version 1.4 (stardew valley)

**Screenshots**
![filesize](https://user-images.githubusercontent.com/62483057/77235369-3b169180-6b72-11ea-9bda-faa37abade30.png)

**Switch:**
- Entrypoint: SX PRO
- System version: 9.1.0
- Checkpoint version: 3.74
- SD Card Filesystem: FAT 32
- Result code (if available):

**Additional context**
none that I can think of.

**Comment by GriffinG1** [comment]
Please properly fill out the issue template.

**Comment by hotducksoup** [comment]
> Please properly fill out the issue template.

updated per request.

**Comment by GriffinG1** [comment]
And there's the first issue. There is no guaranteed support for any CFW outside of Luma for the 3DS, and Atmosphere for the switch. If it happens to works on others, then great! Otherwise, switch to Atmosphere, as we will not provide any help with alternative CFW, especially SXOS.

**Comment by hotducksoup** [comment]
> And there's the first issue. There is no guaranteed support for any CFW outside of Luma for the 3DS, and Atmosphere for the switch. If it happens to works on others, then great! Otherwise, switch to Atmosphere, as we will not provide any help with alternative CFW, especially SXOS.

Thank you for the prompt replies. I'll have to do some changing then. Have a good day and stay safe.
