### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by armon222** [FlagBrew/Checkpoint#331]
I am on both the latest version of switch firmware as well as checkpoint, but for some reason, ACNH does not show up in checkpoint.

**Comment by piepie62** [comment]
Duplicate of #324

**Comment by armon222** [comment]
wait no, i am not requesting a feature. I am saying that ACNH is not even showing up in checkpoint for me.

**Comment by piepie62** [comment]
It's the same problem. The issue is that the save type is not yet supported

**Comment by armon222** [comment]
Oh ok, thank you I was unaware of this
