### ISSUE TITLE
Some games aren't showing up

### ISSUE THREAD

**Issue by connorgavin7502** [FlagBrew/Checkpoint#332]
I downloaded Animal Crossing New Leaf and have played to the point of saving. I can view the save data for the game in FBI, as well as copy it to another location on the SD card as a manual backup system, since the game won't show up in Checkpoint.

**Comment by BernardoGiordano** [comment]
Hold B to refresh your title list in checkpoint.

**Comment by connorgavin7502** [comment]
Oh wow cool ok, I had no clue that was a functionality. Thanks

**Comment by Nephiel** [comment]
I didn't know about the 'hold B to refresh title list' feature either. Maybe it should be described among the on-screen commands that appear by holding Select?

**Comment by connorgavin7502** [comment]
I agree. It's is a very helpful feature in some cases
