### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by N1k17** [FlagBrew/Checkpoint#335]
New 3DS: Latest version of sys and checkpoint. One of my software doesn't show up in the menu the software is INAZUMA ELEVEN GO GALAXY BIG BANG

**Comment by GriffinG1** [comment]
![DCA1D7DA-ED88-4BC6-8BEA-07AFA8905286](https://user-images.githubusercontent.com/28538707/78279343-9cc0ef00-74d4-11ea-8133-f797bcb64aa5.jpeg)
