### ISSUE TITLE
Bug Report cant start Checkpoint in Atmosphere 0.10.5 Tinfoil Fork

### ISSUE THREAD

**Issue by StiefelHD** [FlagBrew/Checkpoint#336]
Hello I am using the Atmosphere Tinfoil fork and have not been able to start the checkpoint since then Atmosphere immediately crashes when starting someone similar problems?

**Comment by StiefelHD** [comment]
The Fork: https://github.com/borntohonk/Atmosphere/releases

**Comment by piepie62** [comment]
Easy answer: don't use shitty forks that remove useful features and replace them with piracy-enabling ones.
