### ISSUE TITLE
Feature Request - Bring back old Atmosphere version compatibility

### ISSUE THREAD

**Issue by FellFromTheSky** [FlagBrew/Checkpoint#342]
**Is your feature request related to a problem? Please describe.**
Cheat path changed for Checkpoint 3.7.4+ for Atmosphere 0.11.1+ for Nintendo Switch.
This break the compatibility with older versions of Atmosphere.

**Describe the solution you'd like**
When Checkpoint boots, let the user select or not to rename the Checkpoint cheats path to the path it should be named. Or, create a small script that would detect firmware and Atmosphere version so cheat folder would be automatically renamed or not when Checkpoint boot. So it would bring back old firmware and Atmosphere compatibility.

**Comment by piepie62** [comment]
No cheat paths changed in Atmosphère 0.11.1, so I don't know what you're on about. Furthermore, there is no point in using outdated versions of software on purpose

**Comment by FellFromTheSky** [comment]
Oh ok, sorry. I misunderstood what you said in lastest update changelog.

**Comment by piepie62** [comment]
0.10.0 did, sure, but 0.11.1 did not. You should not be using outdated Atmosphère versions, though

**Comment by FellFromTheSky** [comment]
Yah, you're totally right, sorry :)
I'm using AMS 0.10.5 instead of 0.11.1 for backward compatibility with Switch firmware 9.2.0 ...
Why? Because AMS 0.11.1 has changed a lot in 0.11.1 and I want to let the time to it's developers to fix bugs, fix new features ...

**Comment by piepie62** [comment]
0.11.1 *is* the bug fix. It's backward compatible as well. 0.11.0 was the buggy version, which could be seen by the fact that it was a prerelease instead of a full release

**Comment by FellFromTheSky** [comment]
Ok, thank you so much for explanation about that.
No further answer needed :)
