### ISSUE TITLE
Instruction screen items overlap with PKSM bridge enabled

### ISSUE THREAD

**Issue by sarahlicity** [FlagBrew/Checkpoint#343]
**Describe the bug**
When the PKSM bridge is enabled, its entry in the "instructions" screen overlaps the previous instruction (Hold Y)

**To Reproduce**
1. Enable PKSM bridge and open Checkpoint
2. Press Select/– to open instructions.
**Expected behavior**
The instructions entries should not overlap.

**Screenshots**
![checkpoint instructions bug](https://user-images.githubusercontent.com/4795206/79700108-71d3ea80-828b-11ea-8a3f-33c7cd934415.jpg)

**Switch:**
- Entrypoint: Atmosphere (0.11.1)
- System version: 10.0.0
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32

**Comment by BernardoGiordano** [comment]
This should have been solved already in latest commits.
