### ISSUE TITLE
Bug Report - ERROR CODE 2162-0002 AT LAUNCH

### ISSUE THREAD

**Issue by Barenchi** [FlagBrew/Checkpoint#347]
**Describe the bug**
The software crashes at launch. Error code: 2162-0002.

**To Reproduce**
Just launch Checkpoint

**Expected behavior**
Let the software launch

**Screenshots**
https://zupimages.net/up/20/18/kqyz.jpg

**Switch:**
- Entrypoint: Atmosphere 0.12.0
- System version: 10.0.1
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32
- Result code (if available): SCREENSHOT

**Comment by BernardoGiordano** [comment]
Are you using applet mode or title takeover?

**Comment by Barenchi** [comment]
I try both of them, same error

**Comment by StiraGHB** [comment]
I am also having the same issue.

**Comment by beeGod** [comment]
This happens when you didn't launch any game yet. I suppose Checkpoint don't handles well when there's none save file in system. Just open a game and let it create the first save file and try again.

**Comment by PerryCodekies** [comment]
> This happens when you didn't launch any game yet. I suppose Checkpoint don't handles well when there's none save file in system. Just open a game and let it create the first save file and try again.

I am having the exact problem and confirmed this is the solution for me. Thanks!!!
