### ISSUE TITLE
[Feature Request] batch backup games

### ISSUE THREAD

**Issue by T0biasCZe** [FlagBrew/Checkpoint#348]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be usefull to add option to batch backup, either by selecting some games or backuping all games. It would save a lot of time, because now, if you want transfer a lot of titles, you need to select, and wait, select and wait... . With batch-backup, you could select which games to backup, and while its backuping, you could do other things

**Comment by piepie62** [comment]
"You could do other things" Like what? There already is a multi-backup mode; I believe the key to start selecting may be Y? If it's not Y, then just hold select to see instructions

**Comment by T0biasCZe** [comment]
OH
But there Is still missing batch restore

**Comment by GriffinG1** [comment]
Yes, and batch restore will never happen, as there's no way to know which backup to restore.

**Comment by GriffinG1** [comment]
See Bernardo's response to #169 for more info.
