### ISSUE TITLE
Bug Report - User Profiles Missing and Z buttons cause freeze

### ISSUE THREAD

**Issue by Elliander** [FlagBrew/Checkpoint#350]
**Describe the bug**
The user profile are absent and so only games for one profile can be backed up and restored. Because the profile selection is absent, pressing either Z button will freeze Checkpoint until the home button is pressed. Pressing - even has the user profiles omitted from the list.

**To Reproduce**
1. On a Nintendo Switch with more than one profile that has saved games, open Checkpoint.
2. Notice the lack of profiles 
3. Press either Z button.
4. Notice how it freezes until you press the home button.

**Expected behavior**
I would expect:

1.) to either see profiles to select or, lacking that, a list of all games for all users. 
2.) that all input will work without making the program unresponsive to further input.
3.) That every game played can be selected, backed up, and restored from any user to any user.

**Switch:**
- Entrypoint: SXOS 2.9.5 Beta
- System version: 9.0.2 and 10.0.2 (tested in both)
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32
- Result code (if available):

**Additional context**
When I downgraded to version 3.5.0 I was able to select user profiles again, and the Z buttons no longer froze Checkpoint, but I lost the ability to backup or restore every title for every user. There is a maximum of the first 20 games ever played (not the last 20) since that's the limit of what the one page will hold. Pressing - even has the L and R button for changing pages omitted from the list.

When I downgraded to 3.2.4 the touch screen worked to select profiles, but no other input worked. 

When I downgraded to 3.2.0 I was met with the old user interface I remember, and I could see the list of games with all profiles together, but no other input worked.

The main reason why I upgraded from a very old version was because on the latest Firmware controller input was unresponsive making it impossible to use, but since it's impossible to select the game I want to backup or restore there is currently no good fully working version of Checkpoint available to use for the Nintendo Switch which isn't good. I would be happy with the old UI and less features if the basic purpose - backup and restore of game saves - worked.

If there is a workaround for these bugs, aside from backing up and restoring the entire emuNAND (which is what I will be doing until Checkpoint works again) I'd love to hear it.

As a side note: For 3.7.4 and 3.5.0 if the Pro Controller is on, no input from the joycons or the touch screen will work.

**Comment by GriffinG1** [comment]
Sxos is unsupported, use atmosphere.

**Comment by BernardoGiordano** [comment]
Issue is within your cfw of choice, not Checkpoint.
