### ISSUE TITLE
Corrupted Save MK7

### ISSUE THREAD

**Issue by T0biasCZe** [FlagBrew/Checkpoint#351]
**Describe the bug**
Hi, i saved Mario Kart 7 save, and copied it to PC, and then my New 3DS. Data says corrupted, even when i deleted secure value in FBI. BUT, Citra loads the save without any problem

**To Reproduce**
1Download the save
2 put it on SD card in checkpoint folder
3 load it with checkpoint
4 delete secure value for both update and game in FBI
5 start MK7, it will say corrupted data
6 open citra on PC
7 right click the MK7 game, and click open save file, delete everything, and copy content in zip in "0x00307 MARIO KART 7" in "20200503-230231" there
8 start the game and the save will load normally

**expected**
Game to load without corrupted error

**Screenshots**

**3DS:**
- Entrypoint: 
- System version: Luma3DS v10.1.3
- Checkpoint version: 3,7,4
- Result code (if available): The save data is corrupted and will now be reset

**Additional context**
[0x00307 MARIO KART 7.zip](https://github.com/FlagBrew/Checkpoint/files/4593606/0x00307.MARIO.KART.7.zip)

**Comment by BernardoGiordano** [comment]
You're not supposed to delete the secure value manually. Also, make sure the file hasn't been corrupted during the copy on your 3DS

**Comment by T0biasCZe** [comment]
Somebody told me to delete it on Nintendo homebrew discord 3ds help Channel
¯\_(ツ)_/¯

**Comment by GriffinG1** [comment]
Closing, lies more in either user error as well as possibly corruption during file transfer.
