### ISSUE TITLE
Can't Restore Saves 

### ISSUE THREAD

**Issue by Jayinem** [FlagBrew/Checkpoint#352]
**Describe the bug**

**To Reproduce**
1. Make a new Backup
2. Click on the game and hit R to restore
3. The screen moves to the top of the page of games, instead of restoring
4. No Error

**Expected behavior**
When I hit restore I would think it would let me choose one of the restore points, instead of goes to the top of the screen of games, the game is towards the bottom. But it does the same for any game.

**Switch:**
- Entrypoint:Atmosphere or SXOS
- System version:10.02
- Checkpoint version:3.74
- SD Card Filesystem:FAT32
- Result code (if available):

Some of the time the Restore option is grayed out, even though there's two saves below new.

**Comment by piepie62** [comment]
You haven't selected the game with A before trying to restore.

**Comment by Jayinem** [comment]
Lol you were right that was dumb on my part. Close this.

**Comment by GriffinG1** [comment]
You are fully capable of closing your own issues.
