### ISSUE TITLE
Feature Request - Allow a way to refresh the game database if a new game card has been inserted

### ISSUE THREAD

**Issue by the16bitgamer** [FlagBrew/Checkpoint#356]
It's a bit frustrating when I am trying to migrate my save games from my Game Cards to my digital version of the same game, that I have to close the software when I insert a new game card. 

If you can, it would be nice to just have the software check the game cart when it's selected, or perhaps have a refresh button somewhere so when I put in a new game card I can backup that game

**Comment by GriffinG1** [comment]
This used to be supported, however it was not working properly, and as such was removed.

**Comment by BernardoGiordano** [comment]
You just hold B to refresh the entire game list.
