### ISSUE TITLE
Idiot's Guide

### ISSUE THREAD

**Issue by Swiftybar** [FlagBrew/Checkpoint#360]
Hi, sorry for being dense but I feel the need to ask.

I would like to use this to use the MHXX Switch Save Editor for my Switch but there are no current guides (the only ones I could find are 2+ years old) out there that explain how to get started on actually installing this on a Switch.

Can anyone signpost me to a current guide or post a quick idiot's guide here please?

I'm not really good with computers and I don't want to mess anything up by just 'having a go', sorry if this is frustrating.

**Comment by piepie62** [comment]
https://nh-server.github.io/switch-guide/ is one.

**Comment by Swiftybar** [comment]
According to the guide, my Switch is patched, so is there nothing I can do?

**Comment by Masamune3210** [comment]
Until a modchip or other means is found, yeah you are stuck with ofw

**Comment by Swiftybar** [comment]
Oh well, thanks anyway guys
