### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by rubinorosso93** [FlagBrew/Checkpoint#365]
hi, when i update (cfw 10.4 and atmosphere last version)
the line with time played is disappear
i have checkpoint 3.7.4

![WhatsApp_Image_2020-07-15_at_01 56 04](https://user-images.githubusercontent.com/69009921/88953801-ba8f3c80-d299-11ea-8544-29ab88344975.jpeg)

**Comment by diwo** [comment]
Ran into problems with playtime as well after updating my system, but the issue went away after rebuilding Checkpoint from source

**Comment by rubinorosso93** [comment]
> Ran into problems with playtime as well after updating my system, but the issue went away after rebuilding Checkpoint from source

how i can do that? (rebuilding from source)?

**Comment by diwo** [comment]
You need to install devkitpro, see https://github.com/FlagBrew/Checkpoint#building

Then just run `make`

**Comment by rubinorosso93** [comment]
> You need to install devkitpro, see https://github.com/FlagBrew/Checkpoint#building
> 
> Then just run `make`
sorry I still don't understand, after installing devkitpro and opening msys2 a screen similar to cmd appears, what should I do here? typed make and what?
