### ISSUE TITLE
Does not work with latest firmware and latest AMS 14.1

### ISSUE THREAD

**Issue by EXO5KELETON** [FlagBrew/Checkpoint#366]
**Describe the bug**
When you run the NRO on latest AMS and Horizon FW checkpoint crashes.

**To Reproduce**

**Expected behavior**
expected to get into the save game and be able to restore.

**Screenshots**

**Switch:**
- Entrypoint:
- System version: 10.1.0
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32
- Result code (if available):

**Additional context**

**Comment by GriffinG1** [comment]
What do you mean by “crashes”? Is it a generic error? Is it an atmosphere crash page? If it’s the latter, what is the result code it gives you? You have minimally filled out the template, with vague info, which makes it difficult to help you.

**Comment by EXO5KELETON** [comment]
Sorry matey I’m new to this github stuff

See attached

**Comment by GriffinG1** [comment]
Email responses do not add attachments. Please use the site instead.

**Comment by EXO5KELETON** [comment]
![IMG_1047](https://user-images.githubusercontent.com/66844343/89301494-a3699980-d661-11ea-9e4c-b206a31777df.jpg)

**Comment by GriffinG1** [comment]
Do you have a cartridge and/or a game installed?

**Comment by GriffinG1** [comment]
Also, how are you entering checkpoint? And if you have a cart/installed game, is there save data present in it?

**Comment by EXO5KELETON** [comment]
No...I have literally just updated to 10.0.1 and a clean install of AMS 14.1. As soon as I launch checkpoint it does that...It doesn't matter if I try it in applet mode or if I hold R so it has full access to ram as soon as I click on checkpoint that happens straight away.

**Comment by GriffinG1** [comment]
You’re saying you have no cart inserted with a save file, nor any installed game with a save file? If so, that is your issue.

Also, don’t use applet mode at all due to that decreased ram issue. Always use title takeover (you need to be holding R while launching a *title*, not the album, which your message suggests you’re doing)

**Comment by EXO5KELETON** [comment]
Thank you ill give it a shot later when I get home and update you thank you

**Comment by Atrius97** [comment]
![20200804_083518](https://user-images.githubusercontent.com/39707481/89306772-8ca94f80-d62d-11ea-8459-8807bee32f13.png)

**Comment by EXO5KELETON** [comment]
Sorry did anyone ask for your input, ok so I have BOTW installed with a save game and when I restore it looks like it restores ok but when you go to the save game nothing appears....I have gone back to AMS 13 and it restores fine so deff something weird with AMS.
