### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by impeeza** [FlagBrew/Checkpoint#368]
**Describe the bug**
Take a lot of time refresh list of games on 3DS XL.

**To Reproduce**
1. Launch Checkpont 3.7.4.
2. On Main Screen press and keep pressed the (B) Button
3. For 10 games takes almost 30 second to be populated the icons.

**Expected behavior**
The refreshing of titles by example on FBI takes 5 seconds, tryed on JKVSM and takes 3 seconds only

**3DS:**
- Entrypoint: Luma 10.2-68973d1d
- System version: Sys 11.13.0-45U
- Checkpoint version: 3.7.4
- Result code (if available): N&A

**Comment by BernardoGiordano** [comment]
Not a bug. FBI and JKSM don't cache the icons on the SD card, Checkpoint does.
