### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by Mr-ZombieSteam** [FlagBrew/Checkpoint#369]
Could you update/add codes for Pokemon Y, and Pokemon Super Mystery Dungeon EU & US?  

SMD - none of the cheats work
Pokemon Y - hoping for XP multipliers, catch trainer Pokemon, Money codes and item codes. 

Regards. 

(P.S thanks for this amazing app!)

**Comment by GriffinG1** [comment]
This is not the correct repo, nor something useful. Nobody on the team knows how to (or wants to learn to) make codes. If the smd codes aren't working, please open an issue on the proper repo [here](https://github.com/FlagBrew/Sharkive).

**Comment by Mr-ZombieSteam** [comment]
> This is not the correct repo, nor something useful. Nobody on the team knows how to (or wants to learn to) make codes. If the smd codes aren't working, please open an issue on the proper repo [here](https://github.com/FlagBrew/Sharkive).

Right!

Sorry I completely messed that up!

Sorry for wasting your time, thanks for the response!
