### ISSUE TITLE
Extdata restore not working

### ISSUE THREAD

**Issue by Razorshnegax018** [FlagBrew/Checkpoint#370]
G'day, mates.

I know this problem has been encountered before and fixed. However, The link that the moderator posted to fix the problem leads to dropbox error 404, The file does not exist.

If you do not know what I am talking about, Let me give you a rundown:

Checkpoint extdata restore function is broken, and has not been fixed. What happens is that certain games (The game that I am trying to restore, Monster Hunter Generations,) Do not have a backup and restore save function. Instead, Checkpoint gives them a extdata backup and restore function. The backup function is fine. It's restore is making me lose my mind. (Rhyme not intended). You see, I formatted the 3ds that the checkpoint app is on. Yes, I made sure the checkpoint app that I re-installed was the same version. Yes, Other games work with the reinstalled version. Yes, I tried downloading the JKSV manager instead. It seems like JKSV can backup and restore extdata just fine, However, It cannot do that with backups made by checkpoint. I conducted an experiment to prove this, And I was right. When I tried to restore the checkpoint backup, I can tell It did absolutely nothing. It didn't corrupt or install anything. Nothing. Please, Help me out. I refuse to give up on this purr-fectly good save just becuase of some stupid broken savedata manager.

Many Thanks

**Comment by GriffinG1** [comment]
Please fill out the proper bug report template instead of ignoring it, as you are not providing a bunch of vital information.

**Comment by Razorshnegax018** [comment]
I'm afraid I do not know what you are talking about

**Comment by piepie62** [comment]
When you open an issue, you can either open a bug report or a feature request. This is a bug report, and so you should fill out the text that comes up when you hit that button
