### ISSUE TITLE
Extdata restore not working (Edited)

### ISSUE THREAD

**Issue by Razorshnegax018** [FlagBrew/Checkpoint#371]
**Describe the bug**

Checkpoint extdata restore function is broken, and has not been fixed. What happens is that certain games (The game that I am trying to restore, Monster Hunter Generations,) Do not have a backup and restore save function. Instead, Checkpoint gives them a extdata backup and restore function. The backup function is fine. It's restore is making me lose my mind. (Rhyme not intended). You see, I formatted the 3ds that the checkpoint app is on. Yes, I made sure the checkpoint app that I re-installed was the same version. Yes, Other games work with the reinstalled version. Yes, I tried downloading the JKSV manager instead. It seems like JKSV can backup and restore extdata just fine, However, It cannot do that with backups made by checkpoint. I conducted an experiment to prove this, And I was right. When I tried to restore the checkpoint backup, I can tell It did absolutely nothing. It didn't corrupt or install anything. Nothing. Please, Help me out. I refuse to give up on this purr-fectly good save just becuase of some stupid broken savedata manager.

**To Reproduce**
1: Press X to see extdata titles
2: Nothing appears on the screen, although the files are in the correct spot (bug)

**Expected behavior**
Monster hunter generations to appear as a title in checkpoint when X is pressed for extdata

**3DS:**
- Entrypoint: Home menu cia
- System version: 11.13.0-45U
- Checkpoint version: 3.7.4
- Result code (if available):

**Additional context**
My apologies for not correctly reporting the bug correctly the first time

**Comment by piepie62** [comment]
Checkpoint does not create save/extdata archives for you, as it cannot know the parameters for the creation that each game wants. You need to open the game and save at least once for it to show up.

**Comment by Razorshnegax018** [comment]
I did do that my friend. I'm sorry for not putting it in the bug description

**Comment by piepie62** [comment]
Try holding B to refresh, then. If that doesn't work, I'll reopen the issue

**Comment by Razorshnegax018** [comment]
My my. Thank you so much my good sir. It worked
