### ISSUE TITLE
Not all my games are showing up

### ISSUE THREAD

**Issue by BenjaminJamesBryanCarter** [FlagBrew/Checkpoint#372]
when i load checkpoint some of my games show up like paper mario sticker star does anyone know how to fix this?

**Comment by GriffinG1** [comment]
![BBBA75BA-6C8A-4279-AA32-11D60AD5E76D](https://user-images.githubusercontent.com/28538707/95150891-8bd48d00-0746-11eb-88c4-75a1cba2611e.jpeg)

**Comment by BenjaminJamesBryanCarter** [comment]
it randomly showed up
