### ISSUE TITLE
Freeze on user change? [Switch]

### ISSUE THREAD

**Issue by silverjohnes** [FlagBrew/Checkpoint#373]
**Describe the bug**
The program shows only one user of two

**To Reproduce**
1. Tap on user picture OR press ZL
2. Program freezes
**Expected behavior**
1. User can be changed.

**Screenshots**

**3DS:**
- Entrypoint:
- System version:
- Checkpoint version:
- Result code (if available):

**Switch:**
- Entrypoint:
- System version: 10.2
- Checkpoint version: v3.7.4
- SD Card Filesystem: exFAT and FAT32
- Result code (if available): n/a

**Comment by GriffinG1** [comment]
![4C9F4755-87BD-4058-852B-C98FA056EEDE](https://user-images.githubusercontent.com/28538707/95243690-3d6ad100-07ce-11eb-8e14-e819bc40980b.jpeg)
