### ISSUE TITLE
Ability to detect and dump saved files for games that are out-of-region on the 3DS

### ISSUE THREAD

**Issue by dothackjhe** [FlagBrew/Checkpoint#374]
I'm not sure if my 3DS is just not properly configured, but I noticed that the latest version of Checkpoint for the 3DS is having an issue not being able to detect saved file for games that are running via region emulation. In my case, I am running a Japanese game on a USA console.

While all the US games installed appear just fine on Checkpoint, the Japanese games would not.

**Comment by GriffinG1** [comment]
![B7BD7C56-5B49-4AC5-AAC2-14001644E8D5](https://user-images.githubusercontent.com/28538707/96745099-ff9baa00-1382-11eb-9def-cd06df7243ab.jpeg)

**Comment by dothackjhe** [comment]
For a while there, I thought it was really an issue with the disparity between the region of the 3DS and the game. In my case, the issue was addressed by shifting to "extdata" from the Checkpoint interface by pressing the "x" button.
