### ISSUE TITLE
Cheat not working

### ISSUE THREAD

**Issue by Blazingsoul6666** [FlagBrew/Checkpoint#377]
**Describe the bug**
I'm not sure if this is the right place to ask this but,I got Shin Megami Tensei IV and tried to use one of the cheats and it didn't do anything.

**To Reproduce**
1. Go to 'checkpoint'
2. Click on 'cheats(on shin megami tensei IV)'
3. Scroll down to 'app points 9999' and click it.
4. Go in game and open luma menu > cheats > app points 9999 > press B > press B

**Expected behavior**
Nothing happens except a item being added to your relics with a name of a foreign language that i can't understand. 
**Screenshots**
![IMG_20201101_164602](https://user-images.githubusercontent.com/73443188/97820193-d7088f80-1c61-11eb-9538-8f30a0757798.jpg)

**3DS:**
- Entrypoint:Luma 10.2-bb07a73
- System version:11.13.0-45U
- Checkpoint version: 3.7.4

Again,idk if this is the right place to ask so if it isn't plz send me somewhere it is

**Comment by GriffinG1** [comment]
Cheat related issues go in the [Sharkive](https://github.com/FlagBrew/Sharkive) repo. Please move your issue there.

**Comment by Blazingsoul6666** [comment]
ok thanks!
