### ISSUE TITLE
Why is there a PKSM.smdh in the RomFS of the 3DS version?

### ISSUE THREAD

**Issue by TimmSkiller** [FlagBrew/Checkpoint#378]
Is it done on purpose? If it is, then what is it used for? I'm genuinely curious

**Comment by raventhecat333** [comment]
same

**Comment by GriffinG1** [comment]
It's the app's icon.

**Comment by piepie62** [comment]
Yep, it's PKSM's icon for when PKSM is installed as a 3DSX. Checkpoint still can access PKSM's ExtData because that is there
