### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by MaxACartwright** [FlagBrew/Checkpoint#381]
**Describe the bug**
Well, it's not really a bug, but I had to redownload Tomodachi Life, and I lost everything but I tried to restore my old save using checkpoint, no luck. The files are still there, it just only shows up under extdata and doesn't show up on the games list.

**To Reproduce**
1. Redownload (Uninstall/reinstall) any app that you used with checkpoint
2. Open checkpoint
3. Doesn't see game without extdata.

**Expected behavior**
I expected to see my backups and when I would click restore, everything would go back to normal.

**3DS:**
- Entrypoint: Boot9Strap
- System version: 11.14
- Checkpoint version: Latest
- Result code (if available):

**Additional context**
Thanks for fixing.

**Comment by BernardoGiordano** [comment]
You need to save at least once before using Checkpoint.
