### ISSUE TITLE
Feature Request: Upload a fresh .nro version of Checkpoint

### ISSUE THREAD

**Issue by mrhappyasthma** [FlagBrew/Checkpoint#382]
It looks like the latest commits added support for PKSM bridge mode w/ Sword And Shield (https://github.com/FlagBrew/Checkpoint/commit/0d0b12a6d2c91c007ce0d7e0a02e6be5ef41c042 and https://github.com/FlagBrew/Checkpoint/commit/c46b4dec598967b5573e6d9f6b7d5786be072d23). However this isn't rolled-up into the latest release.

I tried building a copy for Switch locally, but was getting cryptic python issues when running `make` on my old macbook.

Is it possible to get a new release published (or someone upload a fresh `.nro`) so that I can access this feature?

**Comment by mrhappyasthma** [comment]
It looks like there's a project in progress for version 4.0: https://github.com/FlagBrew/Checkpoint/projects/1

However any recent/stable version would help me out greatly! :)

**Comment by piepie62** [comment]
Features will be released when they are ready. The Sword/Shield bridge actually has an issue that needs to be solved before release, and may not work properly as-is. Releases are done when they are for a reason, and asking "can a release happen soon" is uniquely frustrating. Please refrain from doing it in the future, for any project that you may be using

**Comment by mrhappyasthma** [comment]
Ah, fair point. If it's not in a stable state yet, then not publishing a new .nro does make sense.

Instead, would a more appropriate course of action be to file an issue specific to the Sword/Shield bridge to track any work that still needs to be done?

**Comment by mrhappyasthma** [comment]
I had to reinstall a bunch of stuff, but I was able to get a build working.

I'll play around with the bridge to see if I can help improve it's functionality.
