### ISSUE TITLE
Restoring saves seems broken on Atmosphere 17 and FW 11.0.1

### ISSUE THREAD

**Issue by shalien** [FlagBrew/Checkpoint#387]
**Describe the bug**
Also when restoring save, the application will display a success message but the save aren't actually restored

**To Reproduce**
1. Start Atmosphere 17 using fusée-primary on CFW sysNAND
2. Start Homebrew Menu using application takeover (I didn't try with album)
3. Start Checkpoint
4. Backup a save ( I try with Zelda:BoTW and Pokemon Sword)
5. Modify the save 
6. Restore the save using Checkpoint
7. Reboot in OFW
8. Start the game
9. Change made to the save aren't present

**Expected behavior**
The restored save should show the modification made in the external editor

**Screenshots**

**Switch:**
- Entrypoint: Application Takeover (In memory game)
- System version: 11.0.1
- Checkpoint version: 3.7.4
- SD Card Filesystem: FAT32
- Result code (if available):

**Additional context**
CFW Atmosphere 17 lastest version with lastest payload

**Comment by GriffinG1** [comment]
Make sure you’re restoring in sysnand, not emunand.

**Comment by Zacharybinx34** [comment]
Why?
