### ISSUE TITLE
Aplication crash on startup

### ISSUE THREAD

**Issue by JuezFenix** [FlagBrew/Checkpoint#390]
Lastest version of Checkpoint: 3.7.4
Atmosphère: 0.18.1
SW: 11.0.1

**Comment by bowman-matt** [comment]
Have you edited your config file at all? I am seeing a crash when I add a line to the additional saves config. But I am pointing it to /ROMS/NDS and I am not sure .sav files are supported

**Comment by BernardoGiordano** [comment]
> Lastest version of Checkpoint: 3.7.4
> Atmosphère: 0.18.1
> SW: 11.0.1

do you have any games installed/save file created?

**Comment by imadethisfor1page** [comment]
As a person also having this issue. Yes I do have a game installed. I am following the Yuzu Quickstart Guide and to the point where I have to launch Checkpoint... crash
