### ISSUE TITLE
Game list doesn't show certain games installed with Godmode9

### ISSUE THREAD

**Issue by ICEknigh7** [FlagBrew/Checkpoint#393]
**Describe the bug**
Games installed from cartridge with Godmode9 sometimes don't appear in the game list. These games are perfectly functional.

**To Reproduce**
1. Install a game directly from cartridge with Godmode9
2. Open Checkpoint and wait for the game list to fill
3. Some of the newly installed games show up while other don't. In my case, A link Between Worlds and Mario Kart 7 show up, while Freakyforms Deluxe and Super Mario 3D Land don't (all European versions).

**Expected behavior**
All installed games should appear on the game list.

**3DS:**
- Entrypoint: Godmode9 2.0.0
- System version: 11.14.0-46E
- Checkpoint version: 3.7.4

**Additional context**
These games do show up when the cartridge is inserted, so the save can be backed up correctly. It can't be restored in the installations since those don't show up, though.

**Comment by Masamune3210** [comment]
Do these games already have saves and have you opened the game at least once before checking in here? Games wont show up until their save archive is created iirc

**Comment by ICEknigh7** [comment]
Hey, you were right. Didn't realize that Super Mario 3D Land doesn't create the save file right away after first boot.
So problem solved, thanks.
