### ISSUE TITLE
Fatal Save Loss Glitch

### ISSUE THREAD

**Issue by BrittanyOfKoppai** [FlagBrew/Checkpoint#395]
Being the impatient human being I am, I tried to close the software out to home menu while it was still loading titles. Turns out, _that completely wiped my NAND._ Now, the 3ds acts as if it's only being booted for the first time.

(Thankfully, I made a NAND backup not 2 days before this happened.)

Anyway, I feel there should be some sort of way to prevent this from happening, so somebody who _**doesn't**_ have a backup doesn't lose all their save data.

**Comment by piepie62** [comment]
This is literally impossible for Checkpoint to do; it doesn't include any code that *could* end up doing that. The only explanation is that you somehow corrupted the FS sysmodule's work with that close-out, which Checkpoint can't protect against
