### ISSUE TITLE
Bug Report - Compatibility Atmosphere 0.19.0+

### ISSUE THREAD

**Issue by Santiav90** [FlagBrew/Checkpoint#398]
**Describe the bug**
After installing Atmosphere 0.19.0, when I try to open checkpoint atmosphere crashes.

**To Reproduce**
1. Go to Album
2. Click on Checkpoint
3. See error

**Expected behavior**
I expected the checkpoint menu to open in order to select saves.

**Switch:**
- Entrypoint:
- System version: 12.0.0
- Checkpoint version: Latest
- SD Card Filesystem:TegraRCMGUI
- Result code (if available):

**Comment by AlamosIT** [comment]
Checkpoint shouldn't be used with Album, have you tried opening Homebrew Launcher with other apps?
You can do this holding the R button while launching any game (including demos/cartridges) or application (e.g. Youtube/Hulu).

**Comment by Santiav90** [comment]
Even when opening it that way, it still crashes. Differently though. Instead of having to restart the game, it just says "the software was closed because an error occurred."

**Comment by GriffinG1** [comment]
Looking into it right now... just to be sure; you have saved in at least one game, yes?

**Comment by igor-astsakhov** [comment]
I got the same issue, tried to reinstall it, checked the filesystem on sdcard nothing helping.

**Comment by AlamosIT** [comment]
Seems to be a compatibility error with 0.19.0, it was also reported on FlagBrew Discord Channel.

**Comment by GriffinG1** [comment]
> Looking into it right now...

**Comment by justin-kang** [comment]
Issue persists with Atmosphere 0.19.1.

**Comment by GriffinG1** [comment]
Because this is not an issue that would be solved on atmosphere’s side. Checkpoint will eventually be compatible, have patience.

**Comment by Grass0001** [comment]
if you don't have patience, there's a potentially broken but working release [here](https://github.com/SciresM/Checkpoint/releases)

**Comment by igor-astsakhov** [comment]
> if you don't have patience, there's a potentially broken but working release [here](https://github.com/SciresM/Checkpoint/releases)

I tried it didn't work for me using 0.19.1 , hekate 5.5.5

Using R I get "The software was closed because an error occured."

Going through album same error code 2144-0001

**Comment by impeeza** [comment]
Hi, I just Compiled the Fix compilation branch and works fine, just a little issue, when selecting a different user profile,  the name and picture of later is kept, so the backups for the new user still have appended the wrong username.

**Comment by igor-astsakhov** [comment]
Can you post the .nro files?

**Comment by impeeza** [comment]
I just use MSYSW64 clone the git change to the "Fix Compilation" branch and run make, the result is:
[Checkpoint_3_7_5_Prelease-Fix compilation branch(Giordano).zip](https://github.com/FlagBrew/Checkpoint/files/6330047/Checkpoint_3_7_5_Prelease-Fix.compilation.branch.Giordano.zip)

**Comment by impeeza** [comment]
thanks to @BernardoGiordano for the changes on the code.

**Comment by igor-astsakhov** [comment]
Cool, I can load it now but I cant select a save to restore it just blinks on New, I can save a new back up but no way to select a backup any idea? Also doesn't load through applet mode only when using R.

**Comment by HerbySenpai** [comment]
Checkpoint don't open on my Switch :( I click on the app, the Screen goes black and after that I am again in the hbmenu.

**Comment by impeeza** [comment]
> 
> 
> Checkpoint don't open on my Switch :( I click on the app, the Screen goes black and after that I am again in the hbmenu.

Hi, please provide more information,  version of firmware, version of hardware, version of atmosphére, sigpatches, etc.  and read previus issues and post.  the news firmware compatibility is still on progress, or try the [SciresM version](https://github.com/SciresM/Checkpoint/releases)

**Comment by Craftyawesome** [comment]
The one linked above crashed for me when I tried to backup a save, but this one worked. https://github.com/SciresM/Checkpoint/releases/tag/ams-19-compat

**Comment by HerbySenpai** [comment]
> 
> 
> > Checkpoint don't open on my Switch :( I click on the app, the Screen goes black and after that I am again in the hbmenu.
> 
> Hi, please provide more information, version of firmware, version of hardware, version of atmosphére, sigpatches, etc. and read previus issues and post. the news firmware compatibility is still on progress, or try the [SciresM version](https://github.com/SciresM/Checkpoint/releases)

System 12.0.0 
Atmos 19.0.1

and I tried the [SciresM version](https://github.com/SciresM/Checkpoint/releases)
after that I got this "error" before that I got the Error Code 2144-0001 (0x290)

**Comment by evelynmatson** [comment]
I’m having this too. Same “The software was closed because an error occured” when opened in non-applet mode. Haven’t tried the build provided. 
system 10.2.0 | atmosphere 19.1 E

**Comment by AlamosIT** [comment]
> I’m having this too. Same “The software was closed because an error occured” when opened in non-applet mode. Haven’t tried the build provided.
> system 10.2.0 | atmosphere 19.1 E

If you are in FW 10.2.0 you can use Atmosphere 0.18.1, that works with official release. In Atm 0.19.x (until they release a new official version) you have to use SciresM's build.

**Comment by PapaTurk** [comment]
What the fuck is taking them so long? Its has been around 3 weeks since we can't use Checkpoint on the Switch and we have heard nothing from them.

**Comment by BernardoGiordano** [comment]
@PapaTurk bring respect. This is being worked on and will be ready when the software is working properly: rushing releases only causes more trouble in the long run. People have been working on this project for free for years. If you think this is taking too long, please join development and do something useful rather than complaining about what people are doing in their free time.

**Comment by Santiav90** [comment]
Wow @PapaTurk . You probably haven't paid a single cent for all the work they do so at least have some respect. There is actually a temporary fix on discord but I bet you haven't even bothered to look for it. And it's temporary, it doesn't work perfectly so you would probably be mad about that too. Just give them time, they've got their own lives and things more important than this.

Thanks a lot to everyone who collaborates to make checkpoint possible, take your time, as we users have no idea about how hard it is to create a new version and we are truly grateful for your work. <3

**Comment by NamelessMofo** [comment]
Hi, it's been almost 3 weeks and I was just wondering how things were progressing on fixing this issue. Unlike others, I DO appreciate all the hard work you guys and others put into all these tools, but look forward to being able to use an officially blessed build for managing my saves. Thanks again!

**Comment by impeeza** [comment]
> Hi, it's been almost 3 weeks and I was just wondering how things were progressing on fixing this issue. Unlike others, I DO appreciate all the hard work you guys and others put into all these tools, but look forward to being able to use an officially blessed build for managing my saves. Thanks again!

You can always go to https://github.com/FlagBrew/Checkpoint and make the code changes needed to be compatible and full working. Then create the corresponding pull requests. 

And/or become a patreon 
https://www.patreon.com/FlagBrew
Regards

**Comment by dominus26** [comment]
First off huge hats off for this amazing project. 
I have ended up here, since I too am now affected by this issue with Atmosphere 0.19 on 12. 
Hoping this issue will be resolved soon, as I use checkpoint ALOT. Its a life (game) saver :) 👍

**Comment by whi-tw** [comment]
Can people just please stick a thumbs up on the initial issue, and then turn notifications on. It's getting frustrating seeing all these +1 messages. It'd be nice if the next email we have would be from @FlagBrew telling us it's fixed.

Adding a +1 almost never results in anything getting done faster, and sometimes will actually slow progress down.

**Comment by FM1337** [comment]
Locking this issue, we know about the bug thank you for the report, no ETA on fix, but it is being worked on

**Comment by BernardoGiordano** [comment]
This is fixed.
