### ISSUE TITLE
Feature Request (Restore all)

### ISSUE THREAD

**Issue by NinFanBoyFTW** [FlagBrew/Checkpoint#401]
Hi I wanted to know if there would be a way to add a restore all saves option to checkpoint. I have been using checkpoint for a long time to backup all of my saves at 1 time, and it would be very useful to be able to restore all saves to my secondary switch with 1 button click. Thanks

**Comment by BernardoGiordano** [comment]
It won't be possible, since Checkpoint doesn't know which one of your backups you want to restore.

**Comment by NinFanBoyFTW** [comment]
Hi, couldn't you just have checkpoint restore the "latest save" in the list. Like when I do a backup all, I only have 1 save per game in my sd card anyway
