### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NicoCardenas550** [FlagBrew/Checkpoint#402]
**Describe the bug**
Checkpoint crashes when it is launched on Nintendo Switch

**To Reproduce**
1: launch the Homebrew Menu using title override
2: launch Checkpoint
3: it crashes

**Expected behavior**
Checkpoint should have started normally

**Switch:**
- System version: 12.0.2
- Checkpoint version: 3.7.4
- SD Card Filesystem: Fat32

**Additional context**
I was using Atmosphere 0.19.3 and not SX os.

**Comment by Aura314** [comment]
Download Checkpoint from here: https://github.com/SciresM/Checkpoint/releases/tag/ams-19-compat and then hold down R and start a game Checkpoint works on firmware 12.0.2 and atmospehre 19.3

**Comment by impeeza** [comment]
Duplicated issue #398 https://github.com/FlagBrew/Checkpoint/issues/398
