### ISSUE TITLE
[Bug][Repo] Newest cheats not available due to Sharkive link

### ISSUE THREAD

**Issue by subworx** [FlagBrew/Checkpoint#404]
**Describe the bug**
Due to linking Sharkive repo at a specific commit (Sharkive @ 9877a65), no further commits are recognized, so any cheats updated since Jun 16, 2020 cannot be found in Checkpoint.

**To Reproduce**
1. Install any game where the cheats have been updated after Jun 16, 2020, e.g. Tetris Axis (USA) (0004000000043800) -> https://github.com/FlagBrew/Sharkive/blob/master/3ds/0004000000043800.txt , cheats added on Sep 15, 2020. 
2. Open Checkpoint, select the installed game, click "Cheats"
3. Receive error message "No available cheats codes for this title" even though they exist in the repo for sure.
Same for Shovel Knight (EU) (0004000E0017C900/000400000017C900), Nano Assault EX (EUR)(00040000000BA300), while some titles have old cheats but not updated ones, like Bravely Second (US) (000400000017BA00).

**Expected behavior**
Find all current cheats that exist in the repo.

**3DS:**
- Entrypoint: Installed CIA from home screen
- System version: 11.14.0-46
- Checkpoint version: 3.7.4
- Result code (if available): -

**Additional context**
Linking against Sharkive/Master (if possible) instead of a specific commit would fix the issue permanently. Otherwise, the link would need to be updated whenever a cheat is updated.

**Comment by GriffinG1** [comment]
Checkpoint does not fetch new cheats and the internal database is only updated at an official release. You can compile the database yourself by following the instructions in sharkive's readme. Not a bug.

**Comment by KintsugiUwU** [comment]
> Checkpoint does not fetch new cheats and the internal database is only updated at an official release. You can compile the database yourself by following the instructions in sharkive's readme. Not a bug.

Sorry to bother you, but I did the guide step by step, cloned the repo, compiled the latest release, renamed 3ds.json to cheats.json and placed in the 3ds/checkpoint folder, but it still doesn't see the codes, even tho they are there.
