### ISSUE TITLE
Launching Checkpoint.nro Crashes Atmosphere

### ISSUE THREAD

**Issue by CommicKick69ing** [FlagBrew/Checkpoint#405]
**Describe the bug**
For some reason when ever I open Checkpoint it crashes my CFW and updating and or replacing the files so has done nothing to fix it and now stuck and confused. If anyone can help me find a solution that would be much appreciated

**Screenshots**
![ScQ5Rlo](https://user-images.githubusercontent.com/40266764/120943977-034c2900-c6e7-11eb-9fcb-757d1fe08b9c.jpeg)

**Comment by impeeza** [comment]
Duplicated. Please read https://github.com/FlagBrew/Checkpoint/issues/398 snd there you get help and intermin working versions

**Comment by CommicKick69ing** [comment]
> Duplicated. Please read #398 and there you get help and intermin working versions

The checkpoint release by SciresM does not work but instead when I open it the app boots me back to the homebrew menu

**Comment by impeeza** [comment]
By the way the 010000000000100 is the nxthemes installer module it must be deleted before a firmware update and recreteated on the new firmware with the most recent version of nxthemes installer
