### ISSUE TITLE
Launching Checkpoint Crashes Atmosphere (Firmware: 12.0.2)

### ISSUE THREAD

**Issue by CommicKick69ing** [FlagBrew/Checkpoint#406]
**Describe the bug**
For some reason when ever I open Checkpoint it crashes my CFW and updating and or replacing the files so has done nothing to fix it and now stuck and confused. If anyone can help me find a solution that would be much appreciated.
The checkpoint release by SciresM does not work but instead when I open it the app boots me back to the homebrew menu

**Screenshots**
![IMG_20210606_194903449_HDR](https://user-images.githubusercontent.com/40266764/120944443-58893a00-c6e9-11eb-8d4e-b6a53e93cbd1.jpg)

**Don't close this bug report until the issue is Actually solved**

**Comment by FM1337** [comment]
Yes this is a known bug, there's an issue pinned for it.

**Comment by CommicKick69ing** [comment]
> Yes this is a known bug, there's an issue pinned for it.

Sorry, can link me to the pinned issue

**Comment by FM1337** [comment]
#398

**Comment by GriffinG1** [comment]
As a note: any issues with Scires' build will not be addressed as it is a beta build in all but name. In addition, many people are running it fine. You do not seem to be running that build as the error code in that screenshot wouldn't occur with Scires' build. Debug your user error, or wait for when the next official release of Checkpoint is ready. No, there is no ETA.

**Comment by impeeza** [comment]
By the way the 010000000000100 is the nxthemes installer module it must be deleted before a firmware update and recreteated on the new firmware with the most recent version of nxthemes installer

**Comment by CommicKick69ing** [comment]
Will inistalling the module now help fix this issue?

**Comment by GriffinG1** [comment]
Please do not post unrelated content on this issue tracker. This is specifically for Checkpoint-related issues.
