### ISSUE TITLE
Checkpoint Error

### ISSUE THREAD

**Issue by GlitchingWolf297** [FlagBrew/Checkpoint#407]
[I use a Nintendo Switch] So I gotten the latest version of Checkpoint, I moved the file to the root of the switch. But after I proceed to press it it gives me an Error saying that, "The software was closed because an error occurred." Does anybody know how I could fix this error?

**Comment by impeeza** [comment]
Yes it's easy, read the other issues and follow the instructions on there, you could use the interim version:
[https://github.com/SciresM/Checkpoint/releases](https://github.com/SciresM/Checkpoint/releases)

Duplicated [https://github.com/FlagBrew/Checkpoint/issues/398](https://github.com/FlagBrew/Checkpoint/issues/398)
