### ISSUE TITLE
Wrong save used during backup/restore actions

### ISSUE THREAD

**Issue by jmsb** [FlagBrew/Checkpoint#408]
**Describe the bug**
For a couple of games I have ~ 50 saves backed up for each on a single profile. When in checkpoint there are the L and R commands to backup and restore the selected save. Recently (?) the behavior has changed such that L and R are also paging through the saves, causing the wrong save to be selected for restoration or overwrite. Previously the left thumbstick was needed to page through the list so that L and R always used the currently selected save.

**To Reproduce**
1. Open checkpoint by launching a title while holding R.
2. Select a target game on the list.
3. Use the left thumbstick to page through the list, and the arrow keys to pick select the target save.
4. Click L or R to bring up the backup/restore dialog.
5. The dialog shows as expected with a confirmation. Click Y.
6. Notice that the selected game is one page above or below the original selection.
7. Use the a-button to select a game to restore, and confirm that the backup/restore action targeted the wrong save.

**Expected behavior**
The L and R buttons should not change the position in the list.

**Screenshots**
N/A

**Switch:**
- Entrypoint: Hold R button while launching a title.
- System version: 12.0.3|AMS M.19.4|S
- Checkpoint version: 3.7.4 with the patch for the open Atmosphere bug applied
- SD Card Filesystem: N/A
- Result code (if available): N/A

**Additional context**
I have definitely done a bunch of backup/restore operations since applying the Atmosphere patch successfully, with the last time being within the last 30 days. The only change that I can think of is a system version + atmosphere update in the past month as I always keep both up to date on my system.

I think that's it. Let me know if there is more information that I can provide.

**Comment by GriffinG1** [comment]
Closing as this seems to be more user error. However, the name of the save that's being restored will possibly be added to the info box.
