### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by JohlTheMaker** [FlagBrew/Checkpoint#409]
I'm trying to transfer save data from my old 2ds to a new one, but some games just aren't showing up on my new one. I've opened them and even created saves, but it still won't work.

**Comment by GriffinG1** [comment]
You likely need to refresh the titles. Hold B.

**Comment by impeeza** [comment]
Or you hasn't create a save on the game prior try to restore, Checkpoint only can restore on existing saves not create inexistent ones

**Comment by GriffinG1** [comment]
@impeeza from their message:
> I've opened them and **even created saves**

**Comment by Bombogor** [comment]
They havnt updated checkpoint in 2 years, are these lazy fucks even working on it?

**Comment by impeeza** [comment]
you always will find stupids trolls demanding but not collaborating.  Thanks to FlagBrew Team for all your great effort.
