### ISSUE TITLE
using cheats on virtual console pokemon

### ISSUE THREAD

**Issue by EpicXboss250** [FlagBrew/Checkpoint#411]
I used cheats in pokemon gold virtual console on 3ds to get all the pokeballs and i got a bunch of light balls aswell i tried to sell them or throw them away but i still have them after, any answers as to what this is or how to solve it would be greatley appreciated.

**Comment by GriffinG1** [comment]
1) Cheats questions go to the [Sharkive](https://github.com/FlagBrew/Sharkive) repo, or preferably the FlagBrew discord server.

2) Disable the cheat, it seems like it's either an always on one, or triggered by a button you're using regularly.
