### ISSUE TITLE
Will compatibility for atmosphere 19.5 / firmware 12.x be worked into a new build? 

### ISSUE THREAD

**Issue by Mafaveli** [FlagBrew/Checkpoint#414]

**Comment by GriffinG1** [comment]
#398 duplicate, more or less.

**Comment by impeeza** [comment]
Do not open duplicated issue is already treated on [issue 398](https://github.com/FlagBrew/Checkpoint/issues/398) you can always make the necessary changes on code and compile on new devtools then pull request to main repository
