### ISSUE TITLE
App crash as soon as I launch it

### ISSUE THREAD

**Issue by theshinyknight** [FlagBrew/Checkpoint#415]
**Describe the bug**
After installing the version of checkpoint available on the hbstore app, and trying to run it, I get a crash

Error code: 2144-001 (0x290)
program: 0100000000001000
Firmware: 12.1.0 (atmosphere M 0.19.5-master-9df13781c)

**To Reproduce**
Download Checkpoint from the homebrew app on the switch; once done installing, launch it

**Expected behavior**
The app should launch, instead it crash

**Comment by GriffinG1** [comment]
#398 duplicate.
