### ISSUE TITLE
Attempting to add a save path to config.json results in the 3DS crashing

### ISSUE THREAD

**Issue by RealKGB** [FlagBrew/Checkpoint#416]
I have Black, White, Black 2, and White 2 installed on my 3DS via CIA forwarders. The save files are stored at \Games\saves (or 0:\Games\saves, if you use the 3DS's way of organizing where storage is along with the onboard storage) as .sav files, but when attempting to add that folder to config.json so Checkpoint can read it, Checkpoint crashes the 3DS 100% of the time. I have a New Nintendo 3DS XL.

1. Put your SD/microSD card in your computer
2. Open config.json with a text editor (I use Notepad)
3. Add \Games\saves between the {} listen with additional_save_folders, so config.json looks like this:
`{
  "additional_extdata_folders": {},
  "additional_save_folders": {\Games\saves},
  "favorites": [],
  "filter": [],
  "nand_saves": false,
  "scan_cart": false,
  "version": 3
}`
I also tested with putting a 0: before \Games, so config.json looks like this:
`{
  "additional_extdata_folders": {},
  "additional_save_folders": {0:\Games\saves},
  "favorites": [],
  "filter": [],
  "nand_saves": false,
  "scan_cart": false,
  "version": 3
}`
4. Close Notepad and eject your SD/microSD card
5. Put it back in your 3DS and turn on your console

If I open CheckPoint, it will show the loading screen and then the 3DS will crash. I've attached 2 memory dumps in a Google Drive folder if that helps.
**Expected behavior**
I'd expect CheckPoint to open at least, with it showing my saves folder too.

**Screenshots**
N/A

**3DS:**
- Entrypoint: ???
- System version: Luma3DS v10.2.1
- Checkpoint version: Checkpoint v3.7.4
- Result code (if available): ???

**Comment by piepie62** [comment]
There are multiple issues here. First, that's not how JSON formatting works, which is likely the reason for the crash. Second, paths on the 3DS always use slashes, not backslashes. Third, that's not how the additional_save_folders configuration works, either: additional_save_folders is to add separate backup folders that follow Checkpoint's naming schema, like the way [PKSM](https://github.com/FlagBrew/PKSM) handles its backups. It will not pick up random .sav files in a folder you specify. I'll leave this open to make sure that configuration parsing failure is handled, but fixing the crash isn't going to make the behavior that you currently expect to work.

**Comment by RealKGB** [comment]
Ahh, thanks! I knew there was something I was missing but wasn't sure what.
