### ISSUE TITLE
Can't Even boot it

### ISSUE THREAD

**Issue by Ripjaws23499** [FlagBrew/Checkpoint#417]
I'm using ARCropolis 2.0.0 beta7, I'm guessing that's the issue, but I downloaded the NRO, use the R boot to get full RAM, and the moment I launch it, it crashes. Without R boot it gives me an atmosphere crash, but with R boot it gives me the same crash you'd get for getting a normal, non modded switch crash. I'd love to see this get fixed because being able to back up save data is really useful/important. Thanks.

**Comment by GriffinG1** [comment]
Anything other than Atmosphere is not supported.

**Comment by Suit82** [comment]
I see, you're completely correct, I realize the issue now, thanks.
