### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by theshinyknight** [FlagBrew/Checkpoint#419]
**Describe the bug**
savegames saved from switch using Checkpoint does not load when imported in Yuzu

**To Reproduce**
On your switch pick a game, export the save file. Copy the game folder in the saves folder of Yuzu and start the game there.
Try to load a game: an error pop up saying that loading failed

**Expected behavior**
The save file should load fine

**Screenshots**

**Switch:**
- Entrypoint:
- System version: Atmosphere 0.19.5 - Hekate 5.5.8
- Checkpoint version: SciresM compatibility build (https://github.com/SciresM/Checkpoint/releases)
- SD Card Filesystem: FAT32
- Result code (if available):

**Comment by GriffinG1** [comment]
Not a checkpoint issue, take it up with the Yuzu team.
