### ISSUE TITLE
how to make it support citra?

### ISSUE THREAD

**Issue by rcyggdra** [FlagBrew/Checkpoint#437]
like PKSM citra_debug?

**Comment by GriffinG1** [comment]
There's no point, citra saves are not encrypted.

**Comment by piepie62** [comment]
As a side note, I'm genuinely considering removing CITRA_DEBUG from the source code as several issues arise from it at this point (especially with regard to the auto updater), and it's been literal years since I've debugged PKSM using Citra.

**Comment by SNBeast** [comment]
Sir, this is a Checkpoint issue.

**Comment by piepie62** [comment]
Oh, you are correct. I apologize for the lapse in attention, ignore the above. Griffin is correct; there is no point in using Checkpoint on Citra, as Citra saves are unencrypted.
