### ISSUE TITLE
Checkpoint crashes when opened

### ISSUE THREAD

**Issue by LeAldrich** [FlagBrew/Checkpoint#438]
**Describe the bug**
Everytime i start checkpoint it trys to load but after a few sec it crashes and i get this screen:

![PXL_20211206_103904790.jpg](https://user-images.githubusercontent.com/92257915/144832557-a11a21f9-0a06-4e69-891c-41a27bcd5c5d.jpg)

**3DS:**
- System version: 11.15.0-47E
- Checkpoint version: 3.8.0

**Comment by GriffinG1** [comment]
You're on a EUR console, #436 for those please
