### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Soulsilvertano** [FlagBrew/Checkpoint#439]
**Describe the bug**
Crashes every time the program is started up, my only guess is too many games.

**To Reproduce**
1. Go to: Checkpoint (After having a bunch of games installed)
2. Crash occurs with the crash report and system having to reboot.

**Expected behavior**
Menu should open up with all the games being displayed properly without crash.

**3DS:**
- System version: 11.15.0
- Checkpoint version: 3.8.0

- Result code (if available):

**Additional context**
It began when I added Paper Mario Sticker Star to the list of games, and subsequently it began crashing, this was the 24th game in the catalog.

**Comment by GriffinG1** [comment]
Hi, what region is your console? Also, can you please either upload your crash dump or get a photo of it? Thanks.

**Comment by BernardoGiordano** [comment]
[Checkpoint.zip](https://github.com/FlagBrew/Checkpoint/files/7697158/Checkpoint.zip)
Does this work for you?

**Comment by GriffinG1** [comment]
There has been no response to this issue in two and a half months, and it is possibly a duplicate of #432, #433, or #436. If you come back to this issue, @Soulsilvertano, please see if any of those three issues matches your problem and follow the one that does .

Closed for inactivity.
