### ISSUE TITLE
Question: Does game patching affect cheats?

### ISSUE THREAD

**Issue by imsad2** [FlagBrew/Checkpoint#445]
I'm on 3DS, and when playing Majora's Mask 3D I use Project Restoration (a patch by leoetlino). The problem is that every time I try to add cheats it doesn't do anything. So does game patching affect cheats?

**Comment by GriffinG1** [comment]
You need to activate the cheats via Rosalina. Refer to [Luma3DS's wiki](https://github.com/LumaTeam/Luma3DS/wiki/Cheat-Engine#how-do-i-access-cheats-that-i-have-added) page.

**Comment by imsad2** [comment]
> You need to activate the cheats via Rosalina. Refer to [Luma3DS's wiki](https://github.com/LumaTeam/Luma3DS/wiki/Cheat-Engine#how-do-i-access-cheats-that-i-have-added) page.

I did, but they still don't apply.
