### ISSUE TITLE
Bug Report :checkpoint nor work

### ISSUE THREAD

**Issue by HeJerry** [FlagBrew/Checkpoint#446]
**Describe the bug**
in homebrew touch icon can not open checkpoint, back tu homebrew

**To Reproduce**
1. Go to album
2. Click on checkpoint icon
3. Scroll down to alubm homebrew menu
4. See error can not enter app

**Screenshots**
their can't use screenshots capture that error

**Switch:**
- Entrypoint:Atmosphere 1.2.6, Hekate 5.7.0
- System version:13.2.0
- Checkpoint version:3.8.0
- SD Card Filesystem:exFat
- Result code (if available): N/A

**Additional context**
I use SX dongle boot sxos custom system，then  use DeepSea Tool enter Hekate boot Atmosphere EmuNANDc system.
checkpoint can't work

**Comment by GriffinG1** [comment]
Applet more is not supported, use title takeover (hold R launching a title).
