### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by JohnNathanDrake** [FlagBrew/Checkpoint#447]
When placing the file on the memory card and opening it on the switch, the program does nothing (does not open), nor does it even give an error (that code error).

**Comment by GriffinG1** [comment]
Are you using applet mode, or title takeover?

**Comment by JohnNathanDrake** [comment]
I'm entering applet mode (atmosphere)

**Comment by GriffinG1** [comment]
Applet mode is not supported as it doesn't provide enough memory. Use title takeover (launch a game holding R).
