### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NuggetBoy420** [FlagBrew/Checkpoint#448]
**Describe the bug**
I have the latest version of checkpoint, but when I press the icon for checkpoint, my switch screen goes black for a second then I'm in the homebrew launcher again.  idk if its a storage thing or something.

**To Reproduce**

**Expected behavior**

**Screenshots**

**3DS:**
- Entrypoint:
- System version:
- Checkpoint version:
- Result code (if available):

**Switch:**
- Entrypoint:
- System version: 13.2.1
- Checkpoint version: 3.80
- SD Card Filesystem: 21.3 GB
- Result code (if available):

**Additional context**

**Comment by GriffinG1** [comment]
Applet mode is not supported. Use title takeover (launch a game holding R).
