### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NuggetBoy420** [FlagBrew/Checkpoint#449]
**Describe the bug**
For some reason when I click checkpoints icon, my switch screen goes black for 1 second then it flicks back to me in the homebrew menu. Does Anyone know what to do?

**To Reproduce**

**Expected behavior**

**Screenshots**

**3DS:**
- Entrypoint:
- System version:
- Checkpoint version:
- Result code (if available):

**Switch:**
- Entrypoint: Homebrew Menu
- System version: 13.2.1
- Checkpoint version: 3.8.0
- SD Card Filesystem: 21.3 GB
- Result code (if available):

**Additional context**

**Comment by GriffinG1** [comment]
I just answered you in #448. Don't just make a new issue. Closing as duplicate.
