### ISSUE TITLE
Title not showing up in Checkpoint

### ISSUE THREAD

**Issue by somebudthing** [FlagBrew/Checkpoint#452]
I have about 12 games on my 2DS with cfw. None of them are homebrew, although a few were installed through fbi via cias. Only 8 of my games show up in the Checkpoint menu.
There's one specific game I want to use Checkpoint on, and it isn't showing up even though I've created save data for it. How can I get this game to show up in the Checkpoint menu?

To add: the games showing up in Checkpoint are both eshop downloads and fbi installs

**Comment by GriffinG1** [comment]
![B408A5BC-AC6B-4922-B488-C640389965B6](https://user-images.githubusercontent.com/28538707/155934107-b624cd34-3482-4c9c-805d-e7f1291c108b.jpeg)
