### ISSUE TITLE
Majora's mask 3d cheats not working

### ISSUE THREAD

**Issue by KingDeku86** [FlagBrew/Checkpoint#453]
**Describe the bug**
Any and all cheats don't work

**To Reproduce**
1. Go to Majora's mask 3d
2. activate cheats you want
3. See error

**Expected behavior**
Cheats are suppost to activate

**3DS:**
- System version: 11.15
- Checkpoint version: 3.7.4

**Comment by GriffinG1** [comment]
Cheats questions go in the sharkive repository. Transferring this issue there.
