### ISSUE TITLE
Question: Add Your Own Cheats?

### ISSUE THREAD

**Issue by Omega207** [FlagBrew/Checkpoint#454]
**Is your feature request related to a problem? Please describe.**
I'd like to know how to add your own cheats. I want to see if I could add some Miitopia for 3DS cheats, since I can't get the [NTR framework](https://gbatemp.net/threads/release-miitopia-ntr-plugin.480438/) for it working. At this time of writing, there are no cheats for Miitopia 3DS.

**Describe the solution you'd like**
I want to know any fixes to this that would help me work out the problem.

**Describe alternatives you've considered**
If there is no way to do any of this, please guide me to a related issue that had the same problem as I'm having.

**Additional context**
Proof of no cheats for Miitopia:
![Miitopia-no-cheats-bottom](https://user-images.githubusercontent.com/97362960/158240385-b4ae10b9-c7eb-4f86-9806-d4e5bc15cb88.png)

Thanks!
Omega207

**Comment by GriffinG1** [comment]
Please refer to [Sharkive](https://github.com/FlagBrew/Sharkive)'s README for instructions on adding your own cheats. Any further cheats related questions should be directed to that repository.

**Comment by Omega207** [comment]
Sorry. That felt silly.
