### ISSUE TITLE
Do you want to continue to use the 3.7.4 version?

### ISSUE THREAD

**Issue by OvvvvO** [FlagBrew/Checkpoint#459]
I read the description of the latest version, there are some problems in version 3.8.0 and it has been removed from the shelves, but I see that it needs to be used with version 3.7.4, what does it mean?

My game console 3DS is currently installed with Checkpoint version 3.7.4, how should I use the following files?
![QQ截图20220515000604](https://user-images.githubusercontent.com/105556777/168440016-4073bae4-907c-4e57-8d3a-9a73d06c7a81.png)

**Comment by Masamune3210** [comment]
well, none of those, you need a CIA or a 3DS file, nro is for switch

**Comment by GriffinG1** [comment]
You are looking at the 3.8.0 release. There's a link to 3.7.4 in the release notes.
