### ISSUE TITLE
Bug Report: "Python failure" (i think) when i was compiling on win11

### ISSUE THREAD

**Issue by Robichani6-1** [FlagBrew/Checkpoint#463]
PS C:\Users\rober\Escritorio\Dev\3DS\Checkpoint> make -j16
make[1]: Entering directory '/home/rober/Escritorio/Dev/3DS/Checkpoint/3ds'
make[1]: Entering directory '/home/rober/Escritorio/Dev/3DS/Checkpoint/switch'
C:\Users\rober\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\rober\\Escritorio\\Dev\\3DS\\Checkpoint\\sharkive\\joiner.py': [Errno 2] No such file or directory
make[1]: *** [Makefile:199: cheats] Error 2
make[1]: Leaving directory '/home/rober/Escritorio/Dev/3DS/Checkpoint/3ds'
make: *** [Makefile:31: 3ds_cheats] Error 2
make: *** Waiting for unfinished jobs....
C:\Users\rober\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\rober\\Escritorio\\Dev\\3DS\\Checkpoint\\sharkive\\joiner.py': [Errno 2] No such file or directory
make[1]: *** [Makefile:185: cheats] Error 2
make[1]: Leaving directory '/home/rober/Escritorio/Dev/3DS/Checkpoint/switch'
make: *** [Makefile:34: switch_cheats] Error 2
PS C:\Users\rober\Escritorio\Dev\3DS\Checkpoint>

**Comment by piepie62** [comment]
You did not recursively clone the repository, causing submodules to not be populated. If you downloaded a source ZIP, don't do that and instead use `git clone --recursive`, if you didn't, run both `git submodule init` and `git submodule update`
