### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Reiji456** [FlagBrew/Checkpoint#465]
**Describe the bug**
Super Smash Bros (not updated. Not dlc installed) doesn't appear in the app

1. Back up 
2. Delete the game with FBI (delete title and ticket)
3. Install game
4. Doesn't appear any longe

**Expected behavior**
I hoped that I could at least try to backups again, but I just can't

Old 3DS
- Entrypoint: (sorry I don't know to much about programming)
- System version: 11.15.0-47U
- Checkpoint version: v3.7.4

**Comment by GriffinG1** [comment]
![A1CEDF32-D7A6-40F1-8F66-C1AD31266367](https://user-images.githubusercontent.com/28538707/187108928-0dca010d-0260-4f31-959a-3a0b864c7f67.jpeg)

Refer to points 1 and 3.
