### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Ophakur** [FlagBrew/Checkpoint#471]
The QR code apparently doesn’t work for me? I’ve been trying to scan it through FBI on my Nintendo 3DS, but it says ‘error’ and that the QR code is invalid as of now. 

Is there something I can do to fix this issue?

**Comment by GriffinG1** [comment]
You should be using [v3.7.4](https://github.com/FlagBrew/Checkpoint/releases/tag/v3.7.4)'s QR, which will still work. Make sure your FBI is up to date as well.
