### ISSUE TITLE
switch 1.0.0 - empty gamelist

### ISSUE THREAD

**Issue by mailwl** [FlagBrew/Checkpoint#74]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Pegaswitch
* System version: 1.0.0
* Expected behaviour: List of saves of games
* Encountered behavior: List is Empty
* Result code (if available): (none)
* Steps to reproduce:
  * Launch Checkpoint

I have 2 saves: for Zelda BOTW and Puyo Pyuo Tetris, none visible.
Maybe add some logging to file, to clarify a reason?

**Comment by BernardoGiordano** [comment]
did you ever run those games once?

**Comment by mailwl** [comment]
yes, both has saves (for BOtW about 10 saves).
later i check latest version of CheckPoint, maybe something changes

**Comment by Strat00s** [comment]
I also have this problem. Backuped few saves from my main Switch, but nothing loads on my 1.0.0 (and I have botw saves there)

**Comment by yellows8** [comment]
" but nothing loads on my 1.0.0" ?

**Comment by Strat00s** [comment]
Nothing loads on my 1.0.0 = no saves load/are listed in Checkpoint (some are on console, some are on sd).

**Comment by BernardoGiordano** [comment]
@Hikari-chin can report this problem as well

**Comment by BernardoGiordano** [comment]
This shouldn't be an issue with Checkpoint anymore
